### ISSUE TITLE
Setting nil cache on URLSessionConfiguration

### ISSUE THREAD

**Issue by kennylevinsen** [dart-lang/http#1003]
The way to disable caching in the Foundation URL Loading System is to set URLSessionConfiguration.urlCache to nil. The same is true for httpCookieStorage and urlCredentialStorage. To customize the behavior, one instead sets them to a suitable implementation. All of the standard configurations have caching, with the ephemeral configuration using a private cache.

While a more complete implementation would allow providing custom cache implementations, my particular use-case only requires the ability to disable it as I manage caching higher up in the stack in a platform-agnostic way. Any caching from URLSession would just be a waste of resources.

**Comment by brianquinlan** [comment]
Can you accomplish the same thing by setting `URLSessionConfiguration.requestCachePolicy` to `URLRequestCachePolicy.reloadIgnoringLocalCacheData`?

**Comment by brianquinlan** [comment]
Got it. I started working on this but right `package:ffigen` seems to have an issue correctly generating code for the `NSURLCache` interface: https://github.com/dart-lang/ffigen/issues/597
