### ISSUE TITLE
Fix url encoded requests

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/http#101]
During the migration we lost support for `application/x-www-form-urlencoded`. Wanted to know if there is any preference on how to fix this @nex3 .

I'm thinking it might make sense to have another constructor for Request.

**Comment by nex3** [comment]
Can we support people just passing a `Map<String, String>` to the existing constructors?

**Comment by donny-dont** [comment]
I'm just not sure how were going to get the `content-type` correct. Still digging through 0.11.x to see how it might be done.

**Comment by nex3** [comment]
We should be able to manipulate headers in the constructor body—we do similar stuff with the encoding already.

**Comment by donny-dont** [comment]
Adding some tests with #102 so this can be implemented properly.

**Comment by donny-dont** [comment]
@nex3 are we going to need to add a read method to get back the map?

**Comment by nex3** [comment]
Let's hold off on that for now until we have a more coherent answer for how to represent a map with multiple values for a given key.

**Comment by donny-dont** [comment]
@nex3 @kevmoo how would you guys feel if `Body` contained the content type? By the time `_adjustHeaders` is hit in `message.dart` its already a `Body` so there isn't a way to determine it without modifying that bit.

**Comment by nex3** [comment]
I think we can handle it more cleanly than changing the shape of the type. What if we just add a `bool formFields` argument to `new Message._()` and `adjustHeaders()` to track whether the body was originally a map?

**Comment by donny-dont** [comment]
@nex3 you can close this
