### ISSUE TITLE
Compatibility Conflict between syncfusion_flutter_maps and matrix Dependencies

### ISSUE THREAD

**Issue by Vinayak0-0** [dart-lang/http#1022]
**Description:**

**Issue Overview:**
I've encountered a compatibility conflict between `syncfusion_flutter_maps` and `matrix` dependencies in a Flutter project. The `syncfusion_flutter_maps` package has a dependency on `http ^1.0.0`, while the `matrix` package requires `http ^0.13.0`. This conflict prevents the two packages from being used together in the same project.

**Steps to Reproduce:**
1. Create a Flutter project.
2. Add both `syncfusion_flutter_maps` (version >=22.1.34) and `matrix` (version >=0.3.0) dependencies to your `pubspec.yaml` file.
3. Run `flutter pub get` to fetch and install the dependencies.

**Expected Behavior:**
The `syncfusion_flutter_maps` and `matrix` packages should be compatible and work together seamlessly within the same Flutter project.

**Actual Behavior:**
A compatibility conflict arises due to the differing requirements for the `http` package version.

**Possible Resolutions:**
- Update the `matrix` package to a version that is compatible with `http ^1.0.0`.

**Comment by natebosch** [comment]
This issue is not actionable from this package. You can file issues with the other packages to update their dependencies on `http` to the latest stable version.
