### ISSUE TITLE
For 302 response status code,  Throwing exception.

### ISSUE THREAD

**Issue by engineer-ece** [dart-lang/http#1026]
# For 302 response status code,  Throwing exception.'

[   +7 ms] I/flutter (16362): **UPLOAD_PROGRESS_DONE** [http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1](http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1)
[ +363 ms] E/flutter (16362):

for the above link try using http is throwing 302 error as .

 **ERROR**:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Response has no Location header for redirect

**Comment by natebosch** [comment]
This looks like an exception thrown because of a bad response from a server.

How does this behavior differ from your expectations?

Can you provide a minimal code sample and explain how you'd expect it to behave differently than it does?

As is, this issue is not actionable.

**Comment by natebosch** [comment]
Ah, looks like this might be a known issue with a planned breaking change to fix it.

Closing in favor of https://github.com/dart-lang/sdk/issues/53618

**Comment by engineer-ece** [comment]
I submitted the api in above comment sir.  I given a request in postman it return 302 as status code, but, when using http package is thrown an error. please check it. once sir.

**Comment by engineer-ece** [comment]
> Ah, looks like this might be a known issue with a planned breaking change to fix it.
> 
> Closing in favor of [dart-lang/sdk#53618](https://github.com/dart-lang/sdk/issues/53618)

# For 302 response status code,  Throwing exception.'

[   +7 ms] I/flutter (16362): **UPLOAD_PROGRESS_DONE** [http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1](http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1)
[ +363 ms] E/flutter (16362):

for the above link try using http is throwing 302 error as .

 **ERROR**:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Response has no Location header for redirect


I tried with postman is working ,but is not working with http pacakage try the above api in postman sir.

**Comment by engineer-ece** [comment]
> Ah, looks like this might be a known issue with a planned breaking change to fix it.
> 
> Closing in favor of [dart-lang/sdk#53618](https://github.com/dart-lang/sdk/issues/53618) issue is not fixed sir, please try the api in postman and check the http package once sir.

**Comment by natebosch** [comment]
> issue is not fixed sir, please try the api in postman and check the http package once sir.

When I try `wget -H "http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1"` I see

```
The destination name is too long (642), reducing to 236
--2023-10-04 20:53:52--  http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1
Resolving testing.ppms.co.in (testing.ppms.co.in)... 65.1.119.118
Connecting to testing.ppms.co.in (testing.ppms.co.in)|65.1.119.118|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: unspecified
ERROR: Redirection (302) without location.
```

Throwing an error looks like the correct behavior to me.

What behavior were you expecting? Can you provide a complete minimal code sample that shows the problem?
