### ISSUE TITLE
Ah, looks like his might be a known issue with a planned breaking change to fix it.

### ISSUE THREAD

**Issue by engineer-ece** [dart-lang/http#1027]
Ah, looks like this might be a known issue with a planned breaking change to fix it.

Closing in favor of https://github.com/dart-lang/sdk/issues/53618

_Originally posted by @natebosch in https://github.com/dart-lang/http/issues/1026#issuecomment-1745676991_
            

# For 302 response status code,  Throwing exception.'

[   +7 ms] I/flutter (16362): **UPLOAD_PROGRESS_DONE** [http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1](http://testing.ppms.co.in/Mobileframex/uploadstorecomplete.aspx?visitdate=2023-10-03%2011%3A36&storeid=38845&intime=2023-10-03%2012%3A28&username=sonudel&outtime=2023-10-03%2012%3A32&project=jj_test&targetid=38845&mobileno=5556556535&versionno=vb0.3&cAccCode=sonudel&cAccType=4&latitude=0&longitude=0&imeino=&Out_Latitude=0&Out_Longitude=0&id=12&type=2&version=13397&store_id=38845&storecode=38845&storename=A1200573%7CSACHIN%20STORE&classificationid=3&classification=Platinum&address=SEEMA%20PURI%20-%201&cityid=27&city=DELHI%20EAST&regionid=1&program_typeid=null&zoneid=null&roletype=Merc&previewdate=&isgeofencingrequired=null&entrydate=03-10-23&chainid=1&clusterid=88&formatid=1&rds_nameid=7&stateid=1)
[ +363 ms] E/flutter (16362):

for the above link try using http is throwing 302 error as .

 **ERROR**:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Response has no Location header for redirect

I try in postman is working , but is not working in http package sir.

**Comment by natebosch** [comment]
Keeping discussion in #1026 1026
