### ISSUE TITLE
Issue with parallel requests

### ISSUE THREAD

**Issue by Patrick-Keenan** [dart-lang/http#1028]
Im having issues trying to run requests in parallel. For context I am using flutter. For the following scenario I have created a new flutter project and only added dart http. My only changes to the flutter skeleton code is adding these requests to the main.dart file in the build of the app. I am running the app on Chrome.

Running my first request, EA1, I consistently get a response in ~2sec. 
<img width="759" alt="Screenshot 2023-10-05 at 2 21 06 PM" src="https://github.com/dart-lang/http/assets/87655487/80c2eaad-ca5f-428e-a5a2-cb7e23131469">
`http.get(Uri.https(
      $apiHost, $ea1RequestPath,
    ));`

Running my second request, request 4E5, I consistently get a response in ~2sec.
<img width="874" alt="Screenshot 2023-10-05 at 2 25 57 PM" src="https://github.com/dart-lang/http/assets/87655487/59245715-d7b1-4c38-a1ea-569395bdbee1">
`http.get(Uri.https(
      $apiHost, $4e5RequestPath,
    ));`

Running one after the other with no await I consistently get a response in ~4sec. 
<img width="872" alt="Screenshot 2023-10-05 at 2 53 19 PM" src="https://github.com/dart-lang/http/assets/87655487/0190be59-f70d-4336-a002-75560b2a7191">
`http.get(Uri.https(
      $apiHost, $ea1RequestPath,
    ));
http.get(Uri.https(
      $apiHost, $4e5RequestPath,
    ));`

Running them twice one after the other with no await I consistently get a response from all of the requests in ~8sec.
<img width="873" alt="Screenshot 2023-10-05 at 2 37 16 PM" src="https://github.com/dart-lang/http/assets/87655487/2b1e16ad-4860-4466-84c0-f0fe5c80249e">
`http.get(Uri.https(
      $apiHost, $ea1RequestPath,
    ));
http.get(Uri.https(
      $apiHost, $ea1RequestPath,
    ));
http.get(Uri.https(
      $apiHost, $4e5RequestPath,
    ));
http.get(Uri.https(
      $apiHost, $4e5RequestPath,
    ));`

Adding more and more requests adds more and more time as if the requests are actually being called sequentially rather than in parallel.

I have tried making parallel requests countless different ways with Future.wait, a shared client, a non shared client, etc.  I have tested this on chrome, an android device, and an iOS device with no difference in behavior. How do I go about making parallel requests in dart?

**Comment by egfconnor** [comment]
I am seeing a similar issue in my Flutter app on iOS. Did you figure something out @Patrick-Keenan? Thanks for any info.

**Comment by natebosch** [comment]
I wouldn't expect requests to be serialized by any of the Dart code. Any strange behavior here is likely due to the server side or the browser.

If anyone does think that this library causes requests to run serially and has a complete minimal reproduction case we can take a look.

**Comment by egfconnor** [comment]
@natebosch I agree I believe it is our server side as well. I was investigating our Flutter dart code to make sure it wasn't something silly I was doing wrong though and stumbled upon this issue which seemed oddly similar to my situation. :)
