### ISSUE TITLE
Make BaseRequest (and subclasses) cloneable

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/http#103]
For cases where you implement your own `Client` and override [`send()`](https://github.com/dart-lang/http/blob/e9dbebda39ea48f1f4dc90526854a88ca686c5d7/lib/src/base_client.dart#L149), it doesn't seem right to mutate the caller's `request` object.

It'd be better if `BaseRequest` were easily able to be copied.  Not only would this allow you to keep from mutating the caller's object under their feet, but it would allow you to hide potentially sensitive information from the caller.  e.g. in the use case that spawned this bug, the client is adding authentication headers to the request, and it's an explicit directive from the auth team that the scope of the OAuth token "leakage" be limited to auth libraries (that have undergone security review, etc.).

**Comment by tvolkert** [comment]
Hmm - looks like this may [already exist on `master`](https://github.com/dart-lang/http/blob/e9dbebda39ea48f1f4dc90526854a88ca686c5d7/lib/src/request.dart#L151) and just not be released yet?

**Comment by nex3** [comment]
Yeah, this is one of the goals we're targeting for the refactoring @donny-dont is doing on `master`.

**Comment by nicowernli** [comment]
Hi guys, this is an old request but I still can't see any of this in the library and I still think it should be part of the lib.

I think that a method like `copy` or `copyWith` replacing certain values of the request will be really usefull, specially if you want to automatically modify the request on the `send` method.
