### ISSUE TITLE
Add support for progress events

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/http#104]
Is it possible to add support for progress event for both upload and download phases ?

**Comment by nex3** [comment]
I can't see a clean way to integrate this into the API. The browser client can potentially add event streams to `Response.context`, but we can't return a `Response` object until the request has been fully sent, which means you wouldn't get any upload events.

In general, this package's goal is to create a *cross-platform* HTTP API. If you need advanced features that only work on a certain platform, such as progress reporting, you may be better off using the native APIs.

**Comment by dam0vm3nt** [comment]
actually I think those events should belong to the request. I've done it in my own `browser_client` implementation and I think it's not so bad. Take a look at [this](https://github.com/polymer-dart/html5/blob/master/lib/browser_client.dart) if you want.

**Comment by nex3** [comment]
> actually I think those events should belong to the request.

That doesn't match the structure of the package. The request flows into nested layers of clients; the base client (in this case `BrowserClient`) can't set fields on the request that the caller will see.

> Take a look at [this](https://github.com/polymer-dart/html5/blob/master/lib/browser_client.dart) if you want.

This link looks broken.

**Comment by dam0vm3nt** [comment]
@nex3 in the meanwhile it has moved [here](https://github.com/polymer-dart/html5_browser_client/blob/master/lib/browser_client.dart) 

I've used an `expando` to "extend" the request object with those extra properties, so this issue to me is  can actually stay closed. But I post this anyway because I think it can be usefull for you.
