### ISSUE TITLE
version 1.1.1 conflict between the http package and the flutter

### ISSUE THREAD

**Issue by ziyad-aljohani** [dart-lang/http#1052]
When I tried to update to http package version 1.1.1 i got this

```
Note: web is pinned to version 0.3.0 by flutter from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because http >=1.1.1 depends on web ^0.4.0 and every version of flutter from sdk depends on web 0.3.0, http >=1.1.1 is incompatible with flutter from sdk.
```

**Comment by vijayvaghela72** [comment]
I am facing the same issue. Is there any solution available?

**Comment by vijayvaghela72** [comment]
any possible solution @nex3 @sethladd  @kevmoo ?

**Comment by kevmoo** [comment]
Do you *need* `1.1.1` or would just like to have the latest?

The solution is to upgrade to the latest Flutter release.

**Comment by vijayvaghela72** [comment]
@kevmoo sir ,

i am using latest version flutter ,
and also latest version http package 1.1.1

but facing this issue ,
<img width="698" alt="Screenshot 2023-11-25 at 12 56 19 PM" src="https://github.com/dart-lang/http/assets/61325761/981e1f79-0481-4d6b-95a4-62c762c6abb6">

**Comment by kevmoo** [comment]
> @kevmoo sir ,
> 
> i am using latest version flutter , and also latest version http package 1.1.1
> 
> but facing this issue , <img alt="Screenshot 2023-11-25 at 12 56 19 PM" width="698" src="https://private-user-images.githubusercontent.com/61325761/285571433-981e1f79-0481-4d6b-95a4-62c762c6abb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ2NTksIm5iZiI6MTcwMDkyNDM1OSwicGF0aCI6Ii82MTMyNTc2MS8yODU1NzE0MzMtOTgxZTFmNzktMDQ4MS00ZDZiLTk1YTQtNjJjNzYyYzZhYmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNDg4YmUzNTBhZTAyOGJmOGQ3MTZhNWI1NTczMjZkN2JmNWE4OGMzZDRkNTFiZWNiMTZkYTgyYmU3ZmUxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLHG_-yQbOK7wWHeNr6SwQJ-p4sRTeHibrl8IIJCOSc">

I don't see an issue there...

**Comment by vijayvaghela72** [comment]
yes you are right but i am still getting same error if i use latest http version in my project.

**Comment by vijayvaghela72** [comment]
let me know if there is any possible solution . for this because i have to use downgraded version of http. for this issue .

**Comment by vijayvaghela72** [comment]
<img width="709" alt="Screenshot 2023-11-25 at 8 37 14 PM" src="https://github.com/dart-lang/http/assets/61325761/d67fa22f-f27b-4c59-bb95-15a192afa9cc">


i am only facing issue due to this package 

@kevmoo

**Comment by vijayvaghela72** [comment]
![Uploading Screenshot 2023-11-25 at 8.41.38 PM.png…]()

**Comment by kevmoo** [comment]
Do you *need* 1.1.1? Sometimes it just takes a while. Don't stress to get the latest!

**Comment by vijayvaghela72** [comment]
i prefer to use latest version if you have any solution then please let me know.

**Comment by kevmoo** [comment]
@vijayvaghela72 – you'll have to wait for the next stable release of Flutter, I think

**Comment by vijayvaghela72** [comment]
okay waiting .

that means version 1.1.1 is useless for current latest version of flutter ?

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/http/pull/1055

**Comment by kevmoo** [comment]
v1.1.2 is published. Let me know how things work!

**Comment by vijayvaghela72** [comment]
Thank you Mr.@kevmoo  it's working perfectly .
