### ISSUE TITLE
Issue with http/browser_client.dart

### ISSUE THREAD

**Issue by ankitmiyan30** [dart-lang/http#1085]
I use a single codebase for my Flutter mobile, and Flutter web applications and I am using http/browser_client  and package:js/js.dart' for my Flutter web application, But when I am compiling to run on mobile it's giving me the below-mentioned error.

Error when running in the mobile and for web it's working fine -
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/http-0.13.6/lib/src/browser_client.dart:6:8: Error: Dart library 'dart:html' is not available on this platform. 

<img width="578" alt="Screenshot 2023-12-19 at 5 28 24 PM" src="https://github.com/dart-lang/http/assets/30353044/6b1f224a-ba74-41e8-aa11-4c0c79a07829">

**Comment by brianquinlan** [comment]
You can look at [flutter_http_example](https://github.com/dart-lang/http/tree/master/pkgs/flutter_http_example) for a demonstration of how to structure your code to customize the `Client`.
