### ISSUE TITLE
Feature add Interceptor

### ISSUE THREAD

**Issue by pcariel** [dart-lang/http#109]
Hi, friends. Is it possible to add Interceptor? AngularTS 4.3 [link](https://angular.io/guide/http)

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by zoechi** [comment]
How is your question related to Angular TS?
Please provide more information what you need and what you need it for

**Comment by donny-dont** [comment]
`http` 0.12.0+ is middleware based like `shelf`. I have no experience with angular but it looks like what you'd want anyways.

**Comment by nex3** [comment]
Closing since this is basically just middleware.
