### ISSUE TITLE
`prepare_for_embedded.dart` should use a fixed Cronet version

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/http#1100]
[`prepare_for_embedded.dart`](https://github.com/dart-lang/http/blob/master/pkgs/cronet_http/tool/prepare_for_embedded.dart) updates `build.gradle` to use the latest version of Cronet.

This leads to the possible problem that the version of Cronet included in a release may not have been tested.

Instead, we should set an explicit version in `prepare_for_embedded.dart`.

**Comment by brianquinlan** [comment]
Any thoughts about this @AlexV525 ?

**Comment by AlexV525** [comment]
It should be a corresponding version of the GMS version. Is the dependabot be able to do this?

**Comment by brianquinlan** [comment]
Do the GMS and embedded versions track identically? If so, we can just replace "com.google.android.gms:play-services-cronet" with "org.chromium.net:cronet-embedded" in `prepare_for_embedded.dart` and leave the version unchanged.

**Comment by AlexV525** [comment]
> Do the GMS and embedded versions track identically? If so, we can just replace "com.google.android.gms:play-services-cronet" with "org.chromium.net:cronet-embedded" in `prepare_for_embedded.dart` and leave the version unchanged.

Unfortunately no

**Comment by brianquinlan** [comment]
I don't know the answer regarding dependabot.

**Comment by AlexV525** [comment]
Well that is just my idea. I'll do some investigation about it, before that we can find the correct version and apply it first.

**Comment by AlexV525** [comment]
@brianquinlan Are you able contact owners of Cronet to know about version mapping between GMS and non-GMS versions?
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/components/cronet/OWNERS

**Comment by brianquinlan** [comment]
This is obsolete.
