### ISSUE TITLE
`package:cronet_http_embedded` needs a new name and publisher

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/http#1105]
@AlexV525 

It is not possible to transfer `package:cronet_http_embedded` to another publisher - this is process limitation for Google-owned packages.

So we need to pick a new name so that it can be published by another publisher, i.e., "flutter.cn". We can update the `package:cronet_http_embedded` package page to point to the new package.

Maybe one of:

- `package:cronet_embedded_http`
- `package:cronet_http_noplay`  # I like this one - it makes it clear why you would use it.
- `package:cronet_http_embed`

But I'm open to other names.

**Comment by petrnymsa** [comment]
+1 for **package:cronet_http_noplay**

**Comment by AlexV525** [comment]
Okay I'm going to open the discussion on X. Hope we can get many thoughts!

**Comment by AlexV525** [comment]
+1 for **package:cronet_http_embed**

**Comment by cenumi** [comment]
+1 for package:cronet_http_noplay

**Comment by AlexV525** [comment]
> +1 for package:cronet_http_noplay

Please vote with 👍

**Comment by AlexV525** [comment]
What if we can use `dart-define` to conditionally import the dependency?

**Comment by Dan-Crane** [comment]
* `package:pure_cronet`
* `package:naked_cronet`

**Comment by brianquinlan** [comment]
> What if we can use `dart-define` to conditionally import the dependency?

You mean in the gradle file?

**Comment by AlexV525** [comment]
> > What if we can use `dart-define` to conditionally import the dependency?
> 
> You mean in the gradle file?

Yes. See #1111.

**Comment by AlexV525** [comment]
Could you sync the status of the embedding package later on at here? @brianquinlan

**Comment by brianquinlan** [comment]
Yes

**Comment by AlexV525** [comment]
Okay I saw the release. The `cronet_http_embedded` package is now deprecated and the `cronet_http` was published with the corresponding feature.
- https://pub.dev/packages/cronet_http
- https://pub.dev/packages/cronet_http_embedded
