### ISSUE TITLE
Is it possible to update dependencies its blocking another package i need to use

### ISSUE THREAD

**Issue by Yoda-Man** [dart-lang/http#1127]
http 1.2.0 (was 1.1.2)
  js 0.6.7 (0.7.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)

**Comment by Yoda-Man** [comment]
js 0.7.0

**Comment by brianquinlan** [comment]
What package are you referring to?
