### ISSUE TITLE
CupertinoClient close method doesn't close the connection

### ISSUE THREAD

**Issue by veloce** [dart-lang/http#1131]
`CupertinoClient` doesn't close the underlying connection when calling `close()` on it. It will just prevent sending further requests.

It is an issue because a persistent connection won't be closed, and we have no way to cancel a pending request.

Also it is not consistent with the behaviour of `IOClient`, which does close the connection.

**Comment by brianquinlan** [comment]
This is interesting:
https://lapcatsoftware.com/articles/NSURLSession.html
https://developer.apple.com/documentation/foundation/nsurlsession/1411538-invalidateandcancel
