### ISSUE TITLE
Add analysis/linting options

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/http#117]
Currently `http` just turns on strong mode in its analysis options. If there is a standard for other official dartlang projects then those options should also be enabled.

**Comment by donny-dont** [comment]
@kevmoo @nex3 would be great to figure that out and then enable the options in one last cleanup so we can pass any travis tests required.

**Comment by nex3** [comment]
I think just having strong mode enabled is fine.

**Comment by srawlins** [comment]
Agreed. This is the most standard and common analysis option. Many projects like to enable a set of lints, but that's pretty open to each project.
