### ISSUE TITLE
http requests fail with `cronetHttpNoPlay=true` with error `java.lang.ClassNotFoundException`

### ISSUE THREAD

**Issue by dreautall** [dart-lang/http#1179]
Hello.

I have an app that works fine with `cronet_http` with the GPS-Cronet. Trying to build the same app with `--dart-define=cronetHttpNoPlay=true` works, but the app is not usable and throws errors on http requests. The error message reads:

```
Exception in Java code called through JNI:
java.lang.ClassNotFoundException: Didn't find class "org/chromium/net/CronetEngine$Builder" on path:
DexPathList[[zip file "/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/base.apk"],nativeLibrary Directories=[/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/lib/arm64,/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/base.apk!/lib/arm64-v8a, /system/lib64,/system/system_ext/lib64]]

java.lang.ClassNotFoundException: Didn't find class "org/chromium/net/CronetEngine$Builder" on path:
DexPDexPathList[[zip file "/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/base.apk"],nativeLibrary Directories=[/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/lib/arm64,/data/app/~~xlxrt1ba2YAQ0amUKmEvNg==/com.dreautall.waterflyiii-AbxaklwneLCpq2CmygW_Jg==/base.apk!/lib/arm64-v8a, /system/lib64,/system/system_ext/lib64]]

at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

pubspec.yaml defines `cronet_http: ^1.2.0`. As no other change is outlined in the documentation, there was no code change from my side anywhere - not sure if I would have to exclude/include something in the Android manifest, gradle build or similar.

The app was built with `flutter build apk --split-debug-info=build/app/outputs/symbols/aab --release --dart-define=cronetHttpNoPlay=true`, the test device of the error message is a Samsung Galaxy A52 running the stock OS, but it also fails on a Pixel 8.

**Comment by veloce** [comment]
I also reproduce this issue either using `flutter build` or `flutter run` command.

It seems that the `cronetHttpNoPlay=true` flag does not work in release mode.

The app works fine with `flutter run --dart-define=cronetHttpNoPlay=true` (I can see the cronet version in the logs), but it ceases to work if I append `--release` (same class not found issue).

**Comment by AlexV525** [comment]
It sounds like a obfuscate issue with native methods, but since they actually exported the same entryport the guess might be incorrect. Could anyone try with `minifyEnabled` disabled?

**Comment by AlexV525** [comment]
https://developer.android.com/build/multidex#multidexkeepproguard-property might be helpful too.

**Comment by KevinCFechtel** [comment]
With minifyEnabled and shrinkResources disabled, the error no longer occurs for me. 
Unfortunately, the multiDexKeepProguard property file did not work for me.

**Comment by AlexV525** [comment]
So the solution we should try is providing the proguard rules that exclude the cronet library. I'll request changes later. Thanks for the feedback.
