### ISSUE TITLE
Add timeout option to package:cronet_http

### ISSUE THREAD

**Issue by techouse** [dart-lang/http#1186]
Hi,

Are there any plans to add a _timeout_ option to `package:cronet_http`?

I'm not sure if a _timeout_ option was omitted by design or by mistake.

The [source code](https://chromium.googlesource.com/chromium/src/+/lkgr/components/cronet/android/java/src/org/chromium/net/urlconnection/CronetHttpURLConnection.java#433) seems to say it's disabled by design 

```java
@Override
public void setConnectTimeout(int timeout) {
    // Per-request connect timeout is not supported because of late binding.
    // Sockets are assigned to requests according to request priorities
    // when sockets are connected. This requires requests with the same host,
    // domain and port to have same timeout.
    Log.d(TAG, "setConnectTimeout is not supported by CronetHttpURLConnection");
}
```

**Comment by brianquinlan** [comment]
Can you use the [`timeout`](https://api.flutter.dev/flutter/dart-async/Future/timeout.html) method on the future returned by the client?

**Comment by techouse** [comment]
Well I could but that's more than just plug & play. I was hoping for a timeout error to be thrown from the send method https://github.com/dart-lang/http/blob/ec73b19578273294d9e289f8b229492f9dd989b0/pkgs/cronet_http/lib/src/cronet_client.dart#L326

**Comment by brianquinlan** [comment]
@techouse I don't think that we should add timeout capabilities for a single client.

See https://github.com/dart-lang/http/issues/21

**Comment by techouse** [comment]
Ok, I've taken your initial suggestion of adding a Future.timeout https://github.com/lejard-h/chopper/pull/604

**Comment by brianquinlan** [comment]
Hey @techouse ,

I thought that you were looking for a per-request timeout.

`timeoutIntervalForRequest` can be used to configure the timeout for all requests made by the `Client`
`connectionTimeout` is per-`Client` and it also only applies to the connection phase of the request - the response can take an arbitrary amount of time.

**Comment by absar** [comment]
Hi @brianquinlan ,
Does it mean there is no cronet equivalent of `cupertino_http.timeoutIntervalForRequest`?
Adding a timeout to client future does not seem appropriate, since it's not going to cancel the request after timeout, secondly the timeout on future will essentially be for the whole response duration e.g. `client.get` as opposed to just request/connection timeout

**Comment by techouse** [comment]
@absar I guess now you can get around the problem by using an [abortTrigger](https://pub.dev/documentation/http/latest/http/Abortable/abortTrigger.html) in combination with a `Completer` and `Timer` or a simple `Fututre.delayed`, as outlined [here](https://github.com/dart-lang/http/tree/master/pkgs/http#aborting-requests).
