### ISSUE TITLE
http 1.2.1 reasonPhrase null-safety issue

### ISSUE THREAD

**Issue by LynoDesu** [dart-lang/http#1190]
After upgrading to http 1.2.1, I get the following errors when trying to build my Flutter app:

> ../../.pub-cache/hosted/pub.dev/http-1.2.1/lib/src/streamed_response.dart:26:13: Error: The parameter 'reasonPhrase' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>       super.reasonPhrase})
>             ^^^^^^^^^^^^
> ../../.pub-cache/hosted/pub.dev/http-1.2.1/lib/src/streamed_response.dart:44:13: Error: The parameter 'reasonPhrase' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>       super.reasonPhrase});
>             ^^^^^^^^^^^^
> ../../.pub-cache/hosted/pub.dev/http-1.2.1/lib/src/streamed_response.dart:26:13: Error: Type 'String' of the optional super-initializer parameter 'reasonPhrase' doesn't allow 'null', but the parameter doesn't have a default value, and the default value can't be copied from the corresponding parameter of the super constructor.
>       super.reasonPhrase})
>             ^^^^^^^^^^^^
> ../../.pub-cache/hosted/pub.dev/http-1.2.1/lib/src/streamed_response.dart:44:13: Error: Type 'String' of the optional super-initializer parameter 'reasonPhrase' doesn't allow 'null', but the parameter doesn't have a default value, and the default value can't be copied from the corresponding parameter of the super constructor.
>       super.reasonPhrase});
>             ^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.

Downgrading to http 1.2.0 fixed my issue, but I have packages such as Firebase that use http 1.2.1.

**Comment by brianquinlan** [comment]
This error doesn't make sense to me - `reasonPhrase` is nullable in the `BaseResponse` super class. Could you try `pub cache clean`?
