### ISSUE TITLE
HTTPS requests not working on iOS when running from flutter web

### ISSUE THREAD

**Issue by mand027** [dart-lang/http#1193]
I have a web app that i developed on flutter 3.19.6 and i am currently using HTTP 1.2.1

`  
var token = await user.getIdToken();
    final http.Response response = await http.get(
    Uri.https(baseApiURL, '/user/${user.uid}'),
        headers: {
          'Authorization': "Bearer $token",
        },
    );
`
i am calling the http this way, but specifically on iOS when running on chrome or safari or any browser the console shows an error that the headers must not be empty. and my token gets shortened into wierd characters.

i already tested on chrome on windows, macOS and android and everything runs smoothly.

**Comment by brianquinlan** [comment]
Could you add the console error to this issue?

**Comment by mand027** [comment]
I checked on detail with my team and the issue was on our backend, we needed to add a lot of security features that iOS requires for https services to work
