### ISSUE TITLE
Closing WebSocket throws error if code is not in range 3000 - 4999

### ISSUE THREAD

**Issue by catapop84** [dart-lang/http#1203]
In `pkgs/web_socket/lib/src/utils.dart` you check if the close code is within the range of 3000 - 4999

Is there a reason for this? basically closing the websocket with code 1000 (  normal closure) will throw an error

in `pkgs/web_socket/lib/src/io_web_socket.dart`

```
  @override
  Future<void> close([int? code, String? reason]) async {
  //...

    // is there a reason why only code between 3000-4999 is accepted?
    checkCloseCode(code);
    checkCloseReason(reason);

  // ...
  }
```

**Comment by brianquinlan** [comment]
Allowing 1000 seems like a good idea.

**Comment by catapop84** [comment]
Hello @brianquinlan , thanks for reply and quick fix. However after I checked the submitted code I have to reopen the issue.
I think you misunderstood , I just give an example that code 1000 (normal close) throws error, but you should allow other codes without throwing an error. 
The official documentation: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code allows any code within range 1000-4999

Hope this helps

**Comment by brianquinlan** [comment]
But it does not allow that for user set codes. From https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#code :

> If specified, the value of this code parameter overrides the automatic setting of the close code for the connection, and instead sets a custom code. The value must be an integer: either 1000, or else a custom code of your choosing in the range 3000-4999. If you specify a code value, you should also specify a [reason](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#reason) value.

**Comment by bhumkong** [comment]
Please see the docs here: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code
It says 1000 - normal closure, 1001 - going away, 1002 - Protocol error, and so on.
These are allowed codes, and I'm getting an error with 1001 code from FastAPI.
Let's allow the whole 1000 - 4999 range please.

**Comment by bhumkong** [comment]
Or, I thought it was about server-sent codes, and we're actually talking about client-sent codes. I guess it's correct then. Sorry for bothering.
