### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by victorcode1** [dart-lang/http#1273]
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/http_parser-4.1.0/lib/src/case_insensitive_map.dart:22:9: Error: Superclass has no constructor named 'CanonicalizedMap.fromEntries'

**Comment by arnbut** [comment]
Same here.

**Comment by nikkraljevic** [comment]
Same here - any workaround?

**Comment by victorcode1** [comment]
> Lo mismo me pasa a mí. ¿Alguna solución alternativa?

Prev versión

**Comment by nikkraljevic** [comment]
was able to get working by implementing:
`dependency_overrides:
  collection: ^1.19.0`

**Comment by brianquinlan** [comment]
Can anyone provide more information about this issue? I'm not seeing this myself.
