### ISSUE TITLE
Latest objective_c changes incompatible with cupertino_http

### ISSUE THREAD

**Issue by kekland** [dart-lang/http#1298]
Hi!

I'm using objective_c (and ffigen) at [87e8f92](https://github.com/dart-lang/native/commit/87e8f924f06458ccba11dda7edc26d607c663d60). It seems like at that version doing anything from objective_c (even just creating an NSString) when cupertino_http is also installed instantly crashes the app with a segmentation fault.

I'm not exactly sure what the issue is. Version 1.1.0 (which is in pub) works fine. From the changelog:

```
1.2.0-wip
- Drop API methods that are deprecated in the oldest versions of iOS and macOS that flutter supports.
- Added ObjCBlock, which is the new user-facing representation of ObjC blocks.
- Migrate to ARC (Automatic Reference Counting).
- Enable ObjC objects and blocks to be sent between isolates.
```

My guess is that it's due to ARC. Here's an example project where the issue can be reproduced: https://github.com/kekland/cupertino_http_objc_issue

cc @liamappelbe (not sure whether it's relevant to you, but tagging just in case)

**Comment by brianquinlan** [comment]
@liamappelbe Does the referenced version of `package:objective_c` require ARC?

**Comment by liamappelbe** [comment]
Yep, package:objective_c and ffigen now use ARC. I haven't released that version yet.

**Comment by brianquinlan** [comment]
@liamappelbe So are your clients required to switch to using ARC?

**Comment by liamappelbe** [comment]
Yeah. It's my understanding that this will become a requirement for all flutter plugin writers soon. It has something to do with flutter using the swift package manager.

**Comment by brianquinlan** [comment]
OK, I guess its time for me to try to get delegates to work in Dart again ;-)
