### ISSUE TITLE
[cupertino_http] Failed to load dynamic library 'cupertino_http.framework/cupertino_http'

### ISSUE THREAD

**Issue by konkab** [dart-lang/http#1301]
I'm getting a crash at runtime with the following message:

> ArgumentError (Invalid argument(s): Failed to load dynamic library 'cupertino_http.framework/cupertino_http': > dlopen(cupertino_http.framework/cupertino_http, 0x0001): tried: > '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS > 17.5.simruntime/Contents/Resources/RuntimeRootcupertino_http.framework/cupertino_http' (no such file),
...

Flutter version: 3.24.1
cupertino_http version: 1.5.1
CocoaPods version: 1.15.2

**Comment by joknjokn** [comment]
@konkab Hi. How did you solve this?
