### ISSUE TITLE
Add "preserveHeaderCase" option to retain original case of HTTP headers

### ISSUE THREAD

**Issue by solismatias** [dart-lang/http#1309]
Hello!

The `http` package currently converts all headers to lowercase, which can cause issues when interacting with certain servers that expect headers in specific cases (`Content-Length` in my case).

A straightforward solution would be to simply change the value in `'pkgs/http/lib/src/io_client.dart'` to `true`, as demonstrated in [this issue](https://github.com/dart-lang/http/pull/805/files):  
![Issue Screenshot](https://github.com/user-attachments/assets/3e6ae699-4375-4f7a-9675-57a3e1e0a867)

However, I propose taking it a step further and **not hardcoding** the value. Instead, I would like to add an option to set this value to `true` when necessary, while leaving it `false` by default. This ensures that existing projects won't be affected by the change unless explicitly opted in.

The final result could look something like this:

```dart
final response = await http.post(
  Uri.parse('https://example.com/api'),
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'User-Agent': 'CustomUserAgent/1.0',
    'Content-Length': contentLength.toString(), // Maintain 'Content-Length' case
  },
  body: encodedBody,
  preserveHeaderCase: true, // Option to preserve header case
);
```

This would require adding the `preserveHeaderCase` property to all HTTP methods, propagating it through the code until it reaches the logic where the header cases are set.

**Which option do you think is more viable?**
I would like to do second option if you agree

P.S. This is my first time contributing to an open-source project. I've read the project's Contributing Guide, but any tips or guidance would be greatly appreciated. Thanks!

**Comment by brianquinlan** [comment]
Hi @solismatias 

Thanks very much for your detailed research!

I am not inclined to change the current behavior for two reasons:
1. [RFC-2616 4.2](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2) specifically states that HTTP headers are case insensitive so any server that requires a particular case is broken
2. any change here would be breaking

Let me know what you think!

**Comment by solismatias** [comment]
Hi, thanks for the response! 
I totally agree with your points so I will close this issue.
Thanks again!
