### ISSUE TITLE
http.get and http.head methods changing https request to http request in FlutterWeb PWA for urls from its own domain

### ISSUE THREAD

**Issue by P5music** [dart-lang/http#1315]
I created a PWA with Flutter Web.
When I use the http.get or http.head functions with an url like
https://www.myapp.info/api/validate/?url=https://external.site.com/path/file.ext
but
it likes it if the url has a fake file (I need a different .htaccess rule for that)
https://www.myapp.info/api/validate/fake_file.ext?url=https://external.site.com/path/file.ext
this is a workaround.

In the former case
the request gets changed into
something starting with
http://www.myapp.info/....
and in the browser I get
an error like 

Mixed Content: The page at 'https://www.myapp.info/appdev/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.myapp.info/api/validate/?url=.....'. This request has been blocked; the content must be served over HTTPS.
ClientException: XMLHttpRequest error., uri=[https://www.myapp.info/api/validate?url=

It is ascertained that the request does not even leave the browser, Chrome or Firefox 
(Firefox calls it Active Mixed Content)

My PWA is not working because of this, for a certain feature, unless I use the workaround and change also the htaccess rule on my server.

No matter how I create the uri request, even with https method itself, it gets changed.
The same using the dio package (using that, the error says that the network layer is the cause)

**Comment by brianquinlan** [comment]
It is very unlikely that this is an issue with `package:http`. Instead, it is likely to be a limitation of `XMLHttpRequest`.

**Comment by P5music** [comment]
Thanks for the response.
Is there any possible reason for it to like the fake_file.ext workaround?
Indeed
https://www.myapp.info/api/validate/fake_file.ext?url=https://external.site.com/path/file.ext
is not altered so there is not an error.
You say it is a limitation of XMLHttpRequest, but it is a bug isn't it? I mean, it does something wrong and the result is an error it  creates by itself.

**Comment by mraleph** [comment]
We will need a way to reproduce this to be able to debug this.

**Comment by P5music** [comment]
Yes it is as I described above, you can definitely reproduce it. Why did you close this thread, please?

**Comment by mraleph** [comment]
> you can definitely reproduce it

The fact that _you_ can reproduce it locally does not really allow us to provide any meaningful help or debug it. 

If you would like help troubleshooting you would need to provide some runnable reproduction for _us_ to be able to reproduce it.

**Comment by P5music** [comment]
However, here is the reproducible code:

`import 'package:http/http.dart'; //or other necessary import here
....

{
url='https://external.site.com/path/file.ext';

//does not work: it is transformed in http request
Uri request = Uri.parse(
        'https://www.myapp.info/api/validate/?url=$url');
    print("validate request " + request.toString());
    final Response response = await httpClient.get(request, headers: {
      'Content-Type': 'application/json',
    });

//does work, as you can see there is something more in the called url that is: fake_file.txt?
    Uri request = Uri.parse(
        'https://www.myapp.info/api/validate/fake_file.txt?url=$url');
    print("validate request " + request.toString());
    final Response response = await httpClient.get(request, headers: {
      'Content-Type': 'application/json',
    });

    }`
    
    You can debug in the browser developer tools to see what the browsers says (it does not even send the request).
    
    Thank you

**Comment by mraleph** [comment]
That snippet does not reproduce it. I have tried this:

```dart
import 'package:http/http.dart' as http;

void main() async {
  final url = 'https://external.site.com/path/file.ext';
//does not work: it is transformed in http request
  try {
    Uri request = Uri.parse('https://www.myapp.info/api/validate/?url=$url');
    print("validate request " + request.toString());
    final response = await http.get(request, headers: {
      'Content-Type': 'application/json',
    });
  } catch (e) {
    print(e);
  }
  try {
    Uri request =
        Uri.parse('https://www.myapp.info/api/validate/fake_file.txt?url=$url');
    print("validate request " + request.toString());
    final response = await http.get(request, headers: {
      'Content-Type': 'application/json',
    });
  } catch (e) {
    print(e);
  }
}
```

and I don't see any rewriting of `https` to `http`. The request is being sent (and fails) as an `https` request.

Are you sure you don't have some extension installed in the browser that potentially rewrites these?

**Comment by P5music** [comment]
I cannot reproduce the issue now, as you also experienced, although I cannot edit the htaccess rule on my server now to perform further tests with real urls of my webapp.
The request is not altered, in fact, so it should work fine.
I think it was silently fixed in the release published after this issue was opened. I hope it is not an issue now as it seems.
Best regards
