### ISSUE TITLE
IoClient opens a new Socket connection every time send() is called

### ISSUE THREAD

**Issue by kharland** [dart-lang/http#137]
On this line: https://github.com/dart-lang/http/blob/master/lib/src/io_client.dart#L45

The presence of the `HttpClient.close`, method seems to communicate that, if one never calls close, the underlying socket connection is never closed.   This also makes me believe that there is one socket per HttpClient.  

This is not true though.  Consider the code
```dart
import 'dart:io';
import 'dart:async';

Future<Null> main(List<String> args) async {
        var client = new HttpClient();
        var futures = <Future>[];
        int numConnections = int.parse(args.first);

        print('Opening $numConnections connections');
        for (int i=0; i < numConnections; i++) {
                futures.add(client.openUrl('GET', Uri.parse('https://www.google.com')));
        }
        await Future.wait(futures);
        print('Opened all connections');
}
```

If you save this to `example.dart` and run with 
```sh
dart example.dart 1000
````
You can run `sudo lsof -i | grep dart` and you will see a thousand open socket connections with a pid matching the command you just ran.

This is misleading because my application might never call `close()` intentionally to keep a connection alive.  I won't know that this will eventually cause my system to run out of file descriptors.

**Comment by nex3** [comment]
We can't do much here other than what the underlying `dart:io` [`HttpClient`](https://api.dartlang.org/stable/1.24.2/dart-io/HttpClient-class.html) does. Here's what its documentation says about resource reuse:

> The HttpClient supports persistent connections and caches network connections to reuse them for multiple requests whenever possible. This means that network connections can be kept open for some time after a request has completed. Use HttpClient.close to force the HttpClient object to shut down and to close the idle network connections.

In your example, you're opening many connections in parallel, which inherently requires multiple sockets (something I think http2 fixes, incidentally). If you let some of those connections close before opening new ones, I think the sockets would be reused assuming the server supports persistent connections, but as the `dart:io` documentation indicates that reuse is on a best-effort basis.
