### ISSUE TITLE
Using package:http carries ~100kB cost

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/http#139]
Reproduction case @ https://github.com/matanlurey/http-browser-benchmark

Significant parts:

* [ ] Uses ~30kB more from `dart:core`, I assume this is use of `Uri`.
* [ ] Brings in `package:path` (~10kB).
* [x] Brings in `package:stack_trace` (~8kB).
* [ ] Brings in `package:source_span`(~6kB).
* [ ] Brings in `package:http_parser`, `string_scanner` (~4kB combined).
* [ ] Brings in an extra ~6kB from `dart:convert`.

This is an issue when trying to use this package for mobile web applications. I can't see a clear reason _why_ I need 100kB more for simple JSON requests given that we aren't using any of the other functionality.

**Comment by nex3** [comment]
I'd definitely like to get the size down as much as possible without hurting functionality. The `stack_trace` dependency has already been removed in #115 (on master) and #123 (on 0.11.x). I think I can get rid of the `source_span` and `path` dependencies too once https://github.com/dart-lang/sdk/issues/30962 and https://github.com/dart-lang/sdk/issues/30963 are fixed. I believe the code size hit from `Uri` will be also be vastly smaller once the changes described in https://github.com/dart-lang/sdk/issues/29420#issuecomment-339263063 happen and the class becomes a thin shim over the browser's URL support.

**Comment by natebosch** [comment]
Closing since this is not something we plan to push on.

`source_span` is no longer a dependency.

`path` could be dropped if we re-implement `basename`, but that doesn't look straightforward enough to be worthwhile.

It's unlikely we'll be able to drop the dep on `http_parser`
