### ISSUE TITLE
Is the minimum version requirement too high？

### ISSUE THREAD

**Issue by dashixiong91** [dart-lang/http#1394]
I don't want to use WebSocket, but I have to set the minimum version to 13.0, which I think is very bad

**Comment by dashixiong91** [comment]
Can the minimum version requirement for iOS be restored to be consistent with Flutter framework, so that those who want to use WebSocket can check its version at runtime

**Comment by brianquinlan** [comment]
I'm looking into this now.

**Comment by brianquinlan** [comment]
Hi @dashixiong91 

I don't have an easy way of testing earlier versions of iOS. XCode only supports iOS 15 or later. The same is true of [futureware-tech/simulator-action](https://github.com/futureware-tech/simulator-action), which is what we use in our GitHub workflow.

Can you think of another way to ensure that `package:cupertino_http` works with older iOS versions?

**Comment by brianquinlan** [comment]
Also, iOS 13+ include the vast majority of iOS users: https://iosref.com/ios-usage
