### ISSUE TITLE
http library just can't return all response headers.

### ISSUE THREAD

**Issue by verybox0** [dart-lang/http#1396]
Hi, not sure if it's a bug, or some setting issue.

I did http post, but, it can't retrieve all response headers, it only seems retrieve "Content-Type" from response headers, no more.

below is my post code, no fancy.

```
var apiUrl = '${rootUrl}api/auth/login';
      final response=await http.post(
          Uri.parse(apiUrl),
          headers: <String,String> {
            "Content-Type": "application/json; charset=UTF-8",
          },
          body: jsonEncode({
            "userName": userName,
            "password": password,
          })
      );
      print(response.headers);   
```

     //only 1 response header printed - ContentType, even there are many responses header from the server.

**Comment by verybox0** [comment]
I just did more test, seems it works fine in Android Emulator, it can retrieve all response headers.

However, when I try Edge/Chrome, it doesn't return all response headers.

**Comment by verybox0** [comment]
did test the build Windows (desktop), seems ok, so, seems only affects Web environment. 

so, in Web env (chrome/edge), it seems it doesn't return all response headers. Not sure if some settings need to be set in the browser itself.

**Comment by mraleph** [comment]
Most likely cors related. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by mraleph** [comment]
I am going to close this because I think the issue you are seeing is explained by browser behavior.

**Comment by verybox0** [comment]
Thanks Slava:

I can confirm, it is affected by "Access-Control-Expose-Headers" which from
Server side, thanks.

Cheer

Bin.


Slava Egorov ***@***.***> 于2024年11月16日周六 03:54写道：
