### ISSUE TITLE
Update docs, there are no constructor http.MultipartFile.fromFile

### ISSUE THREAD

**Issue by dnp1** [dart-lang/http#140]
The constructor http.MultipartFile.fromFile is mentioned here: https://www.dartdocs.org/documentation/http/0.11.3%2B16/http/MultipartRequest-class.html

But it doesn't exists

**Comment by nex3** [comment]
The erroneous documentation has already been removed on `master`, so I'm going to close this.

**Comment by genesiscz** [comment]
There's a minor mistake in the example on that page, 

```
var uri = Uri.parse("http://pub.dartlang.org/packages/create"); // uri
var request = new http.MultipartRequest("POST", url); // url
```
