### ISSUE TITLE
Authorization header is removed in redirections

### ISSUE THREAD

**Issue by victorcatn** [dart-lang/http#1402]
```dart
final client = CupertinoClient.fromSessionConfiguration(
        URLSessionConfiguration.ephemeralSessionConfiguration(),
      );
client.get(
              Uri.parse('https://example.com/redirect'),
              headers: {
                'authorization': 'mytoken',
                'X-test': 'test',
              },
            );
```
If `/redirect` returns a 301 redirection the second request made by `CupertinoClient` does not have the `authorization` header, however, the `X-test` header is kept in the second request.
This problem is not present in `IOClient` or `CronetClient`, they include the authorization header in both requests

**Comment by brianquinlan** [comment]
Apple's considers certain headers reserved https://developer.apple.com/documentation/foundation/nsurlrequest?language=objc and does not preserve them in redirects. The relevant part is:

> If you set a value for one of these reserved headers, the system may ignore the value you set, or overwrite it with its own value, or simply not send it. Moreover, the exact behavior may change over time. To avoid confusing problems like this, do not set these headers directly.
