### ISSUE TITLE
Ios build error

### ISSUE THREAD

**Issue by the-best-is-best** [dart-lang/http#1404]
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/http-1.2.2/lib/src/browser_client.dart:6:8: Error: Dart library 'dart:js_interop' is not available on this platform.

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.

**Comment by 2tick** [comment]
Did you found solution for this issue?

**Comment by the-best-is-best** [comment]
Sorry I don't use http now I use Dio only

**Comment by 2tick** [comment]
I am also not using http....more packages in my pubspec list are using http...Is there any to solve this?
