### ISSUE TITLE
Resource timing info for Http(s) call?

### ISSUE THREAD

**Issue by sureshg** [dart-lang/http#141]
Is there any way to get event callbacks for the following operations when making an Http(s) request using this package?
```requestInitiated
dnsStart
dnsEnd
connectStart
secureConnectStart
secureConnectEnd
connectEnd
requestStart
requestEnd
responseStart
responseEnd
``` 

I am looking for something similar to the analytics API available in OKHttp (https://github.com/square/okhttp/issues/270)

**Comment by nex3** [comment]
This is a better request to make against `dart:io`'s HTTP implementation. This package is designed as a *cross-platform* HTTP API, which means that it generally supports the least common denominator of features across all platforms. We wouldn't be able to support these events for the web platform.

**Comment by sureshg** [comment]
@nex3 thanks. Is there any separate GitHub repo for `dart:io HTTP` or is it under the `sdk` repo?

**Comment by nex3** [comment]
It's in [dart-lang/sdk](/dart-lang/sdk).
