### ISSUE TITLE
Any way to get progress indication?

### ISSUE THREAD

**Issue by pablote** [dart-lang/http#153]
I'm mostly interested in getting the upload progress of a MultipartRequest. Thanks.

**Comment by nex3** [comment]
Unfortunately, there's not. The goal of this package is to provide an API that works across all platforms, which means it only supports features that work everywhere. `dart:io`'s HTTP API doesn't expose any progress information, so we can't really do so here.

If you're just writing for the browser, you can use `dart:html`'s [HTTP API](https://api.dartlang.org/stable/1.24.3/dart-html/HttpRequest-class.html) directly, which provides [access to progress events](https://api.dartlang.org/stable/1.24.3/dart-html/HttpRequestEventTarget/onProgress.html).
