### ISSUE TITLE
   Failed host lookup: 'www.xyz.com' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by gbfarah** [dart-lang/http#1645]
We are getting this issue on Android device even though it is connected to internet and the server is up....

when calling several times over a 5 min period the above error is encountered

 var channel = IOWebSocketChannel.connect(Uri.parse(url), connectTimeout: const Duration(seconds: 3));

What is strange is that on the same device and the same time when opening the URL in chrome there are no issues

Anyone else getting this issue

**Comment by feriyalsusanto** [comment]
Hi, any update regarding this issue? I still encountered the issue if my app is in bacgkround. Thanks!
