### ISSUE TITLE
MultipartRequest should deal with none-English encoding things

### ISSUE THREAD

**Issue by jinfagang** [dart-lang/http#165]
I don't konw if this repo has maintainers in non-English people or not, as many other guys showed out that, the MultipartRequest just can not post `中文字符`  or other none-English word to server.
It will set to be null. This is not server side problem, cause I tried both django and go, all have this issue, but using postman or Android native codes are just works fine.
**Hope maintainers test this issue, this is really immergency as http is a so important basic library....**

**Comment by donny-dont** [comment]
@jinfagang can you please provide a test for the issues you are seeing so we can figure out what's going on?

**Comment by cskau-g** [comment]
This issue is many months old now without a follow-up with the necessary information, so I'll close it for now.
Feel free to reopen this issue if you have an example of some code that doesn't work as intended.
Thanks
