### ISSUE TITLE
second example doesn't run; error: The getter 'bodyFields' isn't defined for the class 'Response'

### ISSUE THREAD

**Issue by eturk1** [dart-lang/http#173]
The second example on the <> Code page at github doesn't run.
Error in Dart analysis: error: The getter 'bodyFields' isn't defined for the class 'Response'. 

`var client = new http.Client();
client.post(
    "http://example.com/whatsit/create",
    body: {"name": "doodle", "color": "blue"})
  .then((response) => client.get(response.bodyFields['uri']))
  .then((response) => print(response.body))
  .whenComplete(client.close);`

**Comment by cskau-g** [comment]
Thank you for reporting this, @eturk1!
 
The code snippet in question is the second snippet from the [README](https://github.com/dart-lang/http/blob/master/README.md).
[bodyFields is only defined on Requests](https://pub.dartlang.org/documentation/http/latest/http/Request/bodyFields.html).

**Comment by eturk1** [comment]
It seems persistent connection won't work anyway as cookies aren't managed so the server doesn't know we're the same client between calls?

I have to on this package & had to use dart.io so I could manually maintain the cookies.

**Comment by mit-mit** [comment]
@cskau-g can you clarify what this should be changed to?

**Comment by eturk1** [comment]
I think the first thing to complete is sample code in the doc that works. 
Don't want people trying the code if it's broken.

Then maybe a feature request for bodyFields implementation?

**Comment by iamsourav37** [comment]
add await keyword, it works

**Comment by Mabsten** [comment]
> 
> 
> add await keyword, it works

`Request.bodyFields` does not exist, how can the example works by adding an `await`? It is not an issue related to Future.

**Comment by natebosch** [comment]
I don't think a `bodyFields` on `Response` is likely to be very useful - is it common for servers to use this encoding in a response?

**Comment by JuliousFrost** [comment]
> add await keyword, it works

Worked for me
