### ISSUE TITLE
Make HttpStatus public

### ISSUE THREAD

**Issue by Herohtar** [dart-lang/http#179]
When working with the `http` package, sometimes you might want to check the value of `Response.statusCode`, but the `HttpStatus` class isn't public, so you're stuck with using integer values unless you import `dart:io`. However, it seems a bit much to import the Dart IO package when your project doesn't depend on it just so you can use `HttpStatus`. It makes more sense for a package specifically for HTTP requests to provide that, and since it already has its own it just needs to export it.

**Comment by zoechi** [comment]
There is no `HttpStatus` in this package, only integers.
You can use https://pub.dartlang.org/packages/http_status or https://pub.dartlang.org/packages/shelf_exception_response#-versions-tab- to get constants.

**Comment by Herohtar** [comment]
You're right, I think I was looking at the wrong file when I saw the HttpStatus class. Thanks for the suggestions!
