### ISSUE TITLE
library import issue on mac for http: "^0.11.3+17"

### ISSUE THREAD

**Issue by engr-zeeshan** [dart-lang/http#183]
http: "^0.11.3+17" was imported successfully when i was using flutter on windows and successfully built app for android.

While working on mac with http: "^0.11.3+16=7" is providing me with following error

**because every version of flutter_test from sdk depends on http 0.11.3+16 and edsios depends on http ^0.11.3+17, flutter_test from sdk is forbidden.
So, because edsios depends on flutter_test any from sdk, version solving failed.**

Therefore i have to use http: "^0.11.3+16" on mac, however i have update flutter and have latest version. 

Why this could be? Any ideas?

**Comment by techyrajeev** [comment]
same issue here

**Comment by zoechi** [comment]
Sounds like `esidos` needs to allow `0.11.3+16` or `flutter_test` needs to allow `0.11.3+17`.
In both cases it's not `http`s fault.
As workaround you can add to `pubspec.yaml` 
```yml
dependency_overrides:
  http: 0.11.3+17
```

**Comment by SebSob** [comment]
Same issue! Workaround from @zoechi solved this issue for now.

**Comment by cskau-g** [comment]
Sounds like this isn't a `http` issue, and especially with @zoechi's workaround I think we can go ahead and close this issue.

Thanks  @zoechi !
