### ISSUE TITLE
Setup headers on Request

### ISSUE THREAD

**Issue by mightymatth** [dart-lang/http#193]
I want to send request and get response as a stream.
I need to do it with:
`Future<StreamedResponse> send(BaseRequest request);`
So I need to create BaseRequest( or simply Request)

How to set headers to this request if variable `headers` is final and it cannot be set in constructor?

**Comment by zoechi** [comment]
Does the answer to https://stackoverflow.com/questions/51195648/how-do-i-use-streamedrequest-in-dart-http-library-to-upload-a-file help?

**Comment by mightymatth** [comment]
Yes, completely. Thank you.
