### ISSUE TITLE
Allow to modify URL before sending the request from  BaseClient subclass

### ISSUE THREAD

**Issue by abinvp** [dart-lang/http#196]
The doc suggests creating a subclass of `BaseClient` in order to exert fine-grained control over HTTP request and responses. Here is the sample code from the docs.

    class UserAgentClient extends http.BaseClient {
      final String userAgent;
      final http.Client _inner;

      UserAgentClient(this.userAgent, this._inner);

      Future<StreamedResponse> send(BaseRequest request) {
        request.headers['user-agent'] = userAgent;
        request.url.replace(path: '/modified/path'); // Not working
        return _inner.send(request);
      }
    }

As seen in the code the headers can be modified before sending the request which is very useful, however, the URL cannot be modified. I have tried `request.url.replace()` with the required params but doesn't seem to be working. Allowing to modify the URL will help to add logic for switching different URLs based on the environment at one place.

**Comment by zoechi** [comment]
I have code like
```
class CustomHttpClient extends IOClient {
  CustomHttpClient({Map<String, String> headers})
      : this._headers = headers ?? <String, String>{},
        super();

  final Map<String, String> _headers;

  @override
  Future<StreamedResponse> send(BaseRequest request) =>
      super.send(request..headers.addAll(_headers));

  @override
  Future<Response> head(Object url, {Map<String, String> headers}) =>
      super.head(url, headers: headers..addAll(_headers));

  @override
  Future<Response> get(Object url, {Map<String, String> headers}) =>
      super.get(url, headers: (headers ?? _headers)..addAll(_headers));
...
```
Each request type has `url` as a parameter. You can modify it before pasing it to `super.xxx()`

**Comment by abinvp** [comment]
Thanks for the response. My approach was different as I didn't want to override all methods. Here is my code.

`class CustomHttpClient extends http.BaseClient {

  Map<String, String> _headers = {'Content-Type': 'application/json'};
  final http.Client _client;

  CustomHttpClient(this._client);

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    request..headers.addAll(_headers);
    request..url.replace(path: env == 'dev'? devPath : prodPath);
    return _client.send(request);
  }
}`

While the headers are being added, the URL path is not getting updated.

**Comment by abinvp** [comment]
@cskau-g It is in the readme. https://github.com/dart-lang/http#using

**Comment by cskau-g** [comment]
Thank you, I see it now.

In the code I see [BaseRequest.url is final](https://github.com/dart-lang/http/blob/ff36a9dbbe1e69cf9e2453f9cba877eb9acceebd/lib/src/base_request.dart#L26), which makes some sense to me from a design perspective.
So what I'd recommend doing if you intend to have your CustomHttpClient essentially redirect requests, is to construct your alternative request and send that along instead from your intercepting send(..):

```dart
class CustomHttpClient extends http.BaseClient {

  Map<String, String> _headers = {'Content-Type': 'application/json'};
  final http.Client _client;

  CustomHttpClient(this._client);

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    var redirectedRequest = http.Request(
        request.method,
        request.url.replace(path: env == 'dev'? devPath : prodPath));
    redirectedRequest.headers.addAll(_headers);
    return _client.send(redirectedRequest);
  }
}
```

I think this should do what you want.

**Comment by cskau-g** [comment]
To move this issue along, what I think needs to be done:
- BaseRequst.url is final by design and I think that is a valid design choice that should remain.
- The docs _do_ state that the expectation is that a new Request is constructed, so that part of the doc is fine as is too:

> You can also exert more fine-grained control over your requests and responses **by creating Request or StreamedRequest objects yourself** and passing them to Client.send.

- The one thing that perhaps isn't aligned with the above is that the code example right below that part of the doc then goes on to show modifying the `request.headers` instead of constructing a new Request as suggested. Changing the example to do so could be done as an improvement.

**Comment by abinvp** [comment]
Sorry for the delay in response @cskau-g. My current working solution is by constructing a new request object. The confusing part was the example which allows modifying the headers but not the URL.

**Comment by zoechi** [comment]
Can this issue be closed?

**Comment by abinvp** [comment]
Yes, this can be closed.

**Comment by AnEnigmaticBug** [comment]
> Thank you, I see it now.
> 
> In the code I see [BaseRequest.url is final](https://github.com/dart-lang/http/blob/ff36a9dbbe1e69cf9e2453f9cba877eb9acceebd/lib/src/base_request.dart#L26), which makes some sense to me from a design perspective.
> So what I'd recommend doing if you intend to have your CustomHttpClient essentially redirect requests, is to construct your alternative request and send that along instead from your intercepting send(..):
> 
> ```dart
> class CustomHttpClient extends http.BaseClient {
> 
>   Map<String, String> _headers = {'Content-Type': 'application/json'};
>   final http.Client _client;
> 
>   CustomHttpClient(this._client);
> 
>   @override
>   Future<http.StreamedResponse> send(http.BaseRequest request) {
>     var redirectedRequest = http.Request(
>         request.method,
>         request.url.replace(path: env == 'dev'? devPath : prodPath));
>     redirectedRequest.headers.addAll(_headers);
>     return _client.send(redirectedRequest);
>   }
> }
> ```
> 
> I think this should do what you want.

I don't think that this is enough. We also need to copy the encoding and body of the original request.

**Comment by mr-mmmmore** [comment]
> I don't think that this is enough. We also need to copy the encoding and body of the original request.

And to add to this, `BaseRequest` doesn't give access to the specific fields in `Request` (the actual class constructed by methods like `get` or `post` and received here) like `body`...

So the ability to extend the behavior is very limited inside the `send` method.

**Comment by jvmvl** [comment]
> 
> 
> I have code like
> 
> ```
> class CustomHttpClient extends IOClient {
>   CustomHttpClient({Map<String, String> headers})
>       : this._headers = headers ?? <String, String>{},
>         super();
> 
>   final Map<String, String> _headers;
> 
>   @override
>   Future<StreamedResponse> send(BaseRequest request) =>
>       super.send(request..headers.addAll(_headers));
> 
>   @override
>   Future<Response> head(Object url, {Map<String, String> headers}) =>
>       super.head(url, headers: headers..addAll(_headers));
> 
>   @override
>   Future<Response> get(Object url, {Map<String, String> headers}) =>
>       super.get(url, headers: (headers ?? _headers)..addAll(_headers));
> ...
> ```
> 
> Each request type has `url` as a parameter. You can modify it before pasing it to `super.xxx()`

I get this error while trying to use this method, anyone has any idea?

`error: 'GoogleHttpClient.send' ('Future<StreamedResponse> Function(BaseRequest)') isn't a valid override of 'IOClient.send' ('Future<IOStreamedResponse> Function(BaseRequest)'). (invalid_override at [googlesignin] lib\main.dart:35)`

**Comment by jvmvl** [comment]
> 
> 
> I have code like
> 
> ```
> class CustomHttpClient extends IOClient {
>   CustomHttpClient({Map<String, String> headers})
>       : this._headers = headers ?? <String, String>{},
>         super();
> 
>   final Map<String, String> _headers;
> 
>   @override
>   Future<StreamedResponse> send(BaseRequest request) =>
>       super.send(request..headers.addAll(_headers));
> 
>   @override
>   Future<Response> head(Object url, {Map<String, String> headers}) =>
>       super.head(url, headers: headers..addAll(_headers));
> 
>   @override
>   Future<Response> get(Object url, {Map<String, String> headers}) =>
>       super.get(url, headers: (headers ?? _headers)..addAll(_headers));
> ...
> ```
> 
> Each request type has `url` as a parameter. You can modify it before pasing it to `super.xxx()`

This shows the following error :

`error: 'CustomHttpClient.send' ('Future<StreamedResponse> Function(BaseRequest)') isn't a valid override of 'IOClient.send' ('Future<IOStreamedResponse> Function(BaseRequest)'). (invalid_override at [googlesignin] lib\main.dart:51)`

**Comment by Lokesh003Coding** [comment]
Removing some required parameter and adding null check resolved my issue

`import 'package:http/http.dart' as http;
import 'package:http/http.dart';

class CustomHttpClient extends http.BaseClient {
  final Map<String, String> _defaultHeaders = {};
  final http.Client _httpClient = http.Client();
  
  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    return _httpClient.send(request);
  }

  @override
  Future<Response> get(Uri url, {Map<String, String>? headers}) => _httpClient
      .get(url, headers: _mergedHeaders(headers!))
      .timeout(const Duration(seconds: responseTimeoutSeconds));

  @override
  Future<Response> post(url,
          {Map<String, String>? headers, dynamic body, Encoding? encoding}) =>
      _httpClient.post(url,
          headers: _mergedHeaders(headers!), body: body, encoding: encoding);

  @override
  Future<Response> patch(url,
          {Map<String, String>? headers, dynamic body, Encoding? encoding}) =>
      _httpClient.patch(url,
          headers: _mergedHeaders(headers!), body: body, encoding: encoding);

  @override
  Future<Response> put(url,
          {Map<String, String>? headers, dynamic body, Encoding? encoding}) =>
      _httpClient.put(url,
          headers: _mergedHeaders(headers!), body: body, encoding: encoding);

  @override
  Future<Response> head(url, {Map<String, String>? headers}) =>
      _httpClient.head(url, headers: _mergedHeaders(headers!));

  Map<String, String> _mergedHeaders(Map<String, String> headers) =>
      {..._defaultHeaders, ...headers};
}`
