### ISSUE TITLE
Getting raw response

### ISSUE THREAD

**Issue by flddr** [dart-lang/http#207]
Hi,

is it possible to get the **raw** response (`string` / `byte[]`) which is not already handled / consumed anyway?

**Comment by natebosch** [comment]
Do you mean getting the headers and the body all as a `byte[]`? No, that isn't possible as far as I know. What is the motivation?

**Comment by flddr** [comment]
I am figuring out if it is possible in flutter to build a app tool for devs. Say, there are different (browser) engines, HTTP librarys and different system programming languages or dynamic ones. If you look in different channels and networks, people try to figure out, why their (HTTP) microservices works on one thing - but not o another.

Thats because of using such engines, libs and languages to build microservices. The one parses strictly RFC, the other one not. One has a good error handling, the other one is more strict. And, of course, there may be bugs.

It's a difference if you build a response with `Content-Type: text/html; charset=utf-8` or `content-type:text/html;charset="utf-8"` (to make it really noise). So, there are many differences, like ` ` or not or `\r\n` or `\n` or `\n\n` or case for example.

So, with tooling, it sometimes becomes easy to check output of a service. But - thats only as this tools parses it. Without exact raw response one can waste hours or days to find an (sometimes) error.

If i have a look on a raw string response for example, i need seconds to check thousands of things. Seeing the raw (besides parsed) is like magic - you definitevely know, _oups_ `"` _is wrong_.

If not possible, whats the nearest point to get this in flutter / dart?

You would help me a lot :)

**Comment by flddr** [comment]
@natebosch what do you think is best way to archive something like that? Or should i ask somewhere else? Can you help, please? :)

**Comment by natebosch** [comment]
Filed https://github.com/dart-lang/sdk/issues/34825

This isn't a capability that we're likely to put into `package:http` since it's a wrapper around the `dart:io` and `dart:html` capabilities and this would be rather specialized. In any case to even have the option of adding it here we'd need it in both `dart:io` and `dart:html`. I filed a request to add it in `dart:io` since that's what you'd need for flutter. Please `+1` that issue and follow for updates.

Closing since there are no planned actions for this package.

**Comment by flddr** [comment]
Thank you very much :)

**Comment by zoechi** [comment]
@flddr Btw. that's also why I suggested to create the issue in dart-lang/sdk

**Comment by flddr** [comment]
@zoechi I could follow your suggestion some time later, but in that moment i was just irritated about our talk on gitter and directly _closing_ my issued question under topic "**help me writing my app**"

Btw, thank you, i remember :)

**Comment by zoechi** [comment]
@flddr Sorry for that, but keeping issues open which I know they don't make sense in flutter/flutter just to not appear unfriendly, is cumbersome. 
I'm experimenting with different ways how to handle that better.

**Comment by flddr** [comment]
@zoechi the most important thing is to answer an issue request and i would give you a compliment: you are doing this very well :+1: 

My bad :wink:
