### ISSUE TITLE
"keep alive connections" and "connection pooling" and "caching middleware"

### ISSUE THREAD

**Issue by p30arena** [dart-lang/http#209]
### How To ?

"keep alive connections" and "connection pooling" and "caching middleware"

Hi there,
any suggestions on how can I implement the above properly?

**Comment by p30arena** [comment]
This is mentioned in [dart:io](https://api.dartlang.org/stable/2.0.0/dart-io/HttpClient-class.html)

> Closing the HttpClient
> **The HttpClient supports persistent connections and caches network connections to reuse them for multiple requests whenever possible.** This means that network connections can be kept open for some time after a request has completed. Use HttpClient.close to force the HttpClient object to shut down and to close the idle network connections.

is this valid for this library too?

**Comment by cskau-g** [comment]
The http package is a fairly thin wrapper around dart:io that does some basic management of connections and such.
As a rule of thumb, if you want basic functionality use http for the convenience; if you want full control but more manual legwork then use dart:io.

**Comment by p30arena** [comment]
@cskau-g 
Issues are not always bug reports.

https://github.com/dart-lang/sdk/issues/34966
