### ISSUE TITLE
MultipartFile doesn't support content-disposition customization

### ISSUE THREAD

**Issue by stang1013** [dart-lang/http#212]
It only supports content-type and file-name field, if I want to add an extra field( say size), there is no way to do that:

      var mpFile = new http.MultipartFile('file-upload', stream, length,
            filename: basename(imageFile.path),
            contentType: MediaType(fType.item1, fType.item2),
            //size: length
            
            );
      //mpFile.field["content-disposition"] += ";size:" + length;

**Comment by cskau-g** [comment]
`http.MultipartFile` is just an internal representation of a file and (for the most parts) doesn't directly decide how for instance headers are set on the HTTP request/response.

The `MultipartFile.field` member is defined in the source as follows:
```dart
class MultipartFile {
  /// The name of the form field for the file.
  final String field;
```

`Content-Disposition` is a HTTP header which are set in the request/response.

You can have a look at [MultipartRequest](https://github.com/dart-lang/http/blob/master/lib/src/multipart_request.dart) how the fields are handled and potentially make your own custom request class if it does not suit your needs.
