### ISSUE TITLE
TLS 1.2 Support

### ISSUE THREAD

**Issue by kostaa** [dart-lang/http#213]
Is there a plan to add TLS 1.2 support to this library?

**Comment by kaciula** [comment]
@kostaa Do you know what versions of TLS does this package currently support? I need TLS 1.2 in my flutter app and I get handshake exception right now. If this library does not offer TLS 1.2, what are my other options? Thanks for your time.

**Comment by natebosch** [comment]
This package doesn't do anything specific with TLS, it defers to the SDK for that. Are you hitting a situation where a request works with `HttpClient` from `dart:io` and fails here?

**Comment by natebosch** [comment]
Closing since any problems using TLS 1.2 should be tracked in the SDK repo.
