### ISSUE TITLE
type 'OSError' is not a subtype of type 'bool' of 'function result'

### ISSUE THREAD

**Issue by lifenautjoe** [dart-lang/http#214]
Not really sure whether this is an issue with the Dart VM or the `http` package.

I've recently upgraded my Flutter installation which ships with Dart 2.1 ( specifically `version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297`).

When calling `http.get` I get 
```
type 'OSError' is not a subtype of type 'bool' of 'function result'
```

Then expanding the stack trace

````
#0      _NativeSocket.nativeSetOption (dart:io/runtime/binsocket_patch.dart)
#1      _NativeSocket.setOption (dart:io/runtime/binsocket_patch.dart:1082:18)
#2      _RawSocket.setOption (dart:io/runtime/binsocket_patch.dart:1377:15)
#3      _Socket.setOption (dart:io/runtime/binsocket_patch.dart:1641:17)
#4      _ConnectionTarget.connect.<anonymous closure>.<anonymous closure> (dart:_http/http_impl.dart:1952:16)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
````

My guess is that something on 2.1 isn't compatible with the library.

As if it wasn't strange enough, there is no error on the iPhone device simulator, only on the real one.

**Comment by natebosch** [comment]
This looks like a bug in the VM unrelated to this library since it doesn't show up in the stack trace.

My guess is one of the `external` methods has an incorrect type signature. I remember a bunch of them specify `dynamic` because they sometimes return an `OSError`, this one probably still specifies `bool` incorrectly.

https://github.com/dart-lang/sdk/blob/a9abc6461395e3327c7d3c22095ea3bf3de3d075/runtime/bin/socket_patch.dart#L1148-L1149

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/35207

**Comment by lifenautjoe** [comment]
Hi Nate,

Thanks for taking a look and opening up the other issue.


Cheers.
