### ISSUE TITLE
Authorization Header Problem

### ISSUE THREAD

**Issue by AndryHTC** [dart-lang/http#216]
![cattura](https://user-images.githubusercontent.com/29896004/49229182-4974f300-f3ed-11e8-8070-bd36f5a6dafe.PNG)

I used the guidelines of [jwt.io](https://jwt.io/), and with other client services works...
I'm working in Flutter, and using the 'Authorization' header, the compiler gives me this error.

Can someone help me please?

**Comment by thosakwe** [comment]
It looks like you're getting a [redirect loop](https://en.wikipedia.org/wiki/URL_redirection#Redirect_loops).

I don't think this is a problem with the `package:http` client directly.
