### ISSUE TITLE
No Speed deference observed with gzip  parameter

### ISSUE THREAD

**Issue by vuppalasivakumar** [dart-lang/http#220]
Hi,

We are adding gzip in header, but we are getting the response with same speed i.e.., with or without header no speed changes in response. 

"Content-Encoding": "gzip",
 "Accept-Encoding": "gzip, deflate",

**Comment by thosakwe** [comment]
Response compression isn't necessarily a performance feature, though; after all, there is the cost incurred of encoding/decoding to/from gzip. It's more about sending the data, while using less bandwidth.

Besides, the size decrease depends on the being sent to begin with.

**Comment by natebosch** [comment]
Closing since this doesn't appear to be actionable.
