### ISSUE TITLE
Use custom DNS server?

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/http#222]
There's no way to use a custom DNS server, or manually use another IP address to connect to a server.

**Comment by natebosch** [comment]
An IP address can be used as the server part of a URI. 

I don't think it's possible to override DNS lookup behavior on the web, and this package is a cross platform abstraction so adding platform specific behavior would not be appropriate.

**Comment by hacker1024** [comment]
> An IP address can be used as the server part of a URI.

It can, but then the host header needs to be set manually. The problem with that? HTTPS certificates are seen as invalid, since the certificates domain doesn't match.

> I don't think it's possible to override DNS lookup behavior on the web

I'm using this with Flutter, for mobile apps.

I think this issue should be reopened, due to the first point especially.

**Comment by eliezedeck** [comment]
@natebosch This is a **legitimate** use case. This has nothing to do with platforms, hence the fact that Dart provides lookup in the stdlib. So, you should be able to connect to a host manually, get a socket, and provide that connection to a TLS context, then provide that to the HttpClient. Of course, the way it would work is in the reverse order.

In Golang, you can easily do this, where you can override the making of the socket, so you can connect to a different IP if you wish (`DialContext`).

**Comment by natebosch** [comment]
This package is specifically for the capabilities we can provide across platforms. If there is a capability we are unable to deliver on the web, it is not appropriate for this package.

This issue should be considered a duplicate of https://github.com/dart-lang/sdk/issues/36551

We won't have an API in `package:http`, if there is any API it will come from `dart:io` or some other external package.

**Comment by Sominemo** [comment]
This functionally would be really useful for transparent HTTP proxies. Right now to accomplish this kind of trick, you need to work with dart:Io on low level to be able to intercept the Host header, so it makes developers reimplementing built in methods like HttpClient.post.

**Comment by peiyangli** [comment]
This feature is a MUST
