### ISSUE TITLE
Support for SSL pinning or SecurityContext

### ISSUE THREAD

**Issue by PieterAelse** [dart-lang/http#223]
Couldn't find a way to add support for SSL pinning or SecurityContext, is it possible to add?

**Comment by natebosch** [comment]
`SecurityContext` is only available in `dart:io`. This package is cross-compatible with `dart:html`. If you need more precise control over security you should use `dart:io` directly.

Note that you can construct an `IOClient` from this package with any `HttpClient` from `dart:io` if you need something that fits this interface to pass to other code. That client can be constructed with a `SecurityContext` argument.

https://pub.dartlang.org/documentation/http/latest/io_client/IOClient/IOClient.html

**Comment by PieterAelse** [comment]
Ah, missed that. Thanks!

**Comment by davidanaya** [comment]
I'm sorry, but how do I import IOClient?

**Comment by natebosch** [comment]
> I'm sorry, but how do I import IOClient?

`import 'package:http/io_client.dart';`

**Comment by Nico04** [comment]
Any way to have this feature for web (in BrowserClient) ?

**Comment by natebosch** [comment]
> Any way to have this feature for web (in BrowserClient) ?

Not that I'm aware of - the browsers don't expose this to javascript running on the page.
