### ISSUE TITLE
Client sending multiple requests concurrently

### ISSUE THREAD

**Issue by blackhogz** [dart-lang/http#226]
The documentation in the README suggests that a Client instance can be reused to issue multiple requests to the same server. However, is it safe to use a single client to send the requests concurrently (not in a sense with isolates, but as shown in the below example)?

```
var client = Client();
var responses = List<Future<Response>>();
for (int i = 0; i < 1000; i++) {
  responses.add((client.get("https://www.google.com/search?q=$i")));
}
for (var response in responses) {
    await response;
}
client.close();
```

Thanks in advance!

**Comment by natebosch** [comment]
This should be safe to do.
