### ISSUE TITLE
Link broken for BrowserClient class

### ISSUE THREAD

**Issue by flutterprogrammer** [dart-lang/http#229]
The below link doesn't work. 

https://pub.dartlang.org/documentation/http/latest/http.browser_client/BrowserClient-class.html

**Comment by kevmoo** [comment]
@jcollins-g @jonasfj – could this be a pub site and/or dartdoc issue?

**Comment by flutterprogrammer** [comment]
<img width="1011" alt="screen shot 2019-01-18 at 11 59 41 am" src="https://user-images.githubusercontent.com/46630216/51401393-9edd9e80-1b18-11e9-9529-1e39602f443c.png">

The browser client link found in the pub site under the heading **Using on the Browser**.
https://pub.dartlang.org/packages/http

**Comment by jonasfj** [comment]
We're currently on `0.27.0`, we upgraded a few days ago... 

broken:
`https://pub.dartlang.org/documentation/http/latest/http.browser_client/BrowserClient-class.html`
works:
`https://pub.dartlang.org/documentation/http/latest/browser_client/BrowserClient-class.html`

**Comment by natebosch** [comment]
The referenced link is no longer in the README.
