### ISSUE TITLE
No host specified in URI logout.cgi?RequestFile=html/logout.html

### ISSUE THREAD

**Issue by hkxster** [dart-lang/http#230]
E/flutter: [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    Invalid argument(s): No host specified in URI logout.cgi?RequestFile=html/logout.html
    #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2121:9)
    #1      _HttpClient.postUrl (dart:_http/http_impl.dart:2061:49)
    #2      HG8120.getLogout.<anonymous closure> (package:flutter_app/data/hg8xxxx/hg8120.dart:132:38)
    <asynchronous suspension>
    #3      new Future.<anonymous closure> (dart:async/future.dart:176:37)
    #4      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
    #5      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
    #6      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
    #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by natebosch** [comment]
Closing since there hasn't been a response with enough information to diagnose.
