### ISSUE TITLE
package:http/http.dart

### ISSUE THREAD

**Issue by heinzan** [dart-lang/http#231]
Hello everyone i cann't solve that http issue for serveral day.Please help me.
![http](https://user-images.githubusercontent.com/18256757/51626003-f773c800-1f6c-11e9-8fb5-e1a08be8bc21.PNG)
pubspec.yaml

![structure](https://user-images.githubusercontent.com/18256757/51626018-fc387c00-1f6c-11e9-83e2-ae6278c6974b.PNG)
My Project Structure

![httpdart](https://user-images.githubusercontent.com/18256757/51626028-ff336c80-1f6c-11e9-8bef-ffd4ad242959.PNG)
error: Target of URI doesn't exist: 'package:http/http.dart'. 

Android Studio 3.3 Intellij on Mac , Window OS.
I have no idea how can solve that.I reinstall flutter and restart my IDE and other way try.But don't get.

**Comment by zoechi** [comment]
> for serveral day

I assume you tried restarting your IDE.

Does the `.packages` contain an entry for `http` and does it point to an existing directory and does this directory contain `http.dart`?

**Comment by natebosch** [comment]
From the screenshot it looks like you have `http:` as a key at the _top level_ of your pubspec instead of nested under `dependencies`.

What you want it something like:

```yaml
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
```

Note that you generally shouldn't include the least `+1` (or 3rd digit if the major version isn't `0`) in your constraint.

**Comment by heinzan** [comment]
> > for serveral day
> 
> I assume you tried restarting your IDE.
> 
> Does the `.packages` contain an entry for `http` and does it point to an existing directory and does this directory contain `http.dart`?

.packages don't have http and it doesn't point existing directory and this directory contain http.dart.I add  hardcore.but cann't solve

**Comment by heinzan** [comment]
> From the screenshot it looks like you have `http:` as a key at the _top level_ of your pubspec instead of nested under `dependencies`.
> 
> What you want it something like:
> 
> ```yaml
> dependencies:
>   flutter:
>     sdk: flutter
>   http: ^0.12.0
> ```
> 
> Note that you generally shouldn't include the least `+1` (or 3rd digit if the major version isn't `0`) in your constraint.

![flu](https://user-images.githubusercontent.com/18256757/51686577-03b85d80-201f-11e9-9e63-b9eebfb346a7.PNG)
![flu1](https://user-images.githubusercontent.com/18256757/51686590-087d1180-201f-11e9-85ba-688bb7026c23.PNG)

I edited as u say but error happening.I do packages get,upgrade and so on .restart but cann't solve

**Comment by zoechi** [comment]
The screenshot you posted still misses the indentation before `http: ...`
Add 2 spaces before `http: ...` and try again

**Comment by heinzan** [comment]
> The screenshot you posted still misses the indentation before `http: ...`
> Add 2 spaces before `http: ...` and try again

Oh God.Solved.You Saved my day bro.By the way i saw don't space before http: at another post.Thanks man.
