### ISSUE TITLE
Need to expose badCertificateCallback for IOClient/http.client

### ISSUE THREAD

**Issue by ayanb1992** [dart-lang/http#234]
Dart:io package gives us the badCertificateCallback. Need to include the same for http.Client by implementing the same in the IOClient class.

**Comment by tentone** [comment]
Also need this callback, i currently moving our API client codebase to dart.io cause of this.

**Comment by natebosch** [comment]
The way to get access to IO specific functionality is to construct an `HttpClient` from `dart:io` and then pass it to the constructor for `IOClient`.

**Comment by tentone** [comment]
Oh neat :) Thanks a lot!
