### ISSUE TITLE
SocketException: Reading from a closed socket

### ISSUE THREAD

**Issue by timtraversy** [dart-lang/http#236]
I am making a simple http request, and when I do, the program either throws the exception `SocketException: Reading from a closed socket`, or it just quietly hangs and never returns. Here is what my code looks like:
```
void main() async {
  const url = 'https://example.com';
  final client = http.Client();

  var i = 0;
  var count = 10;

  while (i < count) {
     final options = {...};
     final response = await client.post(url, body: options);
     // deal with response
     ++count
  }
  client.close();
}
```
And as I mentioned above, this hangs or throws:
```
Unhandled exception:
SocketException: Reading from a closed socket
#0      _RawSecureSocket.read (dart:io/secure_socket.dart:694:7)
#1      _Socket._onData (dart:io/runtime/binsocket_patch.dart:1720:27)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#6      _StreamController._add (dart:async/stream_controller.dart:639:7)
#7      _StreamController.add (dart:async/stream_controller.dart:585:5)
#8      _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1005:19)
#9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Oddly, this only seems to happen for certain URLs. Some URLs run perfectly every time, and then some cause it to hang. If it matters, I'm making POST requests to a online form.

**Comment by timtraversy** [comment]
Am I making requests too fast? The requests are in a while loop and I process the results almost immediately so it ends up making calls one after the other very fast.

Does the library discourage/prevent this? Should I add delays?

**Comment by timtraversy** [comment]
Might be related to this dropped call issue: https://github.com/dart-lang/sdk/issues/34477

**Comment by MrWaggel** [comment]
I don't know what URLs you are trying to post to but maybe some of them have anti spam methods on them, which instead of showing a soft error just closes the connection to you.

Also, I suggest you use the higher level [package http](https://pub.dartlang.org/packages/http) and not the dart:io.

`final response = await http.post(...)` Only succeeds if it got a response from the remote. So error handling with `response.statusCode` only works if you received a response from the server [see codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status).

The way to handle this is a try {}catch(){} block
```
try {
	final  response = await http.post(...);
	/// Your code, handle soft errors here (statusCodes)
 catch(error) {
	/// Handle 'hard' errors here, broken connections, connection refused, etc etc
}
```

There is also another way, but I haven't managed to get this working and that is by using the `Future<R> then<R>(FutureOr<R> onValue(T value), {Function onError});`

To the developers, I think that the [Cookbook: Fetch data from the internet](https://flutter.io/docs/cookbook/networking/fetch-data) should explain error handling better, and maybe abstract the exception handling inside the package itself.

**Comment by MrWaggel** [comment]
Okay I managed to make the other way work, which is prettier than a try catch block imo.

```dart
final post = client.post(url, body: options);
await get.then((response){
	if (response.statusCode == 200){
        	// Everything okay
	}else{
		// soft error, see status codes
      }
}, onError: (err){
	// Exception error, see err.toString();
});
```

By the way you can skip the `final client = http.Client();` and go straight to `final post = http.post(url, body: options);`

**Comment by timtraversy** [comment]
Yeah weird still hanging! I have the call wrapped in a try/catch already and it never throws an error, it just hangs and waits. I guess its just something about the URLs I'm trying to hit.

Also, isn't using a Client better if you are making many calls to the same server and want to keep the connection open?

**Comment by shrugs** [comment]
I receive this error intermittently when creating multiple `WebSocketChannel`. I have a factory function like

```dart
// ...
channelFactory: () => IOWebSocketChannel.connect(
    Config.instance.apiWsHostUrl,
    headers: {
    'Authorization': 'Bearer $token',
    },
),
// ...
```

Which is then opened and closed with functions like

```dart
  bool open() {
    if (isActive) {
      return false;
    }

    _monitor.start();
    _channel$.add(consumer.channelFactory())
    _state = ConnectionState.Open;

    return true;
  }

  bool close() {
    if (!this.isActive) {
      return false;
    }

    _monitor.stop();
    _channel$.value.sink.close(status.goingAway);
    _channel$.add(null);
    _state = ConnectionState.Closed;

    return true;
  }

```

And after calling `open()` and `close()` in succession we get the `SocketException: Reading from a closed socket` error from within the `WebSocket.connect` call

```
flutter: SocketException: Reading from a closed socket
flutter: dart:_http                                                         WebSocket.connect
flutter: package:web_socket_channel/io.dart 58:19                           new IOWebSocketChannel.connect
 .... from that factory function call and more ....
```

This only happens on the second `open` call: the state goes like `open() -> close() -> open()`

**Comment by kssujithcj** [comment]
@shrugs, Even we have a similar issue with our app. Have you got any lead or solution or workaround?

**Comment by shrugs** [comment]
@kssujithcj  can't remember making any progress on this, sorry

**Comment by JimmyHuang454** [comment]
> I receive this error intermittently when creating multiple `WebSocketChannel`. I have a factory function like
> 
> ```dart
> // ...
> channelFactory: () => IOWebSocketChannel.connect(
>     Config.instance.apiWsHostUrl,
>     headers: {
>     'Authorization': 'Bearer $token',
>     },
> ),
> // ...
> ```
> 
> Which is then opened and closed with functions like
> 
> ```dart
>   bool open() {
>     if (isActive) {
>       return false;
>     }
> 
>     _monitor.start();
>     _channel$.add(consumer.channelFactory())
>     _state = ConnectionState.Open;
> 
>     return true;
>   }
> 
>   bool close() {
>     if (!this.isActive) {
>       return false;
>     }
> 
>     _monitor.stop();
>     _channel$.value.sink.close(status.goingAway);
>     _channel$.add(null);
>     _state = ConnectionState.Closed;
> 
>     return true;
>   }
> ```
> 
> And after calling `open()` and `close()` in succession we get the `SocketException: Reading from a closed socket` error from within the `WebSocket.connect` call
> 
> ```
> flutter: SocketException: Reading from a closed socket
> flutter: dart:_http                                                         WebSocket.connect
> flutter: package:web_socket_channel/io.dart 58:19                           new IOWebSocketChannel.connect
>  .... from that factory function call and more ....
> ```
> 
> This only happens on the second `open` call: the state goes like `open() -> close() -> open()`

Same thing happens to me. Any update or clue about it?

**Comment by komaxx** [comment]
I know it's a stale thread - but this still happens a lot for our app.
Did anyone solve this or find a workaround?

**Comment by fullflash** [comment]
same here.

`SocketException: Reading from a closed socket
#0      _RawSecureSocket.read (dart:io/secure_socket.dart:779)
#1      _Socket._onData (dart:io-patch/socket_patch.dart:2446)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#8      _StreamController._add (dart:async/stream_controller.dart:658)
#9      _StreamController.add (dart:async/stream_controller.dart:606)
#10     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1116)
#11     _rootRun (dart:async/zone.dart:1391)
#12     _CustomZone.run (dart:async/zone.dart:1301)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#15     _rootRun (dart:async/zone.dart:1399)
#16     _CustomZone.run (dart:async/zone.dart:1301)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)`

**Comment by kashyap-5paisa** [comment]
Getting many such errors, need help.

**Comment by kashyap-5paisa** [comment]
Found the fix, if you are closing the connection with `channel?.sink.close()`, then make sure it is `await channel?.sink.close()`

**Comment by tanlocle0495** [comment]
@kashyap-5paisa  this issue was fixed right ?

**Comment by kashyap-5paisa** [comment]
@tanlocle0495 Yes, await channel?.sink.close() worked for me.
