### ISSUE TITLE
cannot get full data on (Await the http get response)

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/http#237]
I have problem getting full data using http plugin. In https://pub.dartlang.org/packages/http#-example-tab- I try to test it but print shows less data than when I paste https://www.googleapis.com/books/v1/volumes?q={http} into safari I get more data.

How can I get full data using "var url = "https:"?

```
  var url = "https://www.googleapis.com/books/v1/volumes?q={http}";

  // Await the http get response, then decode the json-formatted responce.
  var response = await http.get(url);
  if (response.statusCode == 200) {
    var jsonResponse = convert.jsonDecode(response.body);
    var itemCount = jsonResponse['totalItems'];
    print("===================================================");
    print("===================================================");
    print("Number of books about http: $itemCount.");
    print("---------------------------------------------------");
    print("jsonResponse: $jsonResponse");
  } else {
    print("Request failed with status: ${response.statusCode}.");
  }
```

**Comment by natebosch** [comment]
If you aren't getting a json decode failure you are almost certainly are getting all the data sent. If it was cut off I'd expect a missing close bracket or similar in the json decode.

I also get the same result in chrome as I get when I run your example.

Please add a specific reproduction case if this is still an issue for you.
