### ISSUE TITLE
Format Arrays in Body

### ISSUE THREAD

**Issue by ibrokemypie** [dart-lang/http#238]
Sometimes it is necessary to post arrays formatted as arrayname[]value&
eg foo[1,2,3] becomes  foo[]=1&foo[]2&foo[]3
I cant seem to find any way this would be possible with dart http though.

**Comment by natebosch** [comment]
This seems like a detail of the endpoint you are hitting and not a general enough thing for all users of `package:http` to want it. You should be able to perform this transformation in your code before calling in to the http library.
