### ISSUE TITLE
No error when internet offline

### ISSUE THREAD

**Issue by mctrivia** [dart-lang/http#253]
If I turn the internet off before I make a request it does not throw an error or return an error response code.  Just hangs.

**Comment by natebosch** [comment]
Does the behavior differ from if you use `HttpClient` from `dart:io` directly? I doubt this package can solve that problem...

**Comment by ozenati** [comment]
Hello, Did you find a solution for this issue? With android I was able to schedule a post request when internet is available.

**Comment by natebosch** [comment]
Closing since this issue is not actionable.
