### ISSUE TITLE
Documentation Update Needed

### ISSUE THREAD

**Issue by jeffmikels** [dart-lang/http#258]
When building an app in release mode, the INTERNET permission needs to be added to the AndroidManifest.xml under `android/app/src/main/`

It already exists in `android/app/src/`, but it also needs to go in the main manifest.

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by natebosch** [comment]
This sounds like something that should happen in the flutter docs. Nothing in this package is specific to flutter/android and it's possible to hit a problem with using an http client from `dart:io` without using this package.

**Comment by jeffmikels** [comment]
Actually, the `flutter create` command gives internet permission for development, but then removes that permission for release mode because default flutter apps don't need that permission for development.

It would be a simple thing to add one line in the README.md that recognizes this.
