### ISSUE TITLE
Custom User-Agent lost after redirect

### ISSUE THREAD

**Issue by dolphinxx** [dart-lang/http#268]
I use custom User-Agent to pass app version/distribution info to the server, and encountered an issue today.
The User-Agent configured in request headers will become the default one(ie: `Dart/2.2 (dart:io)`) after redirect.
Here is a [reproduce gist](https://gist.github.com/dolphinxx/aeb312dada9134110a8b2b41f6e811d0)

**Comment by dolphinxx** [comment]
I resolved it by setting default userAgent through `HttpClient.userAgent`, if it's not a bug, please close it.

**Comment by kevmoo** [comment]
I think this is by design.
