### ISSUE TITLE
Listen to redirect

### ISSUE THREAD

**Issue by ykrank** [dart-lang/http#271]
When i download image from server, i want followRedirects, but throw exception on some unique redirects url.  How could i intercept every redirect? Like Interceptor and NetworkInterceptor in okhttp.

**Comment by jonasfj** [comment]
You probably can't do that with this package... it abstracts XHR in the browser and `dart:io` on the client... and as far as I'm aware XHR can't detect redirects...

I might be doable in the browser using `fetch`, if the browser supports fetch.

If you're on flutter I would suggest using: https://api.dartlang.org/stable/2.2.0/dart-io/HttpClient-class.html
