### ISSUE TITLE
Unable to process .bin file from the server

### ISSUE THREAD

**Issue by GauravPatni** [dart-lang/http#273]
Dear all,

In my flutter app, I am fetching .bin file which is a purely binary file from Amazon S3 bucket.

but not able to process request.body because it is in (_OneByteString) format. When tried to save in List<int>, it throws an exception.

Please let us know how to handle .bin files data from flutter HTTP package.

refer attached sample test.bin file ( please change extension from .txt to .bin )

[test .txt](https://github.com/dart-lang/http/files/3144278/test.txt)

please refer following decimal representation of a test.bin file

0, 8, 0, 32, 185, 85, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 17, 92, 0, 0, 153, 56, 2, 0, 5, 86, 0, 0, 21, 52, 2, 0, 5, 57, 2, 0, 165, 56, 2, 0, 189, 56, 2, 0, 157, 56, 2, 0, 5, 86, 0, 0, 125, 88, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 165, 88, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 5, 86, 0, 0, 133, 69, 0, 0, 9, 57, 2, 0, 161, 56, 2, 0, 5, 86, 0, 0, 73, 57, 2, 0, 101, 69, 0, 0, 149, 244, 1, 0, 5, 86, 0, 0, 19, 183, 121, 250, 201, 37, 221, 183, 173, 243, 207, 224, 241, 182, 20, 184, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 66, 0, 0, 34, 0,....

Thanks,
Gaurav

**Comment by jonasfj** [comment]
For future reference it's useful to post a minimal code sample...

Guessing that you might have used `Response.body` instead of `Response.bodyBytes`, see:
https://pub.dartlang.org/documentation/http/latest/http/Response/bodyBytes.html

Please, reopen if that's not the problem here... (if you have a suggestion for how we could improve documentation to better explain this, please feel free to file a PR).
