### ISSUE TITLE
how set ssl in dart

### ISSUE THREAD

**Issue by mehdidavarpanah66** [dart-lang/http#279]

**Comment by mehdidavarpanah66** [comment]
i need know how request to https in dart

**Comment by jonasfj** [comment]
I don't follow... please elaborate the question.

I think you just use an https URL, like `await http.get('https://example.com');`

**Comment by mehdidavarpanah66** [comment]
> I don't follow... please elaborate the question.
> 
> I think you just use an https URL, like `await http.get('https://example.com');`

hi.yes.
i have problem for request to https in java but i dont test in dart.so
 i think this is dsfcult .i am looking for a example

**Comment by jonasfj** [comment]
An example of what?

How to make an HTTPS request in Dart or how to make one from Java (I assume a flutter plugin)?

This package concerns it's self with Dart, and is not flutter specific.

----
Side note: There is this community package, I haven't tried it myself, but it has a lot of examples: https://pub.dev/packages/dio

**Comment by mehdidavarpanah66** [comment]
> Side note: There is this community package, I haven't tried it myself, but it has a lot of examples:

a example of config ssl on dart

**Comment by jonasfj** [comment]
Are you looking to run an HTTPS server? or making a request?

HTTPS server is done with `dart:io`:
https://api.dartlang.org/stable/2.3.1/dart-io/HttpServer-class.html

There is even an example there...


----
Note: if running a public HTTPS server, you might be better off using a reverse proxy and terminate TLS at your load balancer. This is what Google Cloud Run does...

**Comment by mehdidavarpanah66** [comment]
> Are you looking to run an HTTPS server? or making a request?
> 
> HTTPS server is done with `dart:io`:
> https://api.dartlang.org/stable/2.3.1/dart-io/HttpServer-class.html
> 
> There is even an example there...
> 
> Note: if running a public HTTPS server, you might be better off using a reverse proxy and terminate TLS at your load balancer. This is what Google Cloud Run does...

i want request to a https server in android

**Comment by jonasfj** [comment]
You want to do what?

I don't understand the setup? Are you client or server?

**Comment by mehdidavarpanah66** [comment]
client
i am android developer and i have request in android app to https server

**Comment by jonasfj** [comment]
Okay, from a client perspective there is no difference between http and https. You just make a request to the server.

**Comment by mehdidavarpanah66** [comment]
it dont necessery to ssl setting in flutter

**Comment by jonasfj** [comment]
I'm sorry, I don't understand the question.

Have you looked at: https://flutter.dev/docs/cookbook/networking/fetch-data
