### ISSUE TITLE
There should be a library like this for WebSockets

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/http#28]
I know this is not exactly the right place to request this feature, but it's a general Dart one that best related to this package.

WebSockets in Dart are hell. There is no unified interface for VM and Browser and it makes it impossible to create packages that work on top of WebSockets (which are platform-agnostic for the remainder of the package).

A library like this that provides a unified interface for both is really great and I think having one for WebSockets (package:websockets f.e.) would be very useful.

**Comment by nex3** [comment]
For future reference, the [mailing list](https://groups.google.com/a/dartlang.org/forum/#!forum/misc) a better place for discussions like this.

The `http_parser` package [actually does provide a cross-platform interface for web sockets](http://www.dartdocs.org/documentation/http_parser/0.0.2%2B6/index.html#http_parser/http_parser.CompatibleWebSocket), although there's not a great way to convert a client-side socket into that interface.

If you think a library that builds on that to create something usable on both client and server would be useful, by all means write one!
