### ISSUE TITLE
Consider using a global default HttpClient

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/http#281]
When making a HTTP request, why not use a global `HttpClient` by default?

It's quite common that I just want to make an HTTP request, and I don't want to manage a connection pool. In fact I would be quite happy to have many libraries in my application use the same connection pool. So why not have a default HTTP connection pool?

(this is what you have in node.js, and if running in the browser you also have it, as the browser manages connections for you).

**Comment by cskau-g** [comment]
At a glance, because globals are, generally, considered an anti-pattern?

When you, as the user, are making a request, are you not just using the top-level functions as shown in the README?
What connections are you managing in that case?

**Comment by jonasfj** [comment]
> What connections are you managing in that case?

You're not managing connection, which means you're not reusing connections, and that is a problem.

If you make a lot of requests this way you'll run out of ports. It's also slow and energy demanding to always be creating new connections.

The node.js equivalent of HttpClient is [http.agent](https://nodejs.org/api/http.html#http_class_http_agent) it has a [global instance](https://nodejs.org/api/http.html#http_http_globalagent). In golang the equivalent to `HttpClient` is [http.Client](https://golang.org/pkg/net/http/#Client) again it has a global [http.DefaultClient](https://golang.org/pkg/net/http/#pkg-variables) which is used by the top-level [`http.Get` function](https://golang.org/pkg/net/http/#Get).

This is actually rather important, unless your library is making a lot of HTTP requests, you're better off sharing the connection pool with other libraries in the same application. If the libraries talk to the same server they'll be able to reuse connections, which is good for battery, latency, performance and avoiding running out of ports.

We'd likely want to set [maxConnectionsPerHost](https://api.dartlang.org/stable/2.3.1/dart-io/HttpClient/maxConnectionsPerHost.html) to some reasonable limit and have [idleTimeout](https://api.dartlang.org/stable/2.3.1/dart-io/HttpClient/idleTimeout.html) set to 15s or so..

The only hard part is that such a global pool should be closed gracefully when the program terminates, as to avoid keeping the event-loop going. Maybe such a thing should live in `dart:io` (cc/ @sortie).

**Comment by cskau-g** [comment]
From our offline talk I gather this issue isn't motivated by any particular need or practical case, rather it's a theoretical, potential optimisation.

But to summarise our discussion, and as the README explains, users already have the option of using the convenience functions, or alternatively if they're doing something heavier they should manage their own clients.

If you have a practical issue where this API does not work or is actually causing ports to be exhausted, feel free to re-open with a proposal how to fix that issue.
