### ISSUE TITLE
Flutter Web compilation error: File not found

### ISSUE THREAD

**Issue by rostopira** [dart-lang/http#288]
I've tried to build project that uses this package on master
It throws an error
```
$ flutter run -d chrome
Downloading Web SDK...                                              1.6s


Error compiling dartdevc module:http|lib/http.ddc.js

packages/http/src/multipart_file.dart:14:8: Error: Error when reading 'packages/http/src/multipart_file_stub.dart': File not found
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7: Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^


Failed after 24.7s
Failed to compile for the web.
```
Flutter doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.1-pre.58, on Mac OS X 10.14.4 18E226, locale en-BY)
```

**Comment by cskau-g** [comment]
Can you provide us with a `pubspec.yaml` and import statements to reproduce this issue?

**Comment by rostopira** [comment]
@cskau-g Sure, here it is:
```yaml
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk:
    git:
      url: https://github.com/phillwiggins/flutter_parse_sdk.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by natebosch** [comment]
@jonahwilliams - does `flutter run -d chrome` use DDK? Is there something strange going on with module crawling?

**Comment by jonahwilliams** [comment]
yes, we're using DDK. The module crawling might very well be broken though

**Comment by rostopira** [comment]
Should we close this in favor of https://github.com/flutter/flutter/issues/34858 ?
According to your comments, it's not package issue

**Comment by jonahwilliams** [comment]
It's likely the case that my inclusion of `dart:io` in the supported libraries is tripping up the feature detection. I'll need to do some experimentation to see if I can only partially disable it

**Comment by jakemac53** [comment]
We likely just need to pass the `--libraries-file` directly. It will need to agree with whatever we put in the Platform for the module builder.

**Comment by giandifra** [comment]
see [this](https://github.com/dart-lang/http/pull/286)

**Comment by GregorySech** [comment]
Just to clarify which is the issue to track? This or https://github.com/flutter/flutter/issues/34858 (which needs to be re-opened)?

**Comment by rostopira** [comment]
@GregorySech I'm pretty sure, 34858 should be reopened and this one closed

**Comment by jonahwilliams** [comment]
Reopened

**Comment by rostopira** [comment]
@jonahwilliams Thank you! Closing this issue
