### ISSUE TITLE
wrong http method on http.get or http.post with headers on flutter web

### ISSUE THREAD

**Issue by ekasetiawans** [dart-lang/http#289]
When I try consumes rest api using http.get or post with headers, the request http method changed to OPTIONS instead of GET or POST. But, it's working normally when headers is set to NULL value.

**Comment by ekasetiawans** [comment]
Solved, I forget to set Access-Control-Allow-Headers on RestApi.

**Comment by ShurikuS57** [comment]
What exactly did you do? @ekasetiawans

**Comment by ekasetiawans** [comment]
> What exactly did you do? @ekasetiawans

I access my own rest api from my flutter web application, and the response from server is not as I expected. But, if I tried run as android application, it's working perfectly. Now, I know the problem is from my rest api, not from this library. I forgot to allow CORS, which is required by browser.
