### ISSUE TITLE
http dont load last object

### ISSUE THREAD

**Issue by mehdidavarpanah66** [dart-lang/http#291]
**********************************************************
**This is not the repository you want to file issues in!**
**********************************************************

Note that a failing HTTP connection is almost certainly not caused by a bug in
package:http.

This package is a wrapper around the HttpClient from dart:io and HttpRequest
from dart:html. Before filing a bug here verify that the issue is not surfaced
when using those interfaces directly.

https://api.dartlang.org/stable/dart-io/HttpClient-class.html
https://api.dartlang.org/stable/dart-html/HttpRequest-class.html

# Common problems:

- A security policy prevents the connection.
- Running in an emulator that does not have outside internet access.
- Using Android and not requesting internet access in the manifest.
  https://github.com/flutter/flutter/issues/29688

None of these problems are influenced by the code in this repo.

# Diagnosing:

- Attempt the request outside of Dart, for instance in a browser or with `curl`.
- Attempt the request with the dart:io or dart:html equivalent code paths.

**Comment by mehdidavarpanah66** [comment]
Does http have a cache?
becuse when load a list of data with http get method and i dont get last object  While showing it in postman

**Comment by natebosch** [comment]
Nothing in this package should be doing any caching, if you're not seeing subsequent requests that is likely coming from somewhere else. Can you provide a repro?

Note that if you're re-using the same `Future` instance then it is "cached" - a `Future` is a handle on a value that may come later - it isn't a handle on a body of work that can be repeated.

**Comment by mehdidavarpanah66** [comment]
in my app i have to webservice with names: addOrder & loadOrders;
first i addOrder in server and i call loadOrder 
but dont see last order
when i test loadorder in postman i can see last order

**Comment by natebosch** [comment]
Sounds like you may have a race condition or something - unfortunately we won't be able to help much with something specific to your server.

A likely mistake is not awaiting the completion of the `addOrder` request.

You can learn more about `Future` in Dart here: https://dart.dev/tutorials/language/futures

You'll want to be sure that the `loadOrder` request doesn't start until the `addOrder` request is done. Also ensure that you don't have caching somewhere else in the system. Nothing in the Dart SDK or this package will be introducing caching.

If you can create a minimal repro that demonstrates a bug in this package we can re-open and investigate.
