### ISSUE TITLE
Http request is failing on Android 9, but works on earlier versions on android 

### ISSUE THREAD

**Issue by RobertApikyan** [dart-lang/http#292]
I'm trying to make http request on android 9, but it fails, stack trace is below. For other versions of android it works fine, the issue is only related with android 9, I have also tried to add         android:usesCleartextTraffic="true" attribute to android manifest, but it doesn't help. 

Stacktrace
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'auth.raiser-pre.local' (OS Error: No address associated with hostname, errno = 7)
    #0      IOClient.send (package:http/src/io_client.dart:33:23)
    <asynchronous suspension>
    #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
    <asynchronous suspension>
    #2      BaseClient.get (package:http/src/base_client.dart:32:7)
    #3      get.<anonymous closure> (package:http/http.dart:46:36)
    #4      _withClient (package:http/http.dart:166:20)
    <asynchronous suspension>
    #5      get (package:http/http.dart:46:5)
```

**Comment by natebosch** [comment]
This isn't something that would be caused by this package. The problem is potentially with the Dart SDK but that sounds unlikely.

Can you file an issue in the flutter repo asking for help with this? The authors of this package don't have expertise with flutter or android.

I have https://github.com/flutter/flutter/issues/29688 open asking for improved documentation around this.

**Comment by fpv999** [comment]
From stackoverflow:

Set a networkSecurityConfig in your Manifest application tag like this:

<?xml version="1.0" encoding="utf-8"?>
<manifest ... >
    <application android:networkSecurityConfig="@xml/network_security_config">




    </application>
</manifest>

Then in your xml folder you now have to create a file named network_security_config just like the way you have named it in the Manifest and from there the content of your file should be like this to enable all requests without encryptions:

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
