### ISSUE TITLE
MediaType compile error

### ISSUE THREAD

**Issue by duzenko** [dart-lang/http#296]
I am trying to instantiate an object of type MultipartFile and stuck with a compile error
```
import 'package:http/http.dart';
...
    MultipartFile.fromPath('files', '', contentType: MediaType('image', ''));
```
=>
`error: The method 'MediaType' isn't defined for the class '_MyHomePageState'. (undefined_method at [flutter_app1] lib\main.dart:54)`

Do I need to manually add import of some package? Shouldn't it automatically offer me the right import with Alt-Enter in Android Studio?

**Comment by natebosch** [comment]
It looks like you need to add a dependency and import to `http_parser`

https://pub.dev/documentation/http_parser/latest/http_parser/MediaType-class.html

> Shouldn't it automatically offer me the right import with Alt-Enter in Android Studio?

I'm not sure, the analyzer might not suggest imports for packages that you don't depend on already. You could consider filing an issue in the SDK repo for the analyzer team to weigh in.

**Comment by ljh1234** [comment]
is the problem solution? I have the same  question like that

**Comment by dayananronel** [comment]
> 

You'll need to import http_parser manually if you have added it on the dependency already.
