### ISSUE TITLE
http.get hang no response with webdev

### ISSUE THREAD

**Issue by LensionWu** [dart-lang/http#297]
enviroment:
macos 10.14.6
dart 2.4.0
http 0.12.0+2
code:
  _handleSubmitted(int flag) async {
    print('Submitted');
    var url = "https://www.sogo.com";
    var response = await http.get(url);  // hang here
    print('Response status: ${response.statusCode}');  // no print
    print('end submit');  // no print
  }

**Comment by natebosch** [comment]
It's possible that the problem is the body of the response never completes. See https://github.com/dart-lang/http/issues/270#issuecomment-539226402

**Comment by natebosch** [comment]
Hmm, I'm not able to repro this with `"https://www.sogo.com"`. Is this still happening for you?

**Comment by rohanthewiz** [comment]
I am having the same issue on flutter for web. `http.get` hangs. 
`dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
`

`import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isLoading = false;

  void _fetchData() async {
    setState(() {
      _isLoading = true;
    });

    print('Trying to get woot.com...');
    var response = await http.get('https://woot.com'); //http://gonotes.net:9080/api/v1/l/15
    if (response.statusCode == 200) {
      setState(() {
        _isLoading = false;
      });
      print("Response: $response");
    } else {
      throw Exception('Failed to load data');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '${_isLoading ? "Loading" : "Loaded"}',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _fetchData,
        tooltip: 'Get Data',
        child: Icon(Icons.cloud_download),
      ),
    );
  }
}
`
`flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.4 18E227, locale en-US)
    • Flutter version 1.12.13+hotfix.6 at /Users/rallison3/apps/flutter
    • Framework revision 18cd7a3601 (2 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rallison3/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.`

**Comment by rohanthewiz** [comment]
I finally figured it out! Tried this public API and it worked (albeit a little slow): https://vpic.nhtsa.dot.gov/api/vehicles/getallmakes?format=json. Apparently in flutter for web things are stricter than in the mobile as I did not have a problem with the above gonotes.net (mine) API. I need to open up the CORS there apparently.
