### ISSUE TITLE
不知道中文能不能看懂，当后台关上后，http 直接内部错误，连不到后台，除了用try.catch捕获，关键点是直接报错了,并不会出现错误码让你去判断

### ISSUE THREAD

**Issue by doudouaixiaoyu** [dart-lang/http#298]
Exception has occurred.
SocketException (SocketException: OS Error: Connection refused, errno = 111, address = 192.168.1.101, port = 60000)

**Comment by doudouaixiaoyu** [comment]
我的建议是当后台关上后，或者这个url 并不存在，可以返回response为null,而不是直接报错让我去捕获

**Comment by natebosch** [comment]
+1 for needing an example.

From what I understand, you are asking that we return `null` instead of throwing for things like refused connections? If so, that isn't a change we're likely to make, it would not be idiomatic to take that approach in Dart.
