### ISSUE TITLE
Receiving part of ongoing MP3 stream?

### ISSUE THREAD

**Issue by jkleiser** [dart-lang/http#30]
Can this library be used for receiving part of an ongoing MP3 stream, e.g. two minutes?

**Comment by nex3** [comment]
[`StreamedResponse.stream`](http://www.dartdocs.org/documentation/http/0.11.3%2B2/index.html#http/http.StreamedResponse@id_stream) provides access to a low-level byte stream view of the request that should allow you to do this.
