### ISSUE TITLE
http and socks5 proxy

### ISSUE THREAD

**Issue by unifyproxy** [dart-lang/http#301]
Request can go through proxy

maybe something like this

```dart
http.get(String url, {String proxy, ...});
```

**Comment by wuujiann** [comment]
I would also like to see SOCKS5 proxy support added to http (http.findProxy).
Currently, findProxy() only supports proxy of the format: "PROXY proxyhost:port"
Maybe format can be changed to: "PROXY [protocol://][user:password@]proxyhost[:port]>", where
protocol can be http, https or socks5.

**Comment by lichao3389** [comment]
the idea is good.

**Comment by natebosch** [comment]
I don't think there is any way to support this on the web, and `package:http` is intended to be cross platform. Please use the SDK provided class from `dart:io` to accomplish this.

**Comment by liudonghua123** [comment]
Maybe it can add this functionality in https://api.dart.dev/stable/2.9.3/dart-io/HttpClient/findProxyFromEnvironment.html.
