### ISSUE TITLE
Support flutter web release build

### ISSUE THREAD

**Issue by jaumard** [dart-lang/http#303]
I'm using a library that is using this package under the hood, once I'm trying to run `flutter build web --release` I'm getting this error:

```
Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

```

Is it a known issue ? Is there any workaround ? 

Thanks :)

**Comment by jaumard** [comment]
Thanks @natebosch ! From the discussion you mention I can also read that :
> Are you using a mutlipart request object directly? These aren't supported in on the web version of package:http

So I'm guessing that is not full on Flutter side right ? There is still work to do on this package around multipart requests ?

**Comment by natebosch** [comment]
> I'm guessing that is not full on Flutter side right ?

The specific failure is fully Flutter side: `(No such file or directory)` when building.

> There is still work to do on this package around multipart requests ?

I don't _think_ so... The `MulitPartRequest.fromPath` method will never work on the web, but we are using platform specific imports so I don't see any reason other stuff wouldn't work.
