### ISSUE TITLE
SocketException: OS Error: Operation timed out on IOS but not on Android

### ISSUE THREAD

**Issue by yshahak** [dart-lang/http#324]
I running this peace of code:
```dart
var url = 'http://10.0.2.2:8888/login';
var response = await http.post(url, headers: {"Content-Type": "application/json"}, body: json.encode({"user": 'testUser', "password": 'testPassword'}));
```
This running just fine on `Android` but when running on `ios` simulator/real device, I facing this error:
```
flutter: error: SocketException: OS Error: Operation timed out, errno = 60, address = 10.0.2.2, port = 60861
```

**Comment by yshahak** [comment]
Ok, My bad. `http://10.0.2.2:8888` is used by Android for localhost. This is not the right address for ios.

**Comment by natebosch** [comment]
This might be another thing to request that the flutter team documents.

https://github.com/flutter/flutter/issues/29688

**Comment by MohamedSamirEdris** [comment]
what is the right uri for ios

**Comment by webBlaster** [comment]
just 'localhost'
