### ISSUE TITLE
HTTP request Auth Error

### ISSUE THREAD

**Issue by elamir611** [dart-lang/http#330]
Hello Everyone
I have an internal website that uses login page then summary page

when i put the login page in the http.get it return 200 authentication succeeded but it doesn't retrieve any information

when i put the link for the summary page (that have the information i need) in the http.get authentication fail and return 401

i use basic Authentication

do you have any advice ?

Future getCPUData() async{
    var client = http.Client();
    String username = 'xxx';
    String password = 'xxx';
    String basicAuth = ('$username:$password');
    print(basicAuth);

    http.Response sAppLoginURL = await http.get(
        'http://1.1.1.1/app/Login.aspx?autologin=no',
        headers: <String, String>{'authorization': basicAuth});
    print(sAppLoginURL.statusCode);
    print(sAppLoginURL.body);
    var document = parse(sAppLoginURL.body);
    List<html.Element> links = document.querySelectorAll('td.Proprety > a.hostname');

    List<Map<String, dynamic>> linkMap = [];
    for (var link in links) {
      linkMap.add({
        'Proprety': link.text,
        'hostname': link.attributes['hostname'],
      });
      print(linkMap);
      print(links);
      return json.encode(linkMap);
    }
  }
it print 200 when i use the login page but i get nothing from it
----------------------------------------------------

when i change the link to the page i want to get the data from
http://1.1.1.1/app/SummaryView.aspx?ViewID=1

it gives me auth faild 401

**Comment by elamir611** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by mohanmonu777** [comment]
Try testing the API with other front end tech.
If the same error happens in other front end tech, that may be problem with the API You are using.
Have you tried to test your API using Post Man?

**Comment by MrVipinVijayan** [comment]
I am trying to do a post request in Flutter

Below is the code

final String url = Urls.HOME_URL;
  String p = 'Bearer $vAuthToken';

  final Map<String, String> tokenData = {
    "Content-Type": "application/x-www-form-urlencoded",
    'Vauthtoken': p
  };

  final Map<String, String> data = {
    'classId': '4',
    'studentId': '5'
  };

  final response = await http.post(Uri.parse(url),
      headers: tokenData,
      body: jsonEncode(data),
      encoding: Encoding.getByName("utf-8"));

  if (response.statusCode == 200) {
    print(response.body);
  } else {
    print(response.body);
  }
However the header data is not working. I have the correct data and everything. This request works perfectly when done in Postman Client. Any one has any idea what is wrong? Any suggestion is appreciated.

**Comment by natebosch** [comment]
This issue is not actionable.

If someone is still facing this problem please post a _specific_ difference between the behavior you see when using `package:http` and the behavior you expect.
