### ISSUE TITLE
Raw Body on Method Get

### ISSUE THREAD

**Issue by ariefsn** [dart-lang/http#339]
hi, i need to include some payload(body raw) on method get.
any example of that?
one more question, how to send body payload as Map<String, Object> instead of Map<String, String> ??
i've got an error
Map<String, Object>' is not a subtype of type 'String'

**Comment by YourJayer** [comment]
This will probably not be implemented. See this discussion about a body on `DELETE` https://github.com/dart-lang/http/issues/206#issuecomment-434265328 for reference.

However you can use a workaround with `Client.send` like this:
```dart
final body = "SUPER AWESOME BODY";
final req = Request("GET", uri)
  ..body = body;

final resp = await client.send(req);
```

**Comment by natebosch** [comment]
> how to send body payload as Map<String, Object> instead of Map<String, String> ??

Convert the values to Strings. That may be with `.toString()` or `jsonEncode` or some other approach, so we can't make the choice for you in this library. To use `.toString()` to convert to strings use `body.map((name, value) => MapEntry(name, '$value')`
