### ISSUE TITLE
There has to be some way to handle REFUSED connection

### ISSUE THREAD

**Issue by insinfo** [dart-lang/http#340]
I am using the http 0.12.0 package in an AngularDart project, and I need a way to handle the error "REFUSED Connection" and "ERR_NAME_NOT_RESOLVED" to display a more user friendly message. Is it possible to do this somehow with the http package?

Maybe it would be nice if instead of throwing an exception, returning a status code -1 or -3

I'm currently wrapping it up with a try catch

![image](https://user-images.githubusercontent.com/12227024/68143877-2746f780-ff11-11e9-8a20-5f789765ac84.png)

![image](https://user-images.githubusercontent.com/12227024/68142839-f5cd2c80-ff0e-11e9-851f-d0821f06a378.png)

![image](https://user-images.githubusercontent.com/12227024/68142825-ee0d8800-ff0e-11e9-9714-52b63df6b110.png)

**Comment by natebosch** [comment]
Wrapping with a `try/catch` is the expected solution. We do not plan on turning network exceptions into synthetic responses with faked status codes.
