### ISSUE TITLE
The request was rejected because no multipart boundary was found

### ISSUE THREAD

**Issue by phungtienthanh** [dart-lang/http#355]
**The request was rejected because no multipart boundary was found**
```
 Future<StreamedResponse> uploadImage(File file) async {
    String _url = URLConstant.baseURL + this.url;
    final headers = Map<String, String>();
    headers[Constant.contentType] = 'multipart/form-data';
    headers[Constant.headerAPI] = prefs.getString(Constant.token).toString();
    var uri = Uri.parse(_url);
    var stream = ByteStream(DelegatingStream.typed(file.openRead()));
    var length = await file.length();
    var request = MultipartRequest("POST", uri);
    String fileType = file.path.substring(file.path.lastIndexOf('.')+1,file.path.length);
    var multipartFile = MultipartFile(
      'file',
      stream,
      length,
      filename: basename(file.path),
      contentType: MediaType('application',fileType),
    );
    request.files.add(multipartFile);
    request.headers.addAll(headers);
    print('Header' + request.headers.toString());
    var response = await request.send();
    print(response.statusCode);
    return response;
  }
```
**Env**
-  Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-VN)
-  Flutter version 1.12.13+hotfix.5 
-  Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
-  Engine revision 2994f7e1e6
-  Dart version 2.7.0
-  Http: 0.12.0+3

**Comment by natebosch** [comment]
What is the value of `Constant.contentType`? Can you try not setting that header? It is already set by the request. I would expect this to be overridden automatically, but that might work if the key you are using has different capitalization or something.

https://github.com/dart-lang/http/blob/01b325bb815a375fa67134ac5d9846e8b257b5eb/lib/src/multipart_request.dart#L95

**Comment by phungtienthanh** [comment]
The value of Constant.contentType is 'Content-Type'. Previously I used version 0.11.3 + 17 is still normal. But when upgrading to version 0.12.0 + 3, the above error appears.

**Comment by natebosch** [comment]
I confirmed that we had a regression here. Tracking at https://github.com/dart-lang/http/issues/351

I'll close this one as a duplicate. In the mead time, it still won't be a good idea to set your own content type header.
