### ISSUE TITLE
How can I change content-type with a POST request?

### ISSUE THREAD

**Issue by maveroid** [dart-lang/http#357]

**Comment by maveroid** [comment]
I created a custom api backend...
But I'm getting "TypeError: 'NoneType' object is not subscriptable"
So I'm looking for a way to change the request body to application/json

**Comment by natebosch** [comment]
The `post` and `client.post` methods have a `headers` named argument. If you pass `{'content-type': 'application/json'}` to that argument it will be used for the request.

**Comment by maveroid** [comment]
Ohhhhh... Thanks 😊

**Comment by elcolie** [comment]
@natebosch 
http: ^0.12.2

```dart
    const apiTokenAuth = PROD_URL + '/api-token-auth/';
    const headers = {"content-type": "application/json"};
    var body = {
      "username": data.name,
      "password": data.password,
    };
    var res = await http.post(apiTokenAuth, headers: headers, body: body);
```
I got error
```bash
E/flutter ( 6833): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: Cannot set the body fields of a Request with content-type "application/json".
```
Where am I wrong?

**Comment by elcolie** [comment]
Found the [answer](https://stackoverflow.com/questions/27574740/http-post-request-with-json-content-type-in-dartio)
