### ISSUE TITLE
http.head() can return empty unhandled exception

### ISSUE THREAD

**Issue by davenotik** [dart-lang/http#36]
```
var response = await http.head('http://v.youku.com/v_show/id_XOTUwODY0NDky.html').catchError(print);
        print(response);
```

The error is empty. Remove the `catchError` and it reports as `Unhandled Exception:  `.

**Comment by davenotik** [comment]
That's the line: https://github.com/dart-lang/http/blob/8ecdfac7efb66f3297a60e96069336361fcf99bf/lib/src/io_client.dart#L76

**Comment by nex3** [comment]
It looks like the error message will only be empty if an empty error is coming from `dart:io`. That sounds like a `dart:io` bug.
