### ISSUE TITLE
Default encoding for Content-Type application/json should be UTF-8

### ISSUE THREAD

**Issue by svendroid** [dart-lang/http#367]
**Current State:**
When getting a Response with `Content-Type application/json` the library defaults to using latin1 as encoding because the `charset` param is not set in the `Content-Type`-Header.
See docs Response#body method:
```
  /// The body of the response as a string.
  ///
  /// This is converted from [bodyBytes] using the `charset` parameter of the
  /// `Content-Type` header field, if available. If it's unavailable or if the
  /// encoding name is unknown, [latin1] is used by default, as per
  /// [RFC 2616][].
  ///
  /// [RFC 2616]: http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html
```

**Expectation**
I would expect that the default encoding for `application/json` media types to be UTF-8.
```
The MIME media type for JSON text is application/json. 
The default encoding is UTF-8. 
(Source: RFC 4627).
```
see https://stackoverflow.com/a/477819/702478

In general the media type specified is not taken into account when determining the encoding for the body of a response, when the `charset` parameter is not set.

**Comment by wanjm** [comment]
is there any one take care of this ?

as rfc says the default should be utf-8;

**Comment by aoisensi** [comment]
+1 please

**Comment by proshin-roman** [comment]
this issue is really ridiculous: I develop apps for both sides - a flutter app and also a backend on Spring Boot (java), and Spring doesn't recommend anymore to define the encoding in the `Content-Type` header and marks it as deprecated.

**Comment by proshin-roman** [comment]
btw: there is another ticket related to this issue https://github.com/dart-lang/http/issues/455

**Comment by DeD1rk** [comment]
For more context see [this comment](https://github.com/dart-lang/http/issues/175#issuecomment-619593544). TLDR: utf-8 encoding in json is mandatory, not only default.

**Comment by natebosch** [comment]
Closing in favor of #174

The expected pattern to use today when you know the result is json is `jsonDecode(utf8.decode(response.bodyBytes))`. We should consider changing the default decoding so that fewer users get confused by this.
