### ISSUE TITLE
Issue with http library on Firefox, works on Chrome

### ISSUE THREAD

**Issue by jlee-aura** [dart-lang/http#370]
Issue Error for http library on Firefox, works on Chrome

`import` 'package:http/http.dart' as http;`

http.get("some random url");

flutter --version

`Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (3 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0`

pubspec.yml

`http: any`

I've run flutter doctor, upgrade and updated the packages.

http.get() runs correctly in chrome, however in firefox it fails. The only error messages is:

`Error:    dart_sdk.js:5308:7`

**Comment by diegolaballos** [comment]
Same problem here, did you find a solution?

**Comment by natebosch** [comment]
Is there anything that shows up in the network tab of the browser developer tools?
