### ISSUE TITLE
Is it possible to get the html after JavaScript content of the page gets loaded.

### ISSUE THREAD

**Issue by janhrastnik** [dart-lang/http#371]
My problem is that using http.read returns only the base html file, but I need to wait for the JavaScript of the site to run so that I can get the additional generated html content. Is there any way to do this with this library?

**Comment by natebosch** [comment]
Are you asking for a library that would act like a browser? No, this is only for making http request, not for parsing and acting on html files after they are downloaded. You might be able to use https://pub.dev/packages/html to parse the content and look for the scrip tags to download, but there is no javascript engine to evaluate it. You might be able to put something together with some javascript engine, but it would be quite complex and well outside the scope of this package.
