### ISSUE TITLE
Works totally fine with the mobile but gives error on web

### ISSUE THREAD

**Issue by saadjavaidalvi** [dart-lang/http#377]
*** Here is the link to the API that i am trying to access on the flutter web with the 'GET' request:
https://cowork.pk/rest/session/token

*** The API totally gives the result when on the mobile
*** Gives error when accessing with the flutter web
*** On flutter web when getting the GET request it catches in try catch and gives error of XMLHTTPREQUEST error

This package is a wrapper around the HttpClient from dart:io and HttpRequest
from dart:html. Before filing a bug here verify that the issue is not surfaced
when using those interfaces directly.

https://api.dartlang.org/stable/dart-io/HttpClient-class.html
https://api.dartlang.org/stable/dart-html/HttpRequest-class.html

# Common problems:

- A security policy prevents the connection.
- Running in an emulator that does not have outside internet access.
- Using Android and not requesting internet access in the manifest.
  https://github.com/flutter/flutter/issues/29688

None of these problems are influenced by the code in this repo.

# Diagnosing:

- Attempt the request outside of Dart, for instance in a browser or with `curl`.
- Attempt the request with the dart:io or dart:html equivalent code paths.

**Comment by natebosch** [comment]
Closing in favor of #380
