### ISSUE TITLE
(MultipartRequest) Content-Transfer-Encoding header is probably unnecessary / wrong

### ISSUE THREAD

**Issue by inc-cloitsch** [dart-lang/http#39]
Usually an unnecessary header doesn't hurt.  But in my case the browser aborts an xmlhttprequest:

`XMLHttpRequest cannot load `...`. Request header field content-transfer-encoding is not allowed by Access-Control-Allow-Headers in preflight response.`

Apparently Content-Transfer-Encoding is not a valid http header anyways:
[stackoverflow](http://stackoverflow.com/questions/7285372/is-content-transfer-encoding-an-http-header)

Response I got from the server when the Request method was `OPTIONS`:
```
HTTP/1.1 204 No Content
Date: Wed, 06 Jul 2016 18:27:29 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Allow: OPTIONS,POST
Connection: close
Server: Jetty(9.2.9.v20150224)
```

**Comment by kevmoo** [comment]
@nex3 thoughts on this?

**Comment by nex3** [comment]
We definitely shouldn't be passing this as an HTTP header, but it looks like it is necessary as a header for a multipart chunk (see [the HTML spec](https://www.w3.org/TR/html5/forms.html#multipart/form-data-encoding-algorithm), which refers to [RFC 2388](https://tools.ietf.org/html/rfc2388#section-4.3)).
