### ISSUE TITLE
Sending json as `application/www-form-urlencoded` and get error 415 Unsupported media type

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/http#392]
I use `aqueduct` package for creating REST API. I need to send `json` from client to server but your packages says that `application/www-form-urlencoded` content type must be used and cannot be overriden. When I make a REST API call I get an error `415 Unsupported media type` and this is correct beucase `aqueduct` function expectes `application/json` as content type.
How can I handle this problem now? And why do you limit the `content-type` header using `POST` and `PUT`?

**Comment by bambinoua** [comment]
My mistake. Skip it.

**Comment by ayazthemre** [comment]
what is the mistake? I get same error. Postman works nice but sample code on documentation gives error.
