### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: certificate has expired.

### ISSUE THREAD

**Issue by njovy** [dart-lang/http#393]
I have a flutter app using a self signed certificate. All of a sudden, my app couldn't connect to my rpc server. I thought this issue was related to server but this never happened to me when I use this native Android.

CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:354)). I put 9999 for validity value so it shouldn't be expired. I am not sure why this happens all of a sudden. I used the same configuration for native android and this never happend to me. The server has the same configuration as well so I assume this is related to dart.

I would really appreciate it if anyone can help me to fix this problem.

**Comment by prosperoking** [comment]
@njovy were you able to fix this issue? If yes, could you help me out?

**Comment by dmiedev** [comment]
> @njovy were you able to fix this issue? If yes, could you help me out?

We're having the same issue all of a sudden.

**Comment by unico-pedroalmeida** [comment]
Do anyone have a solution for this problem?

**Comment by prosperoking** [comment]
I ended up having the certificate swapped on the server as the issue had to do with the root cert of let'sencrypt expiring

**Comment by boskokg** [comment]
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
