### ISSUE TITLE
Provide a HttpHeaders class for platform-independent use

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/http#4]
The dart:io.HttpHeaders actually belongs in this library.

I'd prefer at least to have it available here _as well_, so that there is one available for platform-independent development.

**Comment by stevenroose** [comment]
Same goes for HttpStatus and ContentType

**Comment by nex3** [comment]
I'm not a fan of providing giant enums for string-based values like these. I find it rarely provides value on top of just writing the strings yourself, while producing a lot of API overhead and making the code harder to read. I understand the argument that they provide better static checking, but I think constants should be used for improving the readability of the code and correctness should generally be left to the tests, and constants here don't help the readability.

I will point out that [`http_parser`](https://pub.dartlang.org/packages/http_parser) has a cross-platform `MediaType` class that's used by this package.
