### ISSUE TITLE
Flutter web app freezes when http get request is made

### ISSUE THREAD

**Issue by Mateis** [dart-lang/http#400]
I would like to fetch information from an API using an HTTP GET request to a public endpoint which returns XML, in Flutter (web).

However, when I run the code in debug mode, and I reach the screen where the API HTTP request is made, app freezes.

I wrote the following code:

```
import 'dart:async';

import 'package:http/http.dart' as http;
import 'package:xml/xml.dart' as xml;

class SearchApi {

Future fetchPhotos(String query) async {
  final http.Response response = await http.get('https://www.gahetna.nl/beeldbank-api/opensearch/?searchTerms=auto&startIndex=1&count=10', headers: {"Accept": "application/xml"});

  print(response.body);

  if (response.statusCode == 200) {
    // If the server did return a 200 OK response,
    // then parse the XML.
    print(xml.parse(response.body));

    return xml.parse(response.body);
  } else {
    // If the server did not return a 200 OK response,
    // then throw an exception.
    throw Exception('Failed to load photos');
  }
}
```

The code works when I change the http.get url to for instance 'https://jsonplaceholder.typicode.com/todos/1'. The http get request works to the 'https://www.gahetna.nl/beeldbank-api/opensearch/' endpoint, when I use curl in command line.

There are no error messages shown in Visual Studio Code IDE when the screen freezes.

**Comment by natebosch** [comment]
Is there an error in the browser console?

Does this reproduce if you use `dart:html` directly?

**Comment by Mateis** [comment]
@natebosch I appreciate your reply! I wish I replied sooner. My Github notification was set to a dead emailaddress.

I cannot show the error in the browser console at the moment. In the meanwhile, I ran into another issue: https://github.com/flutter/flutter/issues/54040. This issue leads to me being unable to run the app in the browser at all.

**Comment by Mateis** [comment]
It works. This may have been part of the issue: https://github.com/flutter/flutter/issues/41336

Yet I believe it also may have to do with an CORS error (which I also fixed by using a proxy).
