### ISSUE TITLE
HTTP request failed on release build - SocketException: Failed host lookup

### ISSUE THREAD

**Issue by akadatsky** [dart-lang/http#401]
During debug my app works ok, but release build failed with exception: 
`Error: SocketException: Failed host lookup: 'blah-blah' (OS  Error No address associated with hostname, error = 7)`

This issue could be solved by manually added permission to android/app/src/main/AndroidManifest.xml:
`<uses-permission android:name="android.permission.INTERNET" />`

But I believe this library should do it automatically.

**Comment by natebosch** [comment]
> But I believe this library should do it automatically.

We have no mechanism to change your apps permissions and I don't think we would if we could.

As soon as flutter provides a canonical link to documentation about it we'll add it to the readme. Until then you can follow up at https://github.com/flutter/website/issues/3592
