### ISSUE TITLE
Content type 'application/octet-stream' not supported | Status: 415

### ISSUE THREAD

**Issue by Alyahya-A** [dart-lang/http#402]
Hi.
Thank you for this amazing plugin..

I using this plugin for ```get()``` & ```post()```, and every thing work fine.

But when I used ```put()``` it's give me an error

This's my Dio:
```
void setupDio() {
  _dio.interceptors.add(DioInterceptors());
  _dio.options.baseUrl = _config.restBaseURL;
  _dio.options.contentType = 'application/json';
}
```
This's my code:
```
Future<Response> putRequest(String endpoint, {Map<String, dynamic> params}) async {
  final Response response = await _dio.put(
    endpoint,
    data: params,
  );

  return response;
}
```
And the error is:
*Response body* :
```
{
timestamp: "2020-04-09",
status: 415,
error: "Unsupported Media Type",
message: "Content type 'application/octet-stream' not supported",
path: "/api/someString"
}
```
*Response headers* :
```
I/flutter (23979): ╔ Headers
I/flutter (23979): ╟ cache-control: [no-cache, no-store, max-age=0, must-revalidate]
I/flutter (23979): ╟ date: [Thu, 09 Apr 2020 21:53:41 GMT]
I/flutter (23979): ╟ transfer-encoding: [chunked]
I/flutter (23979): ╟ vary: [Origin, Access-Control-Request-Method, Access-Control-Request-Headers]
I/flutter (23979): ╟ via: [1.1 google]
I/flutter (23979): ╟ pragma: [no-cache]
I/flutter (23979): ╟ content-type: [application/json]
I/flutter (23979): ╟ x-xss-protection: [1; mode=block]
I/flutter (23979): ╟ x-content-type-options: [nosniff]
I/flutter (23979): ╟ server: [nginx/1.17.9]
I/flutter (23979): ╟ expires: [0]
I/flutter (23979): ╚══════════════════════════════════════════
```

So can any one help me ?

**Comment by Alyahya-A** [comment]
I found the issue..

```  _dio.options.contentType = 'application/json';```  doesn't work..


So, I write it in ```onRequest()``` inside my ```DioInterceptors()```. Now it's work..

Thans :)

**Comment by saswatsaubhagya** [comment]
not working.
_dio
      ..options.headers.addAll({
        'Content-Type': 'application/json;charset=UTF-8',
        'Accept': 'application/json',)}
        
         onRequest: (RequestOptions options) async {
          options.contentType = 'application/json;charset=UTF-8';
          options.baseUrl =
              "";
          return options;
        },
