### ISSUE TITLE
Not timing out for POST request using IP address

### ISSUE THREAD

**Issue by kr1tzy** [dart-lang/http#403]
This POST request doesn't timeout when using an ip address as the host. When i use the domain name it does. Anyone else have this problem? 

<img width="333" alt="Screen Shot 2020-04-16 at 10 11 23 PM" src="https://user-images.githubusercontent.com/14809526/79524713-36d57b00-802f-11ea-8760-09abf4e50ea8.png">

**Comment by SELiOTe** [comment]
same problem, any solution?
