### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by dhs9004** [dart-lang/http#404]
how to solve flutter web ERR_CERT_AUTHORITY_INVALID error while performing a POST request?

Do you have a bad Certificate Callback that I can use?

XMLHttpRequest error.

Thanks in advance

**Comment by funkju** [comment]
#267 has the answer for you mate.

**Comment by dhs9004** [comment]
Hi Justin, 
Thank you for your answer but I can't use it on a flutter web application.

`Error: Unsupported operation: Platform._version`

**Comment by natebosch** [comment]
As far as I'm aware this isn't something that is possible in javascript in the browser. This library can only expose the capabilities from `dart:html`, which in turn can only expose the capabilities provided by the browser in JS.

@sigmundch may be able to correct me if I'm wrong, but I don't think there is anything we can do on this.
