### ISSUE TITLE
Flutter Web Missing Response Headers | http 0.12.0+4

### ISSUE THREAD

**Issue by DenisBarzanov** [dart-lang/http#409]
I have an app that makes requests here and there and it doesn't work both on Web and on Android, because some headers are missing when on the Web.

```dart
final response = await _client.post(
  'http://100.115.92.198:8080/login',
  body: jsonEncode({
    'email': email,
    'password': password,
  }),
  headers: {HttpHeaders.contentTypeHeader: 'application/json'},
);

switch (response.statusCode) {
  case 200:
    final authToken = response.headers['authorization'];
    prefs.setString('authToken', authToken);
    userSubject.add(authToken.toUser());
    return;
  default:
    throw Exception('Unknown error');
}
```

## Expectation 
![Screenshot 2020-04-19 at 23 04 57](https://user-images.githubusercontent.com/29101425/79698667-08f07080-8293-11ea-99b9-87ab05d6d408.png)

When I compile my app for the Web I see only 4 headers, while if I compile for Android, I see everything as it is in the network tab.
While compiling  the web it used to work with "Authorization", but now it is not showing in the response headers either. 
It shows me 
## Reality
![Screenshot 2020-04-19 at 23 24 51](https://user-images.githubusercontent.com/29101425/79699001-350cf100-8295-11ea-8c6a-2cbff9eedf27.png)

while in the network tab I have
## Network Tab
![Screenshot 2020-04-19 at 23 25 14](https://user-images.githubusercontent.com/29101425/79699009-40601c80-8295-11ea-9e5b-2c795d9bfb06.png)

As you can see, there are a lot more response headers that I don't see in the map.

On Android on the other all headers are present all the time.
Complete madness. This is strange, because I developed some of my app while compiling for the Web and when I switched to Android (dev experience) I started seeing this strange behavior.

### http package version
I am using the latest version of http (0.12.0+4). I have it left out blank: `http: `

### `flutter doctor -v`
```
[✓] Flutter (Channel dev, v1.18.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0 at /home/denisbarzanov2002/flutter
    • Framework revision 8f7327f83a (13 days ago), 2020-04-06
      22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 29.0.2)
    • Android SDK at /home/denisbarzanov2002/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/denisbarzanov2002/idea-IU-192.7142.36
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7402

[✓] VS Code (version 1.44.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Google Pixelbook • 100.115.92.2:5555 • android-x64    • Android 9 (API 28)
    • Chrome     • chrome     • web-javascript • Google Chrome
      79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
I tried the code on all branches and it still doesn't work. It used to work with `'Authorization'` (capital 'A') before I switched to Android, but now it doesn't anymore. I must have updated something without realising.
I was told to ask for help here when I filed an issue on the flutter/flutter repository (#55163)

## Works with `dart:io`
If I test the same thing through the `dart:io` library, everything works as expected.

```dart
import 'dart:convert';
import 'dart:io';

void main() async {
  final client = HttpClient();
  final request = await client.postUrl(Uri.parse("http://100.115.92.198:8080/login"));
  request.headers.set(HttpHeaders.contentTypeHeader, "application/json; charset=UTF-8");
  request.write('{"email": "...", "password": "..."}');

  final response = await request.close();
  print(response.headers);
}
```

```
cache-control: no-cache, no-store, max-age=0, must-revalidate
date: Tue, 21 Apr 2020 11:56:17 GMT
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
content-length: 0
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW5pcy5iYXJ6YW5vdjIwMDJAZ21haWwuY29tIiwiZXhwIjoxNTg4MzM0MTc3fQ._hxR67zg17Okiwjo8HA79hratFrJ7VQmCUWSo9pAyGZ7eon-73Js86qnENx9rnWh630UtejMzImctcZoOKkI1g
x-frame-options: DENY
pragma: no-cache
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
expires: 0
```

**Comment by DenisBarzanov** [comment]
The issue was me now knowing the protocols enough. 
The problem was that the browser is not allowed to access the headers from a different origin unless the back-end allows this.
I forgot to add `res.setHeader("Access-Control-Expose-Headers", "*");` to my response header in `Spring Boot` (not my will to use this framework).
When I add the header, the js response becomes:
```
{access-control-allow-origin: http://localhost:4200, access-control-expose-headers: *, 
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW5pcy5iYXJ6YW5vdjIwMDJAZ21haWwuY29tIiwiZXhwIjoxNTg4NjA0MDU5fQ.1gouv3lOE6Ohj8UaH766_pK6I56QnGBksHBTt15Lk2uJX1plVaJn6iadOfUZXXhh6A3qx1h99hrXlFUPLBvuYw, 
cache-control: no-cache, no-store, max-age=0, must-revalidate, connection: keep-alive, content-length: 0, date: Fri, 24 Apr 2020 14:54:19 GMT, expires: 0, 
keep-alive: timeout=60, pragma: no-cache, vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers, x-content-type-options: nosniff, x-frame-options: DENY, x-xss-protection: 1; mode=block}
```

**Comment by lazicah** [comment]
Please how did you fix this, because i am experiencing same issue

**Comment by V1CTOR-cloud** [comment]
my server is on node with express, this solved my issue, then just use http package or Dio and create the service.
`app.use(cors({
    exposedHeaders: 'auth_token',
}));`
