### ISSUE TITLE
Sending a custom http method

### ISSUE THREAD

**Issue by alirezat66** [dart-lang/http#413]
Hi, I wanna use a method like 'CLAIM' instead of Get, post, delete, etc. How can do that?

**Comment by vanceism7** [comment]
Just ran into this little issue myself. The solution is to just construct the request yourself and then send it
E.g:
```dart
makeClaimRequest(url) {
  final response =
          await http.Request("CLAIM", url).send().then(http.Response.fromStream);
  // Do stuff with the response...
}
```
