### ISSUE TITLE
IOClient send override

### ISSUE THREAD

**Issue by jvmvl** [dart-lang/http#414]
I have code like
```
class CustomHttpClient extends IOClient {
  CustomHttpClient({Map<String, String> headers})
      : this._headers = headers ?? <String, String>{},
        super();

  final Map<String, String> _headers;

  @override
  Future<StreamedResponse> send(BaseRequest request) =>
      super.send(request..headers.addAll(_headers));

  @override
  Future<Response> head(Object url, {Map<String, String> headers}) =>
      super.head(url, headers: headers..addAll(_headers));

  @override
  Future<Response> get(Object url, {Map<String, String> headers}) =>
      super.get(url, headers: (headers ?? _headers)..addAll(_headers));
...
```
Each request type has `url` as a parameter. You can modify it before pasing it to `super.xxx()`

_Originally posted by @zoechi in https://github.com/dart-lang/http/issues/196#issuecomment-417844581_

This shows the following error any idea why?

`error: 'CustomHttpClient.send' ('Future<StreamedResponse> Function(BaseRequest)') isn't a valid override of 'IOClient.send' ('Future<IOStreamedResponse> Function(BaseRequest)'). (invalid_override at [googlesignin] lib\main.dart:51)`

**Comment by boskokg** [comment]
Replace Future<StreamedResponse> with Future<IOStreamedResponse>

**Comment by jvmvl** [comment]
It works, thanks @boskokg
