### ISSUE TITLE
can I use MockClient to verify if the function has been call and its params

### ISSUE THREAD

**Issue by NanYeYe** [dart-lang/http#417]
can I use MockClient to verify if the function has been call and its params.
I can not find any function about this.

**Comment by natebosch** [comment]
You can see the api at https://pub.dev/documentation/http/latest/testing/MockClient-class.html

`Mock` was an incorrect choice of name, this is more like a `StubClient`. There is no recording of calls built in. As the docs point out this is for stubbing behavior of handling requests.

If you are looking for general purpose mocking and verification of method calls see mockito. https://pub.dev/packages/mockito
