### ISSUE TITLE
response get bytes (or else meanwhile) may extremely slow

### ISSUE THREAD

**Issue by peterweb2005** [dart-lang/http#420]
dear all,

as:
```
    // process request
    final http.StreamedResponse resp = await XXX;

      final int time = TimeUtil.timestamp();
      final Uint8List bytes = await resp.stream.toBytes();
      log.fine('time (bytes): ', (TimeUtil.timestamp() - time));
      //log.finest('bytes: ', bytes);
```
the time interval is very slow, many seconds

```
      msg = Message.fromBuffer(bytes);
      log.fine('time (message): ', (TimeUtil.timestamp() - time));
```
very fast, a few 1/10 seconds

when test with standalone pc program (no flutter), the time are static, always 6xms, 
but when run in mobile in flutter platform, the time varies 1xxms (0.1 second) to xxxxms (few seconds)

**Comment by peterweb2005** [comment]
update

sdk 1.17 had faster
but 1.17.1 bad again as before

**Comment by natebosch** [comment]
This package will not cause this behavior. It's possible there is a bug in the SDK, but there isn't a lot to go on here.

I'd recommend ruling out `package:http` by using `dart:io` directly and filing an issue on the SDK repo.
