### ISSUE TITLE
Set followRedirects to false not work on flutter web.

### ISSUE THREAD

**Issue by ltvu93** [dart-lang/http#432]
Hi,
I try to set followRedirects to false to intercept the value in the location header of the response. But it not work on flutter web, when I try to build code in mobile side, it work normal.
How can I make it work, or it is the expect behavior in the web?

```
  // http: ^0.12.1
  import 'package:http/http.dart' as http;

  Future<void> test() async {
    const url = 'http://wikipedia.net';
    final client = http.Client();
    final request = http.Request('GET', Uri.parse(url))
      ..followRedirects = false;
    final response = await client.send(request);

    debugPrint(
        'test test location: ${response.headers['location']} statusCode: ${response.statusCode}');
  }

// Expect: print location: http://wikipedia.org statusCode 301
// Actual: print location: null statusCode 200
// Only return the expect result when build the mobile app.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15 19A583, locale
    en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by ltvu93** [comment]
Found the solution with dart:html HttpRequest. But I expect it works on http/http.dart.

```
import 'dart:html' as html;

Future<void> test() async {
    const url = 'http://wikipedia.net';
    final htmlRequest = await html.HttpRequest.request(url, method: 'GET');
    debugPrint('test test ${htmlRequest.responseUrl}');
}
// Print http://wikipedia.org
```

**Comment by masewo** [comment]
Your solution follows redirects so the original issue is still persisting. On flutter web disabling followRedirects is not possible.

**Comment by ltvu93** [comment]
> Your solution follows redirects so the original issue is still persisting. On flutter web disabling followRedirects is not possible.

Yeah, It still called the redirect URL. But I just need to intercept the redirect URL and get information for this, so that solution is good enough for me.

**Comment by SaltumDis** [comment]
@masewo do you have any idea how to disable redirects on web? And could we reopen this issue?

**Comment by jofas** [comment]
> Your solution follows redirects so the original issue is still persisting. On flutter web disabling followRedirects is not possible.

I guess it's because this library utilizes XHR when used in web? I don't think the XHR API describes a flag for disabling redirects, like the fetch API does (https://developer.mozilla.org/en-US/docs/Web/API/Request/redirect). I do not know why XHR was chosen instead of fetch as the underlying web API for http requests. Except by exchanging XHR to fetch, I don't think that you can solve this issue.

... I'd still like to reopen this issue, because I would really appreciate having control of the redirection flow in my application.

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by CannibalKush** [comment]
I also have this problem and it's very annoying :(

**Comment by rynoV** [comment]
I am also running into this issue

**Comment by savadodesigns** [comment]
I also run into this issue. Please consider re-opening this ticket.

**Comment by jblankenship5** [comment]
this issue still exists... can't get a file from s3 because it's passing along the auth header, and I can't disable follow redirects to intercept.

**Comment by Binozo** [comment]
Issue still exist in 2024 with Flutter `3.16.9 (stable)`

**Comment by C0DE-IN** [comment]
`import 'package:http/http.dart' as http; 
class CustomHttpClient extends http.BaseClient {
  final http.Client _inner = http.Client();
  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    try {
      final response = await _inner.send(request
        ..followRedirects = false
        ..maxRedirects = 0)
        ..stream.first;
      return response;
    } catch (e) {
      throw Exception('error while getting websocket url:$e');
    }
  }
}` iam getting a 302 response in network with location header but after that getting an error saying net::ERR_UNKNOWN_URL_SCHEME and then 'error while getting websocket url:$e ,
