### ISSUE TITLE
XMLHttpRequest response details needed!

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/http#434]
Yes, I read the notice in your code where you said about "underlying XMLHttpRequest API doesn't expose any specific information", but is it really **true**? No response, no headers?! As for me it is impossible, sorry. :) I think something **must be**. When I call unexistent URL using your client, of host is down, or incorrect port I get the **same** error (XMLHttpRequest error)! But user need to have more details! If URL does not exists, don't 404 status returned, really? How can it be?
Please investigate more this problem. Thank you in advance!

P.S. Some doc propes which I am confident can be returned:
https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/status
https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/statusText
https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/responseXML

```dart
var xhr = new XMLHttpRequest();
xhr.open('GET', '/server', true);

// responseType должно быть пустой строкой, либо "text"
xhr.responseType = 'text';

xhr.onload = function () {
    if (xhr.readyState === xhr.DONE) {
        if (xhr.status === 200) {
            console.log(xhr.response);
            console.log(xhr.responseText);
        }
    }
};

xhr.send(null);
```

**Comment by andyduke** [comment]
Detailed information about the error in `send()` is really necessary, without it it is impossible to make a production-ready application. I agree with @bambinoua that we need to know in the Exception what kind of error (host unavailable, server error, etc.), code (`status`) and error text (`statusText`).

If the `HttpRequest` in `dart:html` does not provide such information, although the browser does provide such information, is it really impossible to add that?

**Comment by natebosch** [comment]
> although the browser does provide such information

Can you elaborate? The example code above does not use `xhr.error` or `xhr.onError`, and I don't see the requested information on `ProgressEvent` in the spec. https://xhr.spec.whatwg.org/#event-xhr-error

Can you give some example code in JavaScript handling an error in the way you hope to be able to handle it in Dart?

**Comment by andyduke** [comment]
@natebosch In JavaScript, when a response comes with, for example, a 500 error, it is possible to get this 500 code and a reason text. In dart.js, when responding with an error of 500, an exception occurs in dart, in which there is no code and the reason text of the error.

**Comment by natebosch** [comment]
> when a response comes with, for example, a 500 error, it is possible to get this 500 code and a reason text.

This is possible with this package in Dart as well.

> In dart.js, when responding with an error of 500, an exception occurs in dart, in which there is no code and the reason text of the error.

Can you share an example?

I can see a `500` response show up through the normal mechanism when I have a well behaved server that doesn't trigger CORS issues.

If I make a request that has a CORS problem it of course surfaces as an error as the browser will not surface the rest of the response.

You should have an error in your browser console indicating what the problem is. When you are hitting this case I don't think there is anything we can do about it on our side to expose more information since it is the browser hiding it.
