### ISSUE TITLE
Slow API call on iOS side.

### ISSUE THREAD

**Issue by HumbleCarl** [dart-lang/http#438]
Hey guys is there a way to fix slow request on the iOS side? Thank you

**Comment by SeasonLeee** [comment]
...I just want to cry.... this problem exist for so long and nothing progress..... god... anyone? I have a published app is having this problem....

**Comment by spazzlite** [comment]
Not sure that problem only on ios side... but, for example api call in postman shows 100 ms maximum, when package get shows 500 ms minimum...

**Comment by natebosch** [comment]
Issues with the flutter or Dart SDKs should be filed in their respective repositories. Nothing in this package will cause requests to be slower on any given platform.  This issue may be https://github.com/dart-lang/sdk/issues/41451
