### ISSUE TITLE
Why http doesn't work in physical ios device?

### ISSUE THREAD

**Issue by jims57** [dart-lang/http#447]
I am using http: ^0.12.2. Although other device like macOS, even iOS simulators are able to work with http normally.
It fails after I try to debug in my physical device. Is it a bug in iOS?

[Other suggests to use **Dio**](https://stackoverflow.com/questions/54253064/flutter-http-request-not-being-executed-on-ios), I am not sure it is a solution.

**Comment by enyo** [comment]
I'm having the same problem, initially reported here: flutter/flutter#66471

**Comment by natebosch** [comment]
This could be a problem with permissions or the device. You'll fine the same requests also fail when using `HttpClient` from `dart:io` indicating this is not a problem that can be solved in `packag:http`. 

 See https://github.com/flutter/website/issues/3592
