### ISSUE TITLE
Question: Using URL with https means that it is secure?

### ISSUE THREAD

**Issue by joaofrassetto** [dart-lang/http#454]
I have a domain using SSL. If I use `var response = await http.post('https://...', ...)` it means that this request and the response to that is safe?

If not, can someone help me to make it safe, please?

Sorry if this is not the place to make this question.

Thank you.

**Comment by zichangg** [comment]
The short answer is yes. `https` will use secure socket to connect.

**Comment by natebosch** [comment]
It's not clear what you mean by "safe". If you specifically mean "will use SSL" then yes, it will.

Closing for now since I don't think there are any actions for us to take here.
