### ISSUE TITLE
Json Content-Type and explicity encoding declaration

### ISSUE THREAD

**Issue by MichelFortes** [dart-lang/http#455]
Like the Spring developer team has done, it would be interesting to consider that all content-type "application/json" responses where encoded with UTF-8 charset.

From Spring Team:
/**
	 * A String equivalent of {@link MediaType#APPLICATION_JSON_UTF8}.
	 * @deprecated as of 5.2 in favor of {@link #APPLICATION_JSON_VALUE}
	 * since major browsers like Chrome
	 * <a href="https://bugs.chromium.org/p/chromium/issues/detail?id=438464">
	 * now comply with the specification</a> and interpret correctly UTF-8 special
	 * characters without requiring a {@code charset=UTF-8} parameter.
	 */
	@Deprecated
	public static final String APPLICATION_JSON_UTF8_VALUE = "application/json;charset=UTF-8";

**Comment by pierrediderot** [comment]
+1.

**Comment by natebosch** [comment]
Closing in favor of #174

The expected pattern to use today when you know the result is json is `jsonDecode(utf8.decode(response.bodyBytes))`. We should consider changing the default decoding so that fewer users get confused by this.

**Comment by DeD1rk** [comment]
@natebosch you linked the wrong issue

**Comment by natebosch** [comment]
@DeD1rk - corrected. Thanks for the heads up!
