### ISSUE TITLE
Treat HTTP 422 as error

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/http#461]
`HTTP 422`  is treated as response other than error now. According to https://stackoverflow.com/questions/16133923/400-vs-422-response-to-post-of-data, error may be a better choice

And [angular/http](https://www.npmjs.com/package/@angular/http) DOES treat it as error, from https://thinkster.io/tutorials/building-real-world-angular-2-apps/intercept-and-manipulate-http-requests

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;

void main(List<String> arguments) {
  print('Hello world!');
  var body = {
    'user': {
      'username': '',
      'password': '',
    }
  };

  http.post(
    'https://conduit.productionready.io/api/users/login',
    body: jsonEncode(body),
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    },
  ).catchError((error) {
    print('onError $error');
  }).then((response) {
    print('onResponse statusCode ${response.statusCode}');
    print('onResponse body ${response.body}');
  });
}
```

**Comment by simolus3** [comment]
This package doesn't treat any http status code as an error AFAIK. If you want an exception for invalid status codes, you'll need to add that check yourself.

**Comment by Sunbreak** [comment]
> This package doesn't treat any http status code as an error AFAIK. If you want an exception for invalid status codes, you'll need to add that check yourself.

No, it doesn't, even on `400`. Could it be?

```dart
import 'package:http/http.dart' as http;

void main(List<String> arguments) {
  http
      .post(
    'https://httpstat.us/400',
  )
      .catchError((error) {
    print('onError $error');
  }).then((response) {
    print('onResponse statusCode ${response.statusCode}');
    print('onResponse body ${response.body}');
  });
}
```

**Comment by simolus3** [comment]
For what its worth, I don't think this package _should_ throw on invalid status codes, since an `HttpResponse` with a `statusCode` of `400` is still an `HttpResponse` and thus, not exceptional behavior.
There are higher-level packages like [dio](https://pub.dev/packages/dio) which do throw on unexpected status codes, maybe you're better off using those?

**Comment by Sunbreak** [comment]
> For what its worth, I don't think this package _should_ throw on invalid status codes, since an `HttpResponse` with a `statusCode` of `400` is still an `HttpResponse` and thus, not exceptional behavior.
> There are higher-level packages like [dio](https://pub.dev/packages/dio) which do throw on unexpected status codes, maybe you're better off using those?

I encounter the problem in AngularDart. Is `Dio` compatible?

**Comment by natebosch** [comment]
We only throw exceptions if the underlying platform does. From the standpoint of this package an error response is still a response. It's up to your application code to decide what to do with the status codes.

> Is `Dio` compatible?

That is a question best asked to the authors of that project. I would assume it is compatible with the web platform.
