### ISSUE TITLE
Raw Json in Body POST

### ISSUE THREAD

**Issue by pratamarama** [dart-lang/http#467]
can i use raw json in body of POST request?

**Comment by natebosch** [comment]
See the docs. https://pub.dev/documentation/http/latest/http/Client/post.html

> body sets the body of the request. It can be a String, a List<int> or a Map<String, String>. If it's a String, it's encoded using encoding and used as the body of the request. The content-type of the request will default to "text/plain".

You can use `jsonEncode` to get a `String` for some json values.
