### ISSUE TITLE
http post error Expected a value of type 'String', but got one of type 'NoSuchMethodError'

### ISSUE THREAD

**Issue by MarcoPetrolo1992** [dart-lang/http#468]
Hi! I have a problem when i call my NodeJs Server by Flutter Web Application that is the code:

final String serverUrl = GlobalConfiguration().getValue<String>("server_url");
  Future<void> login(
      {@required String email, @required String password}) async {
  

    String url = serverUrl + '/login';

    Map<String, dynamic> body = {"email": email, "password": password};
    http.Response response = await http.post(Uri.encodeFull(url),
        body: json.encode(body),
        headers: {
          "Accept": "application/json"
        }).catchError((onError) => debugPrint(onError));

    if (response.statusCode == 200) {
      await _tokenRepository
          .saveToken(json.decode(response.body)["token"].toString());
      User loggedUser = User.fromJson(json.decode(response.body)["utente"]);
      await setUser(loggedUser);
    } else {
      debugPrint('error');
      throw Exception('Error in login');
    }
  }

but when excute the method i have this error:

onError Expected a value of type 'String', but got one of type 'NoSuchMethodError'
Error: Unhandled error Expected a value of type 'String', but got one of type 'NoSuchMethodError' occurred in Instance of 'LoginBloc'.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 60:3        castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 411:9        as
packages/be_the_one_flutterweb/blocs/login_bloc.dart 71:17                                                                     _mapSubmittedToState
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 284:32               <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1455:54                                              runBinary

when i execute the call by Postman and by Browser the response is correct.

I use http: ^0.12.2

here's my flutter doctor -v

[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Versione 10.0.19041.508], locale it-IT)
    • Flutter version 1.22.0-12.1.pre at C:\flutter
    • Framework revision 8b3760638a (2 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)     
    • Android SDK at C:\Users\39320\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\39320\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 84.0.522.63

• No issues found!

**Comment by MarcoPetrolo1992** [comment]
Sorry i fix this, the problem was related to global_configurations library.

**Comment by ligun123** [comment]
@MarcoPetrolo1992 how to fix it?
