### ISSUE TITLE
type 'list<dynamic> is not a sub type of <string> in my case : Basically I am retrieving video array data from my cloud firesotre

### ISSUE THREAD

**Issue by KetulMehta294** [dart-lang/http#476]
My main. dart file is: 

import 'dart:io';

import 'chewie_list_item.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:video_player/video_player.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
    if (kReleaseMode) exit(1);
  };

  runApp(MaterialApp(
    home: CourseApp(),
  ));
}

class CourseApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance.collection("courses").snapshots(),
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
          return new ListView(children: getCourseItems(snapshot));
        });
  }

  getCourseItems(AsyncSnapshot<QuerySnapshot> snapshot) {
    return snapshot.data.documents
        .map((doc) => new ChewieListItem(
            videoPlayerController:
                VideoPlayerController.network(doc['video'] ?? 'default')))
        .toList();
  }
}

My chiewe_list_item.dart flie is:

import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ChewieListItem extends StatefulWidget {
  // This will contain the URL/asset path which we want to play
  final VideoPlayerController videoPlayerController;
  final bool looping;

  ChewieListItem({
    @required this.videoPlayerController,
    this.looping,
    Key key,
  }) : super(key: key);

  @override
  _ChewieListItemState createState() => _ChewieListItemState();
}

class _ChewieListItemState extends State<ChewieListItem> {
  ChewieController _chewieController;

  @override
  void initState() {
    super.initState();
    // Wrapper on top of the videoPlayerController
    _chewieController = ChewieController(
      videoPlayerController: widget.videoPlayerController,
      aspectRatio: 16 / 9,
      // Prepare the video to be played and display the first frame
      autoInitialize: true,
      looping: widget.looping,
      // Errors can occur for example when trying to play a video
      // from a non-existent URL
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Chewie(
        controller: _chewieController,
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    // IMPORTANT to dispose of all the used resources
    widget.videoPlayerController.dispose();
    _chewieController.dispose();
  }
}
![Screenshot (235)](https://user-images.githubusercontent.com/68146462/94483397-6d2b3f00-01f8-11eb-8e7d-aa2d24276c55.png)

**Comment by abhikhedekar4241** [comment]
Use 
StreamBuilder<String>

Always mention the data type of the data which you are retrieving.

**Comment by natebosch** [comment]
This appears to be some confusion in using flutter APIs unrelated to this package.

If you believe there is a bug in `package:http` please post a full stack trace and a minimal reproduction case.
