### ISSUE TITLE
Post array using http in flutter

### ISSUE THREAD

**Issue by tony123S** [dart-lang/http#482]
How to post array using http?
```

var headers = {"Accept": "application/json"};
      var url = "https://...."
      var response = await http.post(url,
          body: {
           ....
          },
```
I have a param named commentList. I need to pass `comment[0]`, `comment[1]`... inside body.

**Comment by Babwenbiber** [comment]
Works as you would expect:
```
List<String> comments = ["1st", "2nd", "3rd"];
String url = "myurl.com";
var body = json.encode(comments);
final response = await http
    .post(url, body: body, headers: {'Content-type': 'application/json'});
```

**Comment by itsdani121** [comment]
i did the same but in database or server it show empty array , i dont know i tried all solution but not work . i have data which i want to post it to server but did not work for me this solution.

**Comment by jordydave** [comment]
can I see the full whole code, sir? I'm already surfing all night long but didn't get the solution. your case is the same as me

**Comment by itsdani121** [comment]
i resolve this issue, which is application/json is not working instead of urlencoded which then works fine

**Comment by raad9114** [comment]
final response = await http.post(
        Uri.parse('http://yourip/api/SendNotificationToDevice'),
      body: jsonEncode(<String, dynamic>{
        "devices": ["device_code"]
      }), headers: {'Content-type': 'application/json'}
    );
