### ISSUE TITLE
Http Headers are not forwarded to API-URL 

### ISSUE THREAD

**Issue by SameerChorge94** [dart-lang/http#488]
**Description:**
As per the project requirement i need to send the headers to the http post request.
but after adding the headers, it is not forwarded to the API
For all the below scenarios mentioned, even after sending the request headers, API doesn't receive any of the provided headers information.
 
**Example :**
Request Body is Same for all below scenarios:

```
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:io';

var reqBody = jsonEncode({
        "query": query,
        "variables": {},
      });
```

1. **With Http Post**
```
final response = await http.post(GRAPH_QL_API_URI,
          body: reqBody,
          headers: {
            HttpHeaders.authorizationHeader:
                'Bearer ${storage.read('access_token')}'
          });
```

**2. With Http client** 
```
http.Client client = http.Client();
      final response = await client.post(GRAPH_QL_API_URI, body: reqBody,
          headers: {
            HttpHeaders.authorizationHeader:
                'Bearer${storage.read('access_token')}'
          })
```

**3. With Headers as a Map**
```
      Map<String, String> _headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer ${storage.read('access_token')}",
      };
      final response = await http.post(GRAPH_QL_API_URI,
          body: reqBody,
          headers: _headers
      )
```

**Flutter version** 
```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (2 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```

**Http Package Version:**
using the latest version only as specific version not mentioned in the yaml file
`http: any`

**Expected Result:**
Headers provided must be forwarded to the respective API

**Actual Result**
Even After providing headers are not forwarded to the specified API URL

Suggest any solution for sending the headers using http package.

**Comment by trqalothman** [comment]
I have the same problem with get request using headers to consume a PHP api.  With postman it works perfectly, however, when I make the request with the following flutter code:

`await http.get(url, headers: {'Authorization': '[APIKEY]'})`

and then I try to pull the info from PHP, with the following code:

```
$headers = apache_request_headers();
$accessToken = $headers['Authorization'];
```

it responds with a blank $accessToken.  Even when I send back the $accessToken from PHP to flutter response, it sends it blank.

Please check / help!

Thanks

`Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)`

**Comment by SameerChorge94** [comment]
Resolved.

**Comment by SameerChorge94** [comment]
Resolved as per the browser console facing the CORS issue while calling the API
`
Access to XMLHttpRequest at 'http://localhost:4002/graphql' from origin 'http://localhost:60324' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`
Resolved by handling the CORS Policy at the API side after that able to send the request headers from the flutter web also with **http.post** implementation.
