### ISSUE TITLE
FileSystemException: Cannot retrieve length of file, path = '/home/{username}/{File name}.mp4' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by zeeshan-iqbal-cs** [dart-lang/http#490]
I'm trying to upload a large file (around 2 GB in size) on an express server.
## Problem facing
The code that I was running
```
import 'package:http/http.dart' as http;

Uri url = Uri.parse('web url');

void main(List<String> arguments) {
  print('Hello!');
  var request = http.MultipartRequest('POST', url);
  http.MultipartFile.fromPath('video', 'file path').then((http.MultipartFile file) {
    request.files.add(file);
    request.send().then((http.StreamedResponse res) {
      print(res);
    });
  }).catchError((error) {
    print(error);
  });
}

```

When I run the following code it shows me this error.

FileSystemException: Cannot retrieve length of file, path = '/home/{username}/{File name}.mp4' (OS Error: No such file or directory, errno = 2)

## Environment details
1. Linux Ununtu 20.10
2. Dart SDK version: 2.10.2 (stable)

I am not using flutter this is my dart project.

**Comment by natebosch** [comment]
> OS Error: No such file or directory, errno = 2

It looks like your'e trying to read a file path that doesn't exist.
