### ISSUE TITLE
Need to override application/json default content decoder to UTF-8

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/http#494]
I have a sample app that makes http get requests to Unsplash's API. The results are in the form of `application/json`, encoded in UTF-8. Unfortunately, the `content-type` on the return is `application/json`, not `application/json; charset=utf-8`.

See https://github.com/flutter/samples/issues/586 for details.

Ask: allow overriding the default content type charset to UTF-8. Or, ignore the standard and make UTF-8 the default as it's what most people expect, and I suspect what web browsers do by default.

**Comment by DeD1rk** [comment]
See the discussion in #175.

**Comment by natebosch** [comment]
I do think we should consider this.

In the mean time, the expected pattern is `jsonDecode(utf8.decode(response.bodyBytes))`, not `jsonDecode(response.body)`.

**Comment by natebosch** [comment]
Closing in favor of #175
