### ISSUE TITLE
Add utility methods for Basic Auth, Digest Auth, etc.

### ISSUE THREAD

**Issue by wstrange** [dart-lang/http#5]
dart:io HttpClient has utility methods for adding client credentials to the request:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io.HttpClientCredentials

It would be convenient to have similar methods. Not sure where it fits in this library's API.

**Comment by donny-dont** [comment]
This will be done through middleware going forward. Can close.
