### ISSUE TITLE
Does this plugin make HTTPS connections using URLSession in the iOS

### ISSUE THREAD

**Issue by yash365** [dart-lang/http#532]
I have successfully uploaded the app in TestFlight in iOS Platform. It ask for the following messsage: 

"Typically, the use of encryption that’s built into the operating system—for example, when your app makes HTTPS connections using URLSession—is exempt from export documentation upload requirements, whereas the use of proprietary encryption is not."
Wanted to know does this plugin make HTTPS connections using URLSession in the iOS.

Link:
https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations

**Comment by natebosch** [comment]
No. This package does no use `URLSession` and AFAIK neither does the SDK.

This package wraps `HttpClient` when running on mobile. https://api.dart.dev/stable/2.12.2/dart-io/HttpClient-class.html

That class uses sockets for http requests.
