### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by dmvvilela** [dart-lang/http#533]
Version 0.13.0 has this Uri thing instead of String.

**Comment by rakesh4577** [comment]
did you find out anything, i am stuck too, don't know what to pass in Uri :(

**Comment by dmvvilela** [comment]
@rakesh4577 You can use Uri.parse(url) and it will be the same thing.

**Comment by bokanian** [comment]
what is the point for Uri.parse?

**Comment by dmvvilela** [comment]
@bokanian Give this a read and then you will understand: [https://suragch.medium.com/understanding-the-uri-class-in-dart-from-examples-7015a3643e47](https://suragch.medium.com/understanding-the-uri-class-in-dart-from-examples-7015a3643e47)

**Comment by guillermo-ampie** [comment]
@dmvvilela Thanks for the reference!. 

A direct example here, I hope this lead you all in the right direction:
Sample URL:  https://api.openweathermap.org/data/2.5/weather?q=Miami&appid=FAKE_APP_ID_VALUE

In v0.13.0, you need to use a Uri (String is no allowed anymore):

`var city = 'Miami';`
`const apiKey = 'FAKE_APP_ID_VALUE';`
`final Map<String, String> queryParameters = {'q': city, 'appid': apiKey};`
`const authority = 'api.openweathermap.org';`
`const path = '/data/2.5/weather';`
`final uri = Uri.https(authority, path, queryParameters);`

Make your call:
`final response = await httpClient.get(uri, headers: {
    'Content-Type': 'application/json',
  });`

Process `response` as usual.
