### ISSUE TITLE
await http.get(Uri.encodeFull doesn't work with Flutter 2.0

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/http#536]
Today I clean install flutter 2.0 and my project is not working in below line. Before upgrade this line **http.get(Uri.encodeFull**  was working. I look to find any information and documentation is outdated and doesn't include new changes. Any idea?

`var _response = await http.get(Uri.encodeFull("www.googleapis.com"), headers: {'Accept': 'application/json'});`

I use https://flutter-website-staging.firebaseapp.com/networking/ example and I am keep getting "Failed" and I have 20MB wireless internet and its workin as well as I don't have any firewall. 

  Future<void> checkConnection() async {
 
    try {
      var url = 'www.google.com';
      var httpClient = new HttpClient();

      var request = await httpClient.getUrl(Uri.parse(url));
      print("request ${request.headers}");
      var response = await request.close();
      if (response.statusCode == HttpStatus.ok) {
        print("Has Internet");
      } else {
        print("Http status ${response.statusCode}");
      }
    } catch (exception) {
      print("Failed");
    }
  }

I am not sure why this not working.

**Comment by Clashkid155** [comment]
Having same problem. In 0.12.2 i didn't have to encode string but even if i try encoding my url on 0.13.0 ,it doesn't work.

**Comment by NTMS2017** [comment]
**@Clashkid155 thanks,** read the documentation and made it.

before I use get, I parse the my http link using Uri.parse.

```
final _myUri = Uri.parse('https://www.google.com/');
var _response = await http.get(_myUri, headers: {'Accept': 'application/json'});
```
