### ISSUE TITLE
when i am use http package in my app it show me error regarding String cann't assign in Uri

### ISSUE THREAD

**Issue by lkrjangid1** [dart-lang/http#537]
when i am use http package in my app it show me error regarding String cann't assign in Uri

![image](https://user-images.githubusercontent.com/64513385/110341274-2c114380-8050-11eb-9a99-91a0fe8440ed.png)

**Comment by TanveerAbbax** [comment]
i have also same issue

**Comment by andrewpmoore** [comment]
Making the change to our code was simple enough, but we've now run into the issue that all the libraries we use that haven't yet been updated to null safety won't build as we've had to override the dependencies.

Is there any way around this without doing PR's on all the external libraries?

**Comment by natebosch** [comment]
> Is there any way around this without doing PR's on all the external libraries?

No. There is no way to update for a breaking change in a dependency without changing the source code.

**Comment by andrewpmoore** [comment]
Thanks @natebosch I assumed that was the case. Time to contribute to a few libraries.
