### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by EngineerDanny** [dart-lang/http#538]
I updated my `http` package to the latest version which is `0.13.0`. I read the documentation and used it my code.
I had this error "The argument type `String` can't be assigned to the parameter type `Uri`. "
To my surprise, I found out that the documentation was outdated.
There is a breaking change in version  `0.13.0` which warns us to use a `Uri` object to replace the `Uri` string when making a request.

<img width="841" alt="Screenshot 2021-03-10 at 7 37 42 PM" src="https://user-images.githubusercontent.com/47421661/110687129-175fb780-81d8-11eb-82a1-bf3901b60e5b.png">

**Comment by javierbm7** [comment]
Hi @EngineerDanny , in my case I did  used this way: 

var url = 'https://example.com/whatsit/create';
Uri _uri = Uri.parse(url);
var response = await http.get(url);

Or Another way is follow this example:  https://pub.dev/packages/http/example

**Comment by lfbrunke** [comment]
Or use something like this:

Uri url = Uri.http('https://example.com', '/what',  {"language" : "dart"});

for: http://example.com/what?language=dart

**Comment by EngineerDanny** [comment]
Yes. I had to rewrite all my `http` requests using  `Uri.parse(url)` to replace `url` which was initially a `string`.

**Comment by natebosch** [comment]
A version with updated README has been published.

https://pub.dev/packages/http/versions/0.13.1
