### ISSUE TITLE
Need null safety support

### ISSUE THREAD

**Issue by andzejsw** [dart-lang/http#540]
Current latest http doesn't support "Flutter 2.0" null safety logic. This needs to be fixed, else not possible to use this feature for app and all other packages.

**Comment by arteevraina** [comment]
Hey @andzejsw ! It's already null-safe I guess. 
![image](https://user-images.githubusercontent.com/43968121/111025854-f59b4600-840c-11eb-915f-081755ec0ba0.png)
Check here :
https://pub.dev/packages/http/changelog

**Comment by natebosch** [comment]
Please upgrade to ver `0.13.0` for null safety.
