### ISSUE TITLE
With the new version 0.13.0 i can't make http request using localhost

### ISSUE THREAD

**Issue by FelipeCabeza16** [dart-lang/http#548]
Before the 0.13.0 version i had
`String url = 'http://192.168.1.2:3000'; //My ipv4, with localhost:3000 doesn't work or 127.0.0.1:3000`
`final res = await http.post(
        '$url/domiciliary/login',
        headers: {"Content-Type": "application/json"},
        body: body
      );`

`final res = await http.post(
        Uri.http('$url', '/domiciliary/login'),
        headers: {"Content-Type": "application/json"},
        body: body
      );`
But when i'm trying to migrate i have the following exception:
**StateError (Bad state: Insecure HTTP is not allowed by platform: http://192.168.1.2:3000/domiciliary/login)**

And when i try with the same but with Uri.https i have the following
**HandshakeException: Handshake error in client (OS Error: 
WRONG_VERSION_NUMBER(tls_record.cc:242)))**

Now i need to configure clear traffic with http on my manifest to continue with the dev part

**Comment by arthuRHD** [comment]
I get the same output when querying with http scheme.
The state error raised if from `_HttpClient._openUrl` from `dart:_http/http_impl.dart:2435:7`.

**Comment by ASVKVINAYAK** [comment]
I am also facing the same problem can anyone telp me what should i do 

android:networkSecurityConfig="@xml/network_security_config"
android:usesCleartextTraffic="true"

where my network_security_config flie contains 

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>


i even added these lines in androidmanifest file but also got the same error

Can anyone suggest what to do it would be helpful

**Comment by EgHubs** [comment]
Is [this](https://github.com/dart-lang/http/issues/550) might be related, please?

**Comment by yakirifrah** [comment]
@FelipeCabeza16 @ASVKVINAYAK I get the same error too, Were you able to find a solution to this, I stack with it??😞

**Comment by ASVKVINAYAK** [comment]
@FelipeCabeza16  I tried but didn't get any answer so my team hosted the  api on heroku
And it solved the problem
So try to host the api on any platform which provides https (I used heroku)
This will help you

**Comment by natebosch** [comment]
Internet permission issues are unrelated to this package and it's version.

You should be able to use `HttpClient` from `dart:io` to verify that the issues arise without use of this package at all.

See https://github.com/flutter/website/issues/3592 - please as the flutter team for help with mobile specific questions about networking and permissions.
