### ISSUE TITLE
[Error] the Content-Length header occurred more than once, at most one is allowed.

### ISSUE THREAD

**Issue by EgHubs** [dart-lang/http#550]
when i try to connect over the following link:
` http://192.168.4.1/wifisave?s=asdasd&p=10001010101010&ip=192.168.1.202&gw=192.168.1.1&sn=255.255.255.0&email=new@test.com&pass=123456789&alarm=1`
I get the following error

> The Content-Length header occurred more than once, at most one is allowed.

even thought it was working before, I don't know if the upgrade of the latest version of the library did affect that..
the line of code:
```
try {
String overAllLink='http://192.168.4.1/wifisave?s=asdasd&p=10001010101010&ip=192.168.1.202&gw=192.168.1.1&sn=255.255.255.0&email=new@test.com&pass=123456789&alarm=1';
    response = await http.get(Uri.parse(overAllLink));
  } catch (e) {
    print(e);
  }
```

**Comment by LucasAschenbach** [comment]
I'm getting the same error message.
@EgHubs Did you find a solution for this problem?

**Comment by EgHubs** [comment]
Unfortunately no, i'am stuck in here

**Comment by LucasAschenbach** [comment]
@EgHubs In your http request, is the content-length field in the response spelled out `'Content-Lenght'` or `'content-length'`?

(I have been testing a few different APIs, all of which worked fine. However, they all spelled content-length with lower-case letters whereas the API which causes the exception spells it with capital `C` and capital `L`.)

**Comment by EgHubs** [comment]
If you mean how I get the error message I get it in the same way that I have referenced, with capital letters.

**Comment by LucasAschenbach** [comment]
For instance, here is a response where the content-length field-name is written with lower case letters:

```
StatusCode: 200, ReasonPhrase: '', Version: 3, Content: {
  "args": {}, 
  "headers": {
    "Accept-Encoding": "gzip, deflate", 
    "Cache-Control": "no-cache", 
    "Content-Length": "0", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-607574e7-7b8854500cab78fb48eedeae"
  }, 
  "origin": "88.69.152.24", 
  "url": "https://httpbin.org/get"
}
, Headers:
{
  server: gunicorn/19.9.0
  date: Tue, 13 Apr 2021 10:39:35 GMT
  access-control-allow-credentials: true
  access-control-allow-origin: *
}{
  content-length: 359  // <-- lower case
  content-type: application/json
}
```

When you make the API request with a different client (e.g. Windows's ApiTester) is that field-name spelled out `content-length` or `Content-Length`?

**Comment by LucasAschenbach** [comment]
I just changed my method of authentication and now everything works. Before, I was using 'Basic' authentication; now I'm using a custom method.

I'm assuming, when the server requests the username and password with its 401 response, it already sets a content-length for the response and then again, when sending the actual response.

**Comment by EgHubs** [comment]
Will, I have no authentication method on this server to consider, the thing is the request that I am trying to do is done successfully on google chrome on any device, also when I try with flutter here the server receives the request, but flutter throws this error. 
when I tried to test it with an API tester like you mentioned this is what I get:
```
> Host: 192.168.4.1
> User-Agent: insomnia/2021.2.2
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Accept: */*
> Content-Length: 25

| --X-INSOMNIA-BOUNDARY--

* We are completely uploaded and fine
* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Content-Type: text/html
< Content-Length: 1210
< Content-Length: 1210 //second one.
< Connection: close

```

a capital letter, but what I noticed here is I receive two Content-Length in the response, which didn't happen on any other site. i think the problem here is in my server here, but how can I ignore this error? it was never there!

**Comment by EgHubs** [comment]
Alright, it was an issue with the server-side, the server was sending the Content-Length twice.
Thank @LucasAschenbach for pointing out the API tester idea
Solved [here](https://github.com/tzapu/WiFiManager/issues/1235)
