### ISSUE TITLE
The getter 'calawait' isn't defined for the class 'IOClient'

### ISSUE THREAD

**Issue by supardyke** [dart-lang/http#561]
pub-cache/hosted/pub.dartlang.org/http-0.13.1/lib/src/io_client.dart:30:24: Error: The getter 'calawait' isn't defined for the class 'IOClient'.
 - 'IOClient' is from 'package:http/src/io_client.dart' ('pub-cache/hosted/pub.dartlang.org/http-0.13.1/lib/src/io_client.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'calawait'.
      var ioRequest = (calawait _inner!.openUrl(request.method, request.url))
                       ^^^^^^^^

**Comment by natebosch** [comment]
Looks like you have a typo somewhere in your code. `calawait` has never appeared in this package.

**Comment by natebosch** [comment]
Or maybe you tried editing a file in the pub cache? `pub cache repair` or `flutter pub cache repair` should resolve that.
