### ISSUE TITLE
Request Error in Flutter Web

### ISSUE THREAD

**Issue by LenniCodes** [dart-lang/http#563]
The package works fine for Flutter for Windows etc but as soon as i want to connect to my api with Flutter Web, id get "XMLHttpRequest error".. im very sure its not my fault; I really just tried the exact same code for the two different platforms.

**Comment by admedina** [comment]
I had the same problem.  Cors was the issue for me.  Try starting up with an allowed port with `--web-port 9999` or whatever port your server allows.

**Comment by natebosch** [comment]
Look in your browse console for errors. You might need to adjust headers on your server to allow these responses.
