### ISSUE TITLE
Json with list inside an object throws an error 

### ISSUE THREAD

**Issue by igloo12** [dart-lang/http#569]
Hi I am posting json like this 

```
   final res = await http.post(
        Uri.http("${getApiHost()}", "${getApiBasePath()}/final"),
        headers: {
          'Content-type': 'application/json',
          'Accept': 'application/json',
        },
        body: '{"transactionChanges":[{"id":"2","billCode":"P"}]}',
      );
```
I am getting the error `FormatException: SyntaxError: Unexpected token i in JSON at position 1 `

If I remove the list in transactionChanges to something like `'{"transactionChanges":{"id":"2","billCode":"P"}}'` the error goes away. The json above is valid I am able to send it via postman

Note it also works if the list is the outside object `'[{"test":"test"}]',` but not if the list is inside

Using library version 0.13.3
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (3 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

EDIT 1:
I took a quick peek at the source code was able to get it to work using the style of the json tests
```
      var jsonVal = json.encode(FinalRequest(changesAsList));
      log(jsonVal);
      var client = http.Client();
      final request = http.StreamedRequest(
          'POST', Uri.http("${getApiHost()}", "${getApiBasePath()}/final"))
        ..headers[HttpHeaders.contentTypeHeader] =
            'application/json; charset=utf-8'
        ..headers[HttpHeaders.userAgentHeader] = 'Dart';
      var responseFuture = client.send(request);
      request
        ..sink.add(jsonVal.codeUnits)
        ..sink.close();

      var res = await responseFuture;
      var body = await res.stream.bytesToString();
```

**Comment by natebosch** [comment]
Where is the `FormatException` throw from? Can you paste a stack trace?

**Comment by igloo12** [comment]
@natebosch I tried to switch back to the code that was failing before but it seems to be working now not sure what changed maybe a cache error? Closing for now
