### ISSUE TITLE
Dependency on dart:io

### ISSUE THREAD

**Issue by parnham** [dart-lang/http#57]
The latest update `0.11.3+10` which removes the mirrors dependency, adds a dependency to "dart:io" which the BrowserClient can see (via BaseClient -> Client -> IOClient). Whilst it still works when compiled to javascript, when running in Dartium it throws the following error:

```
The requested built-in library is not available on Dartium.'package:http/src/io_client.dart': error: line 6 pos 1: library handler failed
import 'dart:io';
^: package:http/src/io_client.dart
```

**Comment by matanlurey** [comment]
Have you updated your version of Dartium? I believe you need a version that has the `1.22.0` VM.

**Comment by parnham** [comment]
That was my first thought also :) 
Have just double checked and I am running `dartium-linux-x64-stable-1.22.0.0`  and still getting the error I'm afraid.

**Comment by parnham** [comment]
I just pulled `1.23.0` instead and our application is working again.

**Comment by matanlurey** [comment]
Thanks! Looks like we need to up the pubspec, it's not accurate.
