### ISSUE TITLE
How I can get response data when calling multipart post request ?

### ISSUE THREAD

**Issue by aniketsongara** [dart-lang/http#573]
Sample code is here 

```
 final request = http.MultipartRequest('POST', Uri.parse("your_server_url"));
          request.files.add(http.MultipartFile.fromBytes("file", file.bytes, filename: file.name)); //your server may require a different key than "file"
          final response = await request.send();

// Now I want to get response data, How can I get it ?

if (response.statusCode == 200) {
         print("Response : ${response.body}"); // here I want to print the response.
          }

```

**Comment by steinmetz** [comment]
@aniketsongara  you can use like this:
`final respStr = await response.stream.bytesToString();`

then `respStr` will contain the "response"

**Comment by edwinmrb** [comment]
@aniketsongara  or you can use this:
http.Response response = await http.Response.fromStream(await request.send());
( json.decode(response.body) as Map<String, dynamic>)

**Comment by DhleimaMohamed** [comment]
var response = await request.send();
var responseData = await response.stream.bytesToString();
final decodedMap = json.decode(responseData);

The decodedMap contains response the "json format of response"
