### ISSUE TITLE
YOU CHANGED THE API!!

### ISSUE THREAD

**Issue by chornbe** [dart-lang/http#574]
http.get( STRING, .... ) is now http.get( Uri, .... )

YOU NEVER CHANGE AN EXISTING API SIGNATURE! YOU CREATE A NEW FUNCTION.

This is seriously a HUGE problem. HUGE. 

Who is running your QA and deployments? This is entirely unacceptable.

**Comment by natebosch** [comment]
Packages on pub use [semantic versioning](https://dart.dev/tools/pub/versioning#semantic-versions) to indicate breaking changes.

You can use constraints in your pubspec to prevent picking up new package versions with breaking changes until you are ready for them.

**Comment by chornbe** [comment]
Which doesn't help one bit when ImagePicker relies on later versions and the previous versions had show-stopping bugs which necessitate and upgrade. 

DUDE! Why does no one in open source software understand the contract promise of using an API!?!??

you should (have) updated the library with .getUri(....) and deprecate-warn on .get (and other verbs).

Seriously, this is NOT how it's done, man. After 30 years of this stuff, I've already lived through all this "breaking changes" due to not understanding the importance - THE UNDENIABLE AND NECESSARY IMPORTANCE - of NEVER breaking an API call by changing it. YOU ADD. YOU DO NOT REPLACE.
