### ISSUE TITLE
BrowserClient: Listener leak

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/http#586]
Hey, I have created a simple dart web app however there is a leak which I've tracked down to the `BrowserClient`. It's increasing the number of Listeners in the DOM every http request. My web app is running on a low powered device (Amazon Kindle) and it's causing it to crash after a while due to this leak.

## Browser Performance Profile:
[Profile-20210625T094952.zip](https://github.com/dart-lang/http/files/6714869/Profile-20210625T094952.zip)
![image](https://user-images.githubusercontent.com/298850/123398065-08402200-d59b-11eb-9fb3-440957818a88.png)

## The code

Problematic code ([see actual code here](https://github.com/jimmyff/crypto-clock/blob/2d849d95f32d9ebea98bbbda37c570389c1a759f/web/main.dart#L209)):
```dart
    try {
      var response = await client.get(Uri.parse(
          'https://api.binance.com/api/v3/ticker/24hr?symbol=${symbol['symbol']}'));
      data = json.decode(response.body);
    } finally {
      client.close();
    }
```

Mocking the HTTP request & response completely resolves the listener leak:

```dart
    try {
      data = json.decode(
          '{"symbol":"BTCUSDT","priceChangePercent":"${Random().nextInt(7)}","lastPrice":"${Random().nextInt(2000)}"}');
    } finally {
      client.close();
    }
```

## Testing

You can [test the web page here](https://jimmyff.github.io/crypto-clock/). I suggest setting the update interval to 5 seconds which means you will see more requests and this will make the leak easier to spot. To do this click/tap in the central column and change update interval to 5 then save.

**Comment by mraleph** [comment]
DevTools recording is misleading you - there is no actual leak, but listener counter grows because there are no major GCs occuring. If you trigger them manually (e.g. via trash-can icon next to "Web Vitals" check box) you will see the listener count dropping down.
