### ISSUE TITLE
Memory allocation issue on GET request Base64 image

### ISSUE THREAD

**Issue by ObranS** [dart-lang/http#592]
On GET requests I found issue that cause memory allocation but never releases that. In that case periodical request cause memory usage of GBs and kill application with memory issue. I found a code part in **http: 0.13.3** lib which allocates memory but not release:

Unfortunately I couldn't find exact issue code but current code part cause the problem. 
At least when I comment this code line on Base64 request memory allocation won't increase allocation amount.

/// Creates a new HTTP response by waiting for the full body to become
  /// available from a [StreamedResponse].
  static Future<Response> fromStream(StreamedResponse response) async {
    // >>> This line allocate memory
    final body = await response.stream.toBytes();
    // issue reproduces even if body not assigned into response
    return Response.bytes(body, response.statusCode,
        request: response.request,
        headers: response.headers,
        isRedirect: response.isRedirect,
        persistentConnection: response.persistentConnection,
        reasonPhrase: response.reasonPhrase);
  }

Screenshots:

Enabled code line:
<img width="1667" alt="Screenshot 2021-07-06 at 13 58 06" src="https://user-images.githubusercontent.com/5585509/124590518-e597ee00-de63-11eb-92a2-be2027fff833.png">

Disabled code line:
<img width="1660" alt="Screenshot 2021-07-06 at 14 04 35" src="https://user-images.githubusercontent.com/5585509/124590538-eaf53880-de63-11eb-9383-ce0e8a79fba2.png">

❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/newfire/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/newfire/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPad (mobile) • ce0f26bcbaf255e35ccd434298a3344c08bf5f19 • ios
      • iOS 14.6
    • Chrome (web)  • chrome                                   • web-javascript
      • Google Chrome 91.0.4472.114

**Comment by ObranS** [comment]
Any updates on this?

**Comment by natebosch** [comment]
Do you have a complete reproduction case? I haven't seen any other reports of leaking references to the downloaded bytes.

Are you holding leaking a reference to the data in whatever code is handling the response?

**Comment by ObranS** [comment]
> Do you have a complete reproduction case? I haven't seen any other reports of leaking references to the downloaded bytes.
> 
> Are you leaking a reference to the data in whatever code is handling the response?

Nope, I commented everything for except 
final body = await response.stream.toBytes();

Steps to reproduce is easy:
GET request with Base64 encoded image in response

**Comment by natebosch** [comment]
> Steps to reproduce is easy:

I'm not able to reproduce it.

Here is my code:

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;

void main() async {
  while (true) {
    var result = await http.get(Uri.http('localhost:9090', ''));
    var decoded = base64Decode(result.body);
    print(decoded.last);
  }
}
```

and here is my server

```dart
import 'dart:convert';
import 'dart:io';
import 'dart:math';

void main() async {
  var server = await HttpServer.bind('localhost', 9090);
    server.listen((request) async {
    request.response.headers.add('Access-Control-Allow-Origin', '*');
    request.response.write(base64Encode(_randomBytes));
    await request.response.close();
  });

}

final _random = Random();
List<int> get _randomBytes =>
    List.generate((1024 * 1024 * 10), (_) => _random.nextInt(255));
```

This simulates making lots of requests for base64 encoded data and decoding it back. The data is 10 MB and about 14 MB when encoded in base64.

I can run this for a while and I don't see any rise in memory usage in the browser devtools. On my browser the memory usage quickly reaches 22.5MB (for DDC or dev mode) or 11.8 MB (for dart2js or production mode) and then stays around there.

**Comment by natebosch** [comment]
Ah, I was able to reproduce this after attaching devtools. Looks like a bug in the VM or devtools.

**Comment by natebosch** [comment]
Filed https://github.com/flutter/devtools/issues/3290

**Comment by ObranS** [comment]
> Ah, I was able to reproduce this after attaching devtools. Looks like a bug in the VM or devtools.

Unfortunately Xcode Profile reports bytes allocation too. After long investigation seems it is Dart and Garbage Collector specific.
