### ISSUE TITLE
Unable to pass Map<String,dynamic> data as body in http.MultipartRequest

### ISSUE THREAD

**Issue by arslankaleem7229** [dart-lang/http#594]
I want to `POST` data to API with file using `http.MultipartRequest `but it is limiting the data type to `String` means I can only push the body data in form of `Map<String,String>` but here in API data is dynamic mean it has `double` , `int` , `bool` and `String` type data. Here is the code
```

var request = http.MultipartRequest('POST', Uri.parse(addimageUrl))
      ..fields.addAll(body)
      ..headers.addAll(headers)
      ..files.add(await http.MultipartFile.fromBytes(
          'cover_image', file.readAsBytesSync()));

    var response = await request.send();
```

**Comment by natebosch** [comment]
This package does not want to make decisions about how to represent non-String data types within the request, so you need to make those decisions in your application code. In some cases `.toString()` might be sensible, in other cases something like `jsonEncode` may be more sensible.

If you want to use `.toString()` to convert to a String you can use `body.map((name, value) => MapEntry(name, '$value'))`. That way you are explicit about how you expect non-String values to be handled.
