### ISSUE TITLE
Why can't my body be an array of objects?

### ISSUE THREAD

**Issue by LautaroLobo12** [dart-lang/http#598]
Hi!

I'm trying to make a POST request with a body that looks like this:

```
[
  {
    "id": "9032",
    "name": "Carlomagno",
    "origin": "web"
  }
]
```

Right now is just one object inside the array, but in the future I'm expecting to make a request with more than one object, and getting an array of objects in response.

And I'm getting an Exception, which I don't understand (neither do my teammates at work 😅), saying : `_TypeError (type '_CastError' is not a subtype of type 'int')`.

My `catch(e)` has an `_errorMsg` saying: `"type '_InternalLinkedHashMap<String, String>' is not a subtype of type 'int' in type cast"`, and `_url` saying: `"dart:_internal/cast.dart"`.

I'm guessing that there's some sort of map or forEach inside the http package that can't do it's work if you give him an array instead of an object.

Anyways, why can't my body be an array of objects? And if someone can explain to me why that Exception is being thrown, an what does it mean, that would be really appreciated.

And if you need more info, lemme know.

Thank you for time!

**Comment by natebosch** [comment]
> "type '_InternalLinkedHashMap<String, String>' is not a subtype of type 'int' in type cast"

I'm not sure where we would cast to `int` in this package.

Try adding a `StackTrace` argument to your `catch`. It should point you somewhere in your code where you have a cast.

> Anyways, why can't my body be an array of objects?

See the docs for the `body` argument.

https://pub.dev/documentation/http/latest/http/post.html

The most reliably approach is to convert to the `List<int>` of bytes yourself, but in this case if you are looking to send encoded JSON you could `jsonEncode` the list and pass the resulting String as the `body`.
