### ISSUE TITLE
Problems on the latest version of http package (1.13.3)

### ISSUE THREAD

**Issue by V1t0n3** [dart-lang/http#600]
when I try to run my app on iOS and Android, Simulator and physical, i cannot because of this error:

../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/src/io_client.dart:61:7: Error: Can't find ')' to match '('.
          (throw ClientException(error.message, error.uri);
          ^

I found this issue yesterday, after many successful builds, improvisely didn't work anymore. Kept searching since now, when i used an older version of http and then worked.

**Comment by natebosch** [comment]
There is no `(` on that line in the published version of this package.

https://github.com/dart-lang/http/blob/798aad1cb9407fbf0db5b65c21f32b3ca936574b/lib/src/io_client.dart#L61

You made edits in your local copy of the package in the pub cache. You might be able to use `flutter pub cache repair` to fix it.
