### ISSUE TITLE
Accessing partial download data via StreamedRequest does not seem to work on web

### ISSUE THREAD

**Issue by BananaNeil** [dart-lang/http#631]
I implemented the code in this Stackoverflow answer: https://stackoverflow.com/a/61021018/937841

And on the web, I found that `_response = await http.Client().send('GET", ...)` seems to download the entire file before advancing. 

The callback passed to `_response.stream.listen( ... )` only gets called once with the entire file downloaded, and then `onDone` is called immediately - this makes it impossible to add a progress loader with incremental download percentages. 

On macos, I see the incremental download percentages with no issue.

**Comment by natebosch** [comment]
Feature request for supporting streaming downloads on the web is at https://github.com/dart-lang/http/issues/595
