### ISSUE TITLE
library 'package:http/http.dart' is legacy

### ISSUE THREAD

**Issue by zzj0402** [dart-lang/http#632]
I tried to follow example from 
https://pub.dev/packages/google_sign_in/example .

But I run into the following error
```
The library 'package:http/http.dart' is legacy, and should not be imported into a null safe library.
Try migrating the imported library.
```

**Comment by karen1au** [comment]
http v0.13.4 requires Dart 2.14, either set 2.14 for your environment or lower http package to v0.13.3 would remove the warning

**Comment by natebosch** [comment]
You can update to the latest `http` package to get a null safe version.

Versions starting at `0.13.0` are null safe.

**Comment by Ismailov773** [comment]
> You can update to the latest `http` package to get a null safe version.
> 
> Versions starting at `0.13.0` are null safe.

dalbayeb
