### ISSUE TITLE
Implement HTTP over Unix domain sockets

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/http#636]
This has been [requested for the Dart core](https://github.com/dart-lang/sdk/issues/42716) but it seems like the http package would be a better home for it.

Would you be open to accepting a pull request that adds a `HttpUnixClient` (a `BaseClient` subclass)?

**Comment by natebosch** [comment]
I don't know how we'd implement something like this without support form the SDK. I imagine we'd need to use `ffi`?

I don't think that this package is an appropriate place to use `ffi` - it aims to be cross platform.

I'd recommend putting something like this into a separate package. It can still implement `Client` for compatibility.
