### ISSUE TITLE
unhandled exception: type 'string' is not a subtype of type 'uri'

### ISSUE THREAD

**Issue by youcef-mo** [dart-lang/http#643]
I have this problem when I try to use http.get(url) method , it is work fine on web but in android it is show me this error :
"unhandled exception: type 'string' is not a subtype of type 'uri' ",
I try to solve it using this method Uri.parse() , but it doesn't work .

**Comment by jenishpatel07** [comment]
FormatException (FormatException: Scheme not starting with alphabetic character (at character 1)
 https://reqres.in/api/products/1

**Comment by youcef-mo** [comment]
I solved this by adding a null check in my fromMap() function : 
` json[data]["image"] ?? " " `
But I don't know why it's work in web without it
