### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by ielb** [dart-lang/http#644]
Getting this error when using  a post method 
this is TrackTrace : #0      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:25)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#2      CastMap.forEach (dart:_internal/cast.dart:287:13)
#3      mapToQuery (package:http/src/utils.dart:17:7)
#4      Request.bodyFields= (package:http/src/request.dart:137:12)
#5      BaseClient._sendUnstreamed (package:http/src/base_client.dart:87:17)
#6      BaseClient.post (package:http/src/base_client.dart:32:7)
#7      post.<anonymous closure> (package:http/http.dart:69:16)
#8      _withClient (package:http/http.dart:164:20)
#9      post (package:http/http.dart:68:5)
#10     Api.httpPost (package:knorrieplay/services/api.dart:33:14)
#11     UserService.addUser (package:knorrieplay/services/user_service.dart:8:18)
#12     AuthProvider.signInWithFacebook (package:knorrieplay/providers/auth_provider.dart:219:23)
<asynchronous suspension>
#13     _LoginPageState.facebookAuth (package:knorrieplay/pages/login_page.dart:89:18)
<asynchronous suspension>
 the method i used 
  Future<http.Response?> httpPost(String endPath, Object body) async {
    try {
      Uri uri = Uri.parse('$url$endPath');
      return http.post(uri, body: body, headers: headers);
    } catch (e) {
      print(e);
    }
  }

::::::::::: when i use dio it works fine

**Comment by natebosch** [comment]
The doc comment on `http.post` says: 

> `body` sets the body of the request. It can be a `String`, a `List<int>` or a `Map<String, String>`.

You have pass a `Map` which contains a value that is `null`, which is not a `String`.
