### ISSUE TITLE
Feature request: support SOCKS proxies

### ISSUE THREAD

**Issue by isoos** [dart-lang/http#65]

**Comment by nex3** [comment]
The `http` package is designed to be composable and to make it easy to make middleware that add special functionality or implement a new way of sending requests. This is a great example of something that would work well as middleware.

**Comment by isoos** [comment]
It is not immediately clear for me how this could be achieved as a middleware. Could you please leave pointers here, so that later it can be picked up by somebody?

**Comment by nex3** [comment]
Maybe a custom client would work better than middleware? I don't know a lot about the SOCKS protocol. But however you were envisioning it being implemented in this package, you could implement elsewhere.

**Comment by isoos** [comment]
I was thinking more of `curl`, which has a `--socks5` command line flag. For example node.js has this http client library that was specifically built for socks support: https://github.com/mattcg/socks5-http-client

I am not that familiar with the socks protocol either, but given the examples, it feels it belongs to the http client. Btw. this is one of last remnants on my server which is using external process (`curl`) instead of dart-only libraries.

**Comment by nex3** [comment]
This library isn't intended to include support for every protocol; it's intended to be a solid foundation on which that support can be added externally.

**Comment by wuujiann** [comment]
Can you give me a pointer on how to add SOCKS proxy support externally to this http package?
