### ISSUE TITLE
package:http missing docs on dartdocs.org

### ISSUE THREAD

**Issue by abarth** [dart-lang/http#66]
## Steps to reproduce:

1. Go to https://pub.dartlang.org/packages/http
2. Click the link under "Documentation" on the right

## Expected result

I expect to see the API docs for package:http

## Actual result

I get a 404.

## Analysis

https://www.dartdocs.org/documentation/http/0.11.3%2B12/ lacks API docs.  The most recent version with API docs appears to be 0.11.3+10:

https://www.dartdocs.org/documentation/http/0.11.3%2B10/

Perhaps this corresponded to the change in SDK requirements in package:http and dartdocs.org is using an old Dart SDK to generate the docs?

**Comment by mit-mit** [comment]
CC @kevmoo 

This is blocking an update to flutter.io as it causes our automatic link checker to report broken links.

**Comment by kevmoo** [comment]
Core issue: dartdocs.org is running 1.22.0 – latest pkg/http requires 1.23.0-dev

https://www.dartdocs.org/documentation/http/0.11.3+12/log.txt

**Comment by kevmoo** [comment]
See https://github.com/astashov/dartdocs.org/issues/42

**Comment by nex3** [comment]
Looks like this is fixed.
