### ISSUE TITLE
上传图片到aliyunOss会出现The body of your POST request is not well-formed multipart/form-data错误

### ISSUE THREAD

**Issue by guohuake12** [dart-lang/http#676]
原因是因为在file域里面Content-Type在Content-Disposition之前，因此出现了该问题，oss这里是需要Content-Type在Content-Disposition之后才可以正常的。

0.13.3左右版本，MultipartRequest._headerForFile的Content-Type会在Content-Disposition之前。

把Content-Type和Content-Disposition顺序替换一下就正常了

**Comment by xia-weiyang** [comment]
@guohuake12  大佬，我也遇到这个问题了，请问你怎么处理的，如何Content-Type和Content-Disposition位置兑换下
