### ISSUE TITLE
HttpClient postUrl request appends non standard strings to headers

### ISSUE THREAD

**Issue by lowbit** [dart-lang/http#690]
When using post request, even if you set content type headers the normal way, library will overwrite application json content and add charset to it.

This is not how default library for flutter http requests should handle these requests, especially without ability to overwrite it (easily), the only solution to this that I found is this code:
```
final httpClient = HttpClient();
final request = await httpClient.postUrl(url);
request.headers.set('Authorization', 'Bearer ' + token);
request.headers.contentType = ContentType("application", "json");
// body
request.add(
  utf8.encode(
    jsonEncode(body),
  ),
);
final response = await request.close();
```

It shouldn't append charset to json encoding without giving user the choice, this is not a standard, therefor this is a bug.

**Comment by natebosch** [comment]
I'm guessing you are hitting the behavior called out in the docs for `Request.body`.
https://pub.dev/documentation/http/latest/http/Request/body.html

When you set the body as a `String` the `charset` parameter is always set for you. You may be able to work around this by setting the header after you set the body.
