### ISSUE TITLE
Undocument fail when execut post during app closing

### ISSUE THREAD

**Issue by ruscoff** [dart-lang/http#693]
Hi to All, 
   i'm experiance a strange behavior with http.post request during android app closing. If i put app on background it works always correctly but with pushing back button to close app sometimes 90% of times the request fail without reporting any exception, failure or response. 
Stepping into code i saw that code seems to exit on io_client.dart on code:  
var ioRequest = (await _inner!.openUrl(request.method, request.url))

This is my code where i put http call:

```
...
void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (   state == AppLifecycleState.inactive) {
               var response = await http.post(
        Uri.https(
          'www.ccccccc.it',
          'xxxxx/xxxxx.php/xxxx',
        ),
        headers: {
          HttpHeaders.authorizationHeader: 'Basic $DbUserCredentials',
        },
        body: {
          'xxxx': xxxxxx,
        });
```

How can i execute http post before app completly closing in a safe mode?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Versione 10.0.19043.1645], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by natebosch** [comment]
It looks like this question is more related to what happens when there are outstanding requests and the app is closed with the back button.

I can't transfer issues to the flutter repository from here - can you reopen this issue at https://github.com/flutter/flutter/issues with more details and clarify what you mean by

> 90% of times the request fail without reporting any exception, failure or response.

what is the behavior you observe when it "fails" without an exception?
