### ISSUE TITLE
Requests 2x slower than in Postman or Web ?

### ISSUE THREAD

**Issue by lukaskurz** [dart-lang/http#723]
## Problem

I was just debugging the performance of my flutter app and noticed that requests sometimes take very long.
For example, a specific request takes about 100ms to complete, when testing it through my website ~ i.e. javascript and 130ms when testing it with Postman. However in my app this request sometimes took over 6000ms (when running in debug mode). When changing to profile mode this improved significantly, but still averaged 200-300ms.

I was wondering whether this is just typical mobile behaviour and this performance is to be expected, or whether there maybe is something in the http library/dart that is slowing things down a bit in comparison.

**Comment by ArbazShaikh077** [comment]
Facing the same issue.

**Comment by ash-hashtag** [comment]
yeah mine even taking 6 secs in flutter, on postman I get them in 200-400 ms, Are there any other packages that can be used?

**Comment by natebosch** [comment]
I'm not aware of any implementation issues that cause arbitrary requests to slow down.

Is it possible the issue is on the server side?

Without a specific reproduction case I can observer, there unfortunately are no actions we can take on this issue.

**Comment by teddy-dubal** [comment]
Hi guys , i'm facing the same issue , did you found a solution ?

**Comment by arrahmanbd** [comment]
Having this issue on android 12 +

**Comment by PawanFyers** [comment]
Same issue with my project. Even if we are using cdn urls.

http takes 3-4 seconds
whereas postman takes only 63 milliseconds.

**Comment by joaomarcosribeiroc** [comment]
Same issue here. Using http library. In insomnia I have 45-60ms but in flutter app in debug mode, 400ms to 500ms
