### ISSUE TITLE
SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64

### ISSUE THREAD

**Issue by sitakanta136** [dart-lang/http#729]
Connection failed (OS Error: Machine is not on the network, errno=64)
- Change wi-fi network, are facing this issue.

Case 1:  
 Connect to  Wi-fi network (ex- Situ Wifi) => try to login => Login successfuly
- [InternetAddress('142.250.199.174', IPv4), InternetAddress('2404:6800:4009:82e::200e', IPv6)]
Case 2:
   change wi-fi connection => Connected with IOT devices => try to login => Login Failed
Case 3:
 Change to Previous connected (Situ Wi-Fi ) => Now ,
  http.post() =>SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64.
  Don't know what going on .
 If check youtube, login in the browser, All working fine.

**Comment by sitakanta136** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = login.parker.com, port = 443
E/flutter (12143): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (12143): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
E/flutter (12143): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (12143): #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
E/flutter (12143): #4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
E/flutter (12143): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449:26)
E/flutter (12143): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
E/flutter (12143): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
E/flutter (12143): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
E/flutter (12143): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2591:7)
E/flutter (12143): #10     IOClient.send
package:http/src/io_client.dart:35
E/flutter (12143): #11     BaseClient._sendUnstreamed
package:http/src/base_client.dart:93
E/flutter (12143): #12     BaseClient.post
package:http/src/base_client.dart:32
E/flutter (12143): #13     post.<anonymous closure>
package:http/http.dart:69
E/flutter (12143): #14     _withClient
package:http/http.dart:164
E/flutter (12143): #15     post
package:http/http.dart:68

**Comment by osa1** [comment]
This doesn't look like an `http` bug. Please feel free to re-open with a reproducer and an explanation on why you think this is an `http` library bug.

**Comment by sitakantasundaray** [comment]
Can you tell me what is the issue? Why did you close this issue? Are you identify the root cause of the issue?

**Comment by osa1** [comment]
> Can you tell me what is the issue?

@sitakantasundaray you should provide us a reproducer (i.e. a Dart code that we can run and observe the problem you're observing), and tell us why it doesn't work the way you expect and why you think it's a problem with the `http` library.
