### ISSUE TITLE
Performing http.get to download Files increases Memory usage

### ISSUE THREAD

**Issue by cal-g** [dart-lang/http#735]
### Problem
Doing a `http.get` to fetch a 60kB file multiple times increases memory usage over time and does not decrease. 

The below code is run in a dart application and performs a total of 100 get requests.
```dart
import 'package:http/http.dart' as http;

void main(List<String> arguments) async {
  for (int i = 0; i < 10; i++) {
    print('\n  loop :$i');
    for (int j = 0; j < 10; j++) {
      await networkRequest();

      print('network call done  :$j');
    }

    await Future.delayed(Duration(seconds: 1));
  }
}

Future<void> networkRequest() async {
  await http.get(
    Uri.parse(
      'https://filesamples.com/samples/document/pdf/sample2.pdf', //~60kB
    ),
  );
}
```

### Memory snapshot:
<img width="1489" alt="Screen Shot 2022-07-21 at 5 14 47 PM" src="https://user-images.githubusercontent.com/98470469/180316916-9e43e746-f12f-4702-86a3-709a6bd5c8a3.png">

I'm using this package in my Flutter application and downloading 500+ such images on a low RAM device such as iPhone 8 which has only 2GB RAM crashes the application because the heap space gets exhausted.

**Comment by natebosch** [comment]
I don't see a monotonically increasing memory usage when I run this and check the memory usage externally.

Are you able to observe an increasing memory usage when you don't have devtools attached?

I can't find the previous conversation (It might have been @bkonyi who helped me last time?) but I recall that the network tab in devtools can cause memory retention, but I recall for sure if that was in the VM process or the devtools process. Can you try opening the network tab and clearing any cached requests?

**Comment by cal-g** [comment]
Thanks @natebosch  you're right, it's the network tab in devtools that causes the memory bloat. Clearing the requests in the network tab and forcing the GC  helps.
I should be closing this as I had later posted the same question in [dart-lang/sdk#49506](https://github.com/dart-lang/sdk/issues/49506).
