### ISSUE TITLE
Simple nested map in body throws cast exception

### ISSUE THREAD

**Issue by vishalkhedeker** [dart-lang/http#736]
```dart
var response = await http.post(
        Uri.parse(BASE_URL+"/fucntion/path"),
        headers: {
          'Accept': 'application/json',
          'authorization': 'Bearer $token'
        },
        body: {
          "key1":{
            "key2":"value"
          }
        }
    );
```

Above code throws [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type '_InternalLinkedHashMap<String, String>' is not a subtype of type 'String' in type cast

If i change it to body: { "key1" : "value" } it works. If i use jsonEncode i receive key1 value as string instead of object in nodejs.

**Comment by kartik-madhak** [comment]
Are you decoding the response in server when you are using jsonEncode? If yes, then you should get the same object that you sent...

**Comment by natebosch** [comment]
The doc states that the body can be a [String, List<String>, or a Map<String, String>](https://pub.dev/documentation/http/latest/http/post.html). A `Map<String, dynamic>` is not allowed.

You will need to manually encode the field in whatever way your server is expecting.

**Comment by guyluz11** [comment]
Same here
[Api](https://sensibo.github.io/#overview) of the product requires sending an object

See examples section

Turn on the AC curl -X POST https://home.sensibo.com/api/v2/pods/{device_id}/acStates?apiKey={api_key} -d "{\"acState\":{\"on\":true}}"
