### ISSUE TITLE
The requested built-in library is not available on Dartium.'package:http/src/io_client.dart'

### ISSUE THREAD

**Issue by damondouglas** [dart-lang/http#79]
Version `0.11.3+11` seemed to introduce this error.  How I suspect this is described below.

1.  Using `stagehand simple-web`, I scaffold a simple web application.
2.  I add `http: "0.11.3+9"` as a dependency and `import 'package:http/browser_client.dart';`
3.  The following code runs with no error:

```dart
main() async {
  var client = new BrowserClient();
  var response =
      await client.get('data.json');
  print('Response status: ${response.statusCode}');
  print('Response body: ${response.body}');
}
```

4.  Changing dependency to `http: "0.11.3+11"` and re-running `pub get` yields the following error in the Dartium console:
```
The requested built-in library is not available on Dartium.'package:http/src/io_client.dart': error: line 6 pos 1: library handler failed
import 'dart:io';
^: package:http/src/io_client.dart
```

**Comment by zoechi** [comment]
>=0.11.3+11 uses a new language feature that ignores `dart:io` imports in the browser.
It looks like you need a newer Dart version

**Comment by damondouglas** [comment]
The following are the versions of dart and Dartium.

```bash
$ dart --version
Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"
```
and Dartium: `Version 45.0.2454.104 (64-bit)`

Thank you, @zoechi for your help :)

**Comment by nex3** [comment]
I think you need to update your Dartium version.
