### ISSUE TITLE
cronet_http: depend on org.chromium.net:cronet-api instead

### ISSUE THREAD

**Issue by chengyuhui** [dart-lang/http#807]
The current implementation depends on `com.google.android.gms:play-services-cronet`, which pulls in the Google Play services. This might be undesirable for apps that do not want to have GMS code in them (and those who mainly target Chinese users and do not have GMS available).

We should depend on Chromium's API package, which will find the relevant dependencies automatically if they are declared. Additional documentations should be provided to the users on how to choose a Cronet provider (similar to https://exoplayer.dev/network-stacks.html#cronet).

**Comment by brianquinlan** [comment]
Hey @chengyuhui ,

So the idea is that:
1. cronet_http would depend on `com.google.android.gms:play-services-cronet`
2. the user would then have to depend on either `com.google.android.gms:play-services-cronet` or `org.chromium.net:cronet-embedded`.
3. the user would then create the appropriate `CronetEngine`

?

That seems like a lot of user complexity. I wonder if there is a way that we can use this one repo to release two packages: one with cronet embedded and one using play services?

**Comment by chengyuhui** [comment]
That's another valid idea, but might be difficult unless we are copying code around...

**Comment by brianquinlan** [comment]
Ideally, someone interested could create a fork of `cronet_http` and configure it to use `org.chromium.net:cronet-embedded`. That way users could pick the implementation that they want without having to deal with any complex configuration.

**Comment by AlexV525** [comment]
If the only difference in the implementation is importing and the `implementation` definition, it can be ideally done with different branches and setup a proper continue integration.
