### ISSUE TITLE
Pub release is outdated

### ISSUE THREAD

**Issue by DaveShuckerow** [dart-lang/http#81]
The latest release of this package on Pub (0.11.3+9) is very far behind the version of http used in Flutter (0.11.3+13), as well as the latest release available here on Github (0.11.3+13).

When will package:http be updated on Pub?

**Comment by nex3** [comment]
It looks to me that [0.11.3+13 was published on 30 March](https://pub.dartlang.org/packages/http).

**Comment by jakobr-google** [comment]
The latest versions of http require Dart SDK >= 1.23, so you might not get them if you're on an older Dart.

At least, I'm guessing that's the problem CrossDart has: https://www.crossdart.info/p/http/0.11.3+13/log.txt
