### ISSUE TITLE
How to use Streamed Response?

### ISSUE THREAD

**Issue by ash-hashtag** [dart-lang/http#810]
I can't figure out, A streamed response is only returned if we use a streamed request, So I tried to use a streamed request for just "GET" method, and I don't even understand how to send it,

```
  final request = http.StreamedRequest("GET", Uri.parse(url));

  final response = await request.send();
  print("did we reeaally send?...."); // It never gets past this and it didn't send I checked logs of the server

  response.stream.listen(doSomething)
```

What am I missing?

**Comment by brianquinlan** [comment]
I added a clarification in this PR: https://github.com/dart-lang/http/pull/813

Does that clarify the usage for you?
