### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)

### ISSUE THREAD

**Issue by Gugu04** [dart-lang/http#811]
**http: ^0.13.5**

It shows me this error with [namecheap](https://www.namecheap.com/) provider certificates. I did different tests with different domains and certificates with the same provider, but it still gives me the same error.

HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))

**Comment by ffigueroa0212** [comment]
I have the same issue

**Comment by Gugu04** [comment]
After doing several tests. The certificate settings were not configured correctly..
It is not an bug.

[Help guide to configure namecheap certificates](https://www.namecheap.com/support/knowledgebase/article.aspx/9419/33/installing-an-ssl-certificate-on-nginx/)
