### ISSUE TITLE
Mutual TLS support for Http Package

### ISSUE THREAD

**Issue by pranavpsawant** [dart-lang/http#822]
Hello,

I wanted to use flutter web client to make api calls to a server which requires me to provide client certificates. Although I was able to do the same using securityContext from dart.io package on iOS and Android, there is no option to do the same on web as io package is not supported on web.

Is there a way I can issue http requests with cert on flutter web ? This is blocking me from using flutter on web for my web based projects. Thanks.

I asked about the same in flutter channel, and was directed here as this seemed to be a http package function and not really a flutter web thing.

I can see axios JS lib supporting it based off the this link https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate, and thus was wondering what would it take for dart http package to support it as well.

**Comment by mraleph** [comment]
The quoted SO question is talking about nodejs browser. 

The capability you are asking for does not exist on the Web as an API. The only way for this to work is if certificate is installed into the system certificate storage by the user. In this case you can make browser to prompt user to provide a specific certificate when connection is established.

**Comment by pranavpsawant** [comment]
Pardon my understanding here, but is there a limitation as to why it doesn't exist ? How does a frontend service otherwise talk to the backend which has added layer of mTLS authentication ?

The setup I would like to have is:

1. User connects to the flutter frontend web server using some identity provider (Google Sign In for example)
2. Flutter web server then issues requests to the backend server with the certs its configured with in the bundle. The end user is unaware of these certs and shouldn't really be concerned with them. The certs are purely for communication between front end and backend, and not for communication between user and frontend.

**Comment by asashour** [comment]
If I may add something to explain a little. There is no "Flutter frontend web server" which sends requests to "backend server".

For the Flutter Web, it is compiled at the end to JavaScript, which runs on the Browser.

So, the user interacts with the Browser, which sends the HTTS(s) requests to the web server (the backend).

What I understand is that there is no Web standard to be used by the JavaScript (or Flutter) to a define user-side certificate. The certificate needs to be manually installed by the user at the system level, and not by the JavaScript or the application which runs on the Browser.

The JavaScript running on the browser doesn't have access to any local files (for security reasons).

[Google Sign in](https://developers.google.com/identity/gsi/web/guides/overview) (and others) usually use JSON Web Token (JWT), which is something different from client SSL.

**Comment by pranavpsawant** [comment]
@mraleph 
> That's the question better asked to standard bodies like W3C and WHATWG and browser vendors. They have decided to not include any APIs for mTLS support in neither XHR nor fetch.

Fair point, but that goes for cases where a user requires certs to access the front end. As I said, the issue is for the case of the front end making secure calls to backend using mTLS, and not for the end user trying to access the front end (which is gated by oAuth and not mTLS)

> One question you could ask yourself is the following: how does client certificate get to the client? If it is downloaded over the network like the rest of the application assets, then what is the point of having this certificate to begin with?

The user is not downloading the certificate. The certificate Is part of the front end bundle which would be hosted on asome AWS machine. Again let me clarify, there are two levels of auth workflows here:

1. User uses oAuth to connect to the web front. (Auth mechanism: OAuth). This is sorted out.
2. Web Front (hosted somewhere) uses its own client certs to connect to the backend servers using mTLS

@asashour 

> There is no "Flutter frontend web server" which sends requests to "backend server". For the Flutter Web, it is compiled at the end to JavaScript, which runs on the Browser.

Sure, so when we deploy the flutter web on a host, I was under the assumption that we will bundle the certs as part of its application package, and then when it comes to making those backend calls, these certs will then be used for auth ?

> What I understand is that there is no Web standard to be used by the JavaScript (or Flutter) to a define user-side certificate. The certificate needs to be manually installed by the user at the system level, and not by the JavaScript or the application which runs on the Browser.

Can you expand on what do you mean by system level. I am thinking the certificate would be on the machine that hosts the front end. And this frontend will be using the cert to connect to backend. The end user (person interacting with the web front) will not be using certs to connect to webfront but using OAuth identity provider like google to authenticate itself.

**Comment by mraleph** [comment]
> The certificate Is part of the front end bundle which would be hosted on asome AWS machine. Again let me clarify, there are two levels of auth workflows here:
> 
> 1. User uses oAuth to connect to the web front. (Auth mechanism: OAuth). This is sorted out.
> 2. Web Front (hosted somewhere) uses its own client certs to connect to the backend servers using mTLS

I am puzzled. Can you clarify what application do you expect to make requests that use mTLS, what language that application is written in and where it is running? 

If it is some server hosted on AWS then this has nothing to do with Flutter Web, really. 

If it is Flutter Web application - then that whole application runs in the browser. So it is bound by browser capabilities and APIs

**Comment by asashour** [comment]
When a Flutter web app is deployed on a web server, it is simply JavaScript files, which are downloaded by the browser, and run on the browser, and not on the hosting web server. The hosting machine doesn't actually run them at all, then are just static files (similar to HTML or .jpg).

So, the container which executes it is the browser, and it then triggers HTTP requests to some external website. The same rules of JavaScript applies (because it is JavaScript running on the browser).

What I meant by the system, is the Operating System which hosts the browsers, e.g. the web user OS, on which Chrome or Firefox, etc. is installed. That's the place where the browser can ask for certificates. Please read how JavaScript on the browser works.  Whatever it can do, so can Flutter.

**Comment by pranavpsawant** [comment]
@mraleph and @asashour  Thanks for persisting with me so far :) 

>  Can you clarify what application do you expect to make requests that use mTLS, what language that application is written in and where it is running?

Yes, I expect the flutter web application to make requests to the backend java web server using mTLS.

1. Backend is a Java Vertx application hosted on a EC2 instance in AWS. Backend apis are gated by mTLS, thus any call that goes to the backend requires certs.

2. Frontend is a Flutter web application.

> When a Flutter web app is deployed on a web server, it is simply JavaScript files, which are downloaded by the browser, and run on the browser, and not on the hosting web server. The hosting machine doesn't actually run them at all, then are just static files (similar to .html or .jpg).

This was missing I guess. Thanks for clarifying
