### ISSUE TITLE
Consider publishing a `1.0.0` version of package:http

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/http#837]
We should consider publishing a `1.0.0` version of package:http (it's one of our `dart.dev` packages).

**Comment by devoncarew** [comment]
From a discussion, there are some breaking changes we'd like to make to the package:http API. We'd want to consider whether we do that before or after we rev. to 1.0.

`http` is currently at `0.13.5`; so the options would be to 
- release an `0.14.0` with the breaking changes, then release a `1.0.0`
- release a `1.0.0` with the current contents, then in the future introduce any breaking changes as `2.0.0`
- possibly, introduce the desired breaking changes concurrently with a `1.0.0` release

**Comment by brianquinlan** [comment]
Done!
