### ISSUE TITLE
[cronet_http] Support running in a different isolate

### ISSUE THREAD

**Issue by knaeckeKami** [dart-lang/http#876]
Hi!

I'd like to give some feedback on cronet_http:

Currently, it is not possible to initiate http requests from an different isolate than the main isolate.

This due to the usage of `setMessageHandler()` in the call to `receiveBroadcastStream()`: https://github.com/dart-lang/http/blob/e2c4e6f7aea17e89a6c56d0ff3d3a200983fb9fe/pkgs/cronet_http/lib/src/cronet_client.dart#L239

Which is not supported on non-root isolates, see https://github.com/flutter/flutter/issues/119207 and

https://api.flutter.dev/flutter/services/BackgroundIsolateBinaryMessenger/setMessageHandler.html

```dart
void setMessageHandler(String channel, MessageHandler? handler) {
  throw UnsupportedError(
      'Background isolates do not support setMessageHandler(). Messages from the host platform always go to the root isolate.');
}
```

It's a common use case to have the network logic in a separate isolate in order to not block the UI while e.h. parsing JSON, but this makes it more difficult to do so.

cupertino_http uses ffi, so it does not have this issue.

Reproducible code:

run this on an android device:

```dart

import 'dart:isolate';
import 'package:flutter/services.dart';
import 'package:cronet_http/cronet_http.dart';

void main() {

  RootIsolateToken? token = RootIsolateToken.instance;
  Isolate.run(() async {
    print('Isolate running ${Isolate.current.debugName}');
    try {
      BackgroundIsolateBinaryMessenger.ensureInitialized(token!);
      final resp = await CronetClient.defaultCronetEngine().get(Uri.parse('https://www.google.com'));
      print(resp.body);
    } catch (e) {
      print(e);
    }
  });


}
```

**Comment by brianquinlan** [comment]
Thanks for the report. I think that we need to wait for the issue with `setMessageHandler` to be fixed.

**Comment by atrope** [comment]
Can we provide a workaround  to this issue so we can use http in isolates? Maybe a flag or something?

**Comment by brianquinlan** [comment]
Could you explain what you mean about adding a flag?

**Comment by atrope** [comment]
@brianquinlan as @knaeckeKami wrote, on iOS it works because it is using ffi maybe we can have a flag in android http to use another way of making the requests without the use of `setMessageHandler` because by the looks of it it will not be supported in the near future by flutter and i think using http in an isolate can make a huge difference in a lot of use cases.

**Comment by knaeckeKami** [comment]
Potentially it could work with [jnigen](https://github.com/dart-lang/jnigen). But I did not investigate further

**Comment by brianquinlan** [comment]
We have a [gSoC project](https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2023-Project-Ideas#idea-build-a-dart-http-client-using-java-apis) that will use `package:jnigen` to wrap Java HTTP APIs that will start on the June 5th.

**Comment by brianquinlan** [comment]
One hacky fix be to ask the user to run an initialization method on the root isolate that does that actual `send`ing over the channel but accepts messages from other isolates.

Like:
```dart
late SendPort sendPort;
late ReceivePort receivePort;
late BasicMessageChannel channel;

void setup() {
  sendPort = SendPort();
  receivePort = sendPort.receivePort;
  channel = BasicMessageChannel(...);
  receivePort.listen((msg) {
    channel.send(msg.value).then((result) {
      msg.sendPort.send(result);
    });
  });
}

// This is a public API method:
Future<int> double(int x) {
  SendPort sp = SendPort();
  ReceivePort rp = sp.ReceivePort();
 
  sendPort.send({value: x, sendPort: sp});
  return rp.first;
}
```

**Comment by brianquinlan** [comment]
This is now fixed at HEAD. Would anyone like to test this in a pre-release version? If so I'll release `0.3.0-jni` and prioritize any feedback that I get about it.

Please let me know.

**Comment by atrope** [comment]
I can test in my flutter app. I have all working in ios, if you release a version I can test in Android

**Comment by brianquinlan** [comment]
I've [released version 0.3.0-jni](https://pub.dev/packages/cronet_http/versions/0.3.0-jni). You can use it by adding this to your `pubspec.yaml`:

```yaml
dependencies:
  cronet_http: ^0.3.0-jni
```

Please let me know if you have any issues!

**Comment by brianquinlan** [comment]
Hey @atrope and @ knaeckeKami - any luck using the jnigen version?

**Comment by knaeckeKami** [comment]
Didn't get to try it out yet - sorry. 
But I see that I can give feedback until next week.

**Comment by knaeckeKami** [comment]
We've been using cronet_http  [0.4.0-jni](https://pub.dev/packages/cronet_http/versions/0.4.0-jni) internally (mainly for graphql requests and downlaoding network images ) and did not find any issues as of now.

**Comment by brianquinlan** [comment]
@knaeckeKami Thank you very much for testing it!

**Comment by atrope** [comment]
I Know i am late to the show but i can confirm it is working as expected :)

**Comment by brianquinlan** [comment]
Thanks @atrope !
