### ISSUE TITLE
Can't request Korean domain address.

### ISSUE THREAD

**Issue by ainusdev** [dart-lang/http#890]
Hi there.

I requested a .com address in Korean.

The address is '감자.com'.

However, I received the following error result.

<img width="1140" alt="스크린샷 2023-03-09 오후 9 22 23" src="https://user-images.githubusercontent.com/50290684/224022370-5a94099a-b67e-43b9-a31e-5dd682e35752.png">

**Comment by lavara123** [comment]
```dart

import 'package:http/http.dart' as http;
import 'package:idna/idna.dart';

void main() async {
  var punycode = toASCII('감자.com'); // Alan adını Punycode biçimine dönüştürün
  var uri = Uri.parse('http://$punycode'); // Uri nesnesine dönüştürün
  var response = await http.get(uri); // GET isteği gönderin
  print(response.body);
}

```

**Comment by ainusdev** [comment]
> ```dart
> import 'package:http/http.dart' as http;
> import 'package:idna/idna.dart';
> 
> void main() async {
>   var punycode = toASCII('감자.com'); // Alan adını Punycode biçimine dönüştürün
>   var uri = Uri.parse('http://$punycode'); // Uri nesnesine dönüştürün
>   var response = await http.get(uri); // GET isteği gönderin
>   print(response.body);
> }
> ```

Thank you so much !!!!!!! Amazing !!!!!!!!

xn--od1ba
