### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/http#91]
I think we're near a point where we could do CI on `http`.

@nex3 @kevmoo maybe time to enable Travis?

**Comment by nex3** [comment]
I'm in favor. @kevmoo will have to flip the switch, though.

**Comment by donny-dont** [comment]
Ok I'll make a PR that puts the repo in a state that `pub run test` will work. Then @kevmoo can modify accordingly to hook in the CI.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/http/pull/94

**Comment by donny-dont** [comment]
Fixed with #96
