### ISSUE TITLE
Disjoint behavior for network level errors between native & web 

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/http#927]
## Use case

Developers that target both native and the web don't have a good way to handle network related errors surfaced by `package:http`.

### Example:

```
import 'package:http/http.dart';

void main() async {
          try {
            await get(Uri.parse('https://google.com'));
          } catch (error) {
            print(error is ClientException);
            print(error.runtimeType);
            print(error);
          }
}
```

On native, this gives `_ClientSocketException` & `Failed host lookup: 'google.com'`,
while on the web this is `ClientException` & `XMLHttpRequest error.`.

## Proposal

Allow the `ClientException` to contain a cause (probably an enum?) of the network level error,
so that people don't have to rely on matching the `message`.

**Comment by brianquinlan** [comment]
By design (for security reasons), the web APIs do not surface detailed error information.
