### ISSUE TITLE
Update the readme to reflect the status change

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/http#955]
We should update the readme for package:cupertino_http (https://github.com/dart-lang/http/blob/master/pkgs/cupertino_http/README.md); it currently says 'Status: Experimental' and that it's published through labs.dart.dev.

**Comment by brianquinlan** [comment]
Oops, missed this. But it was fixed in https://github.com/dart-lang/http/commit/8834aecd973446263a23e1d2ea17932721c87281
