### ISSUE TITLE
[http_client_conformance_tests] ERR_H2_OR_QUIC_REQUIRED

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/http#968]
I'm trying to run `http_client_conformance_tests` against fetch based client ([`fetch_client`](https://github.com/Zekfad/fetch_client)) and test streaming request body.
Locally, using online servers everything works fine, but using `http_client_conformance_tests` brings some mystical error:
Running web test with `canStreamRequestBody` results in `ERR_H2_OR_QUIC_REQUIRED`.

**Comment by natebosch** [comment]
Does the fetch API require that the server supports HTTP2? 
https://stackoverflow.com/questions/76412619/receiving-error-neterr-h2-or-quic-required-when-using-fetch-api-with-a-strea


We don't have that support in the Dart SDK. I'm not sure if it would be worth adding a dependency on `package:http2` and implementing the test server that way. WDYT @brianquinlan

**Comment by brianquinlan** [comment]
@Zekfad do you have a traceback or code that we could look at?

I see that you have a different code path if `FetchClient` is constructed with `streamRequests`  set to true (was it?):
https://github.com/Zekfad/fetch_client/blob/master/lib/src/fetch_client.dart#L78

BTW, how are you consuming the tests? Are you using a git url and branch reference in your `pubspec.yaml`?

**Comment by Zekfad** [comment]
@brianquinlan my test is here (commented out for not):
https://github.com/Zekfad/fetch_client/blob/master/test/client_conformance_test.dart#L46-L60

I do use pubspec with git:
https://github.com/Zekfad/fetch_client/blob/master/pubspec.yaml#L29-L33

**Comment by brianquinlan** [comment]
Hey @Zekfad,

Do you see a similar error if you test with Firefox?

FWIW, it looks like that error code is coming from https://chromium.googlesource.com/chromium/src/+/master/net/http/http_stream_factory_job.cc#1184 but I couldn't find anything relevant in the Chrome issue tracker.

If you can determine that this is a Chrome issue then the most pragmatic thing to do would probably be to leave the test commented out and add a note to your API docs saying that `streamRequests` will not work with Chrome when communicating with HTTP1 servers.

You could also file a chrome bug.

**Comment by Zekfad** [comment]
Hi @brianquinlan, it looks like FF doesn't support `Request` streaming  as of now - see bottom chart at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request#:~:text=Send%20ReadableStream%20in%20request%20body) (Send `ReadableStream` in request body).

**Comment by brianquinlan** [comment]
@Zekfad Then maybe the best approach would be to mention in your docs that the functionality is not widely supported (with that MDN link) and that Chrome only supports it with HTTP/2 and HTTP/3 connections.

BTW, I didn't know that anyone has using the `http_client_conformance_tests` - is there anything that I could do to make them easier to use? Any other feedback?

**Comment by Zekfad** [comment]
Thanks for your help @brianquinlan!

I think tests are quite good as of now, the only inconvenience is that they are not published, and I don't really see `1.0.0` tag.
It would be great to be able to test against known version of `http` package assuming if new features would be added (like recent isolate test).

In a future, if http2/3 make it's way to `http` package I think tests would be more rich on that side, but for now its's great.

**Comment by brianquinlan** [comment]
@Zekfad I think that we would have to increase the major version of `package:http_client_conformance_tests` every time that a new test were adding because it would be potentially breaking.

But it still probably makes sense to publish it.
