### ISSUE TITLE
Fix Multipart support

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/http#97]
CC @donny-dont

**Comment by donny-dont** [comment]
@nex3 do you have any idea where you want to go with the multipart support?

I was thinking maybe more of a builder sort of setup.

**Comment by nex3** [comment]
That's a good question. Maybe just expose it as a separate constructor:

```dart
new Request.multipart(String method, url, List<MultipartFile> files,
    {Map<String, String> fields,
    Map<String, String> headers,
    Map<String, Object> context});
```

It's not orthogonal to the other utility constructors, but I don't see a great way to make that work unless we add a totally new type of body which doesn't seem ideal.
