### ISSUE TITLE
Support for StreamedRequest

### ISSUE THREAD

**Issue by Vovcharaa** [dart-lang/http#974]
Right now native clients drain the stream of StreamedRequest before making a request.
https://github.com/dart-lang/http/blob/d68081f50f0f0a8928e42237e937dcc69cc5d890/pkgs/cupertino_http/lib/src/cupertino_client.dart#L236
This makes it impossible to track the progress of uploading files for example.

**Comment by Vovcharaa** [comment]
@brianquinlan I tested your implementation of this feature and found some issues.
https://github.com/dart-lang/http/blob/b2067710f88980fc0fee43ec3380bce089f001db/pkgs/cupertino_http/lib/src/cupertino_api.dart#L124-L127
`StreamQueue` is buffering everything it can consume before sending it to the remote.
This does not fix the problem when it is needed to track upload progress or with sending large files.

**Comment by Vovcharaa** [comment]
@brianquinlan Do I need to create a separate issue for this?

**Comment by brianquinlan** [comment]
@Vovcharaa Could you please file a new issue? Could you include the stream that you are sending? AFAIK, `_hasData` is only buffering the first non-empty `List<int>` in the stream.

`_streamToNSInputStream` is only providing data when requested to by the Apple's client implementation and is, in my experience, providing less data than requested.

**Comment by Vovcharaa** [comment]
@brianquinlan https://github.com/dart-lang/http/issues/997
