### ISSUE TITLE
[http_client_conformance_tests] Test large payload.

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/http#977]
I've come across issue using Fetch that >64KiB request are failing with keep-alive:

> __4.5. HTTP-network-or-cache fetch__
>
> > 8.10.5: If the sum of _contentLength_ and _inflightKeepaliveBytes_ is greater
> > than 64 kibibytes, then return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).
> 
> _Source: [Fetch. Living Standard — Last Updated 19 June 2023](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch)_

I would appreciate to have some sort of test for this behavior.

Currently you have to  **explicitly** set [`BaseRequest.persistentConnection`](https://pub.dev/documentation/http/latest/http/BaseRequest/persistentConnection.html) to `false` to make it work which I believe is correct behavior, but not something widely known.

**Comment by brianquinlan** [comment]
Does https://github.com/dart-lang/http/pull/984/files include the test that you are looking for?

BTW, feel free to send in your own pull requests to add conformance tests - they are pretty easy to write and they benefit everyone working on  `package:http` `Client`s.

**Comment by Zekfad** [comment]
Something like that, but need a flag to make it reverse, because with persistent connection and 64KiB payload it should fail with fetch, something like `webFetchKeepAliveBehavior: false` (with default false it's current test that follows io behavior, with true it tests that request fails and follows fetch behavior)

My laptop currently in service, if you could test use `fetch_client` module for behavior that corresponds to spec.

**Comment by brianquinlan** [comment]
@Zekfad I don't think that there is any hurry. I'd be happy for you to download the PR, make it correct for your use case, and then send me a new one.

**Comment by Zekfad** [comment]
This is fixed fixed in f585947d28f9be7588cd2440cd12642676e9c235 , thanks @brianquinlan !
