### ISSUE TITLE
http.delete body not working

### ISSUE THREAD

**Issue by Wotakoi** [dart-lang/http#998]
http.delete body not working. working well when put it direcly on uri query

**Comment by natebosch** [comment]
Can you provide a reproduction case? What are you trying to do? What specifically is failing?

**Comment by brianquinlan** [comment]
Hi @Wotakoi 

I just wanted to confirm that you are no longer seeing this issue? Because this seems like an important bug.

**Comment by Wotakoi** [comment]
i don't really know if it is supported or not but when i use it like this:
 
var response = await http.delete(url, body: {'uid': uid});

uid on body can't be read. but if directly on the url like this:

"example.com/remove-item?uid=$uid"

can go well.

i close it cuz someone told me that it is not supported. and srry if my english so bad :'

**Comment by brianquinlan** [comment]
@Wotakoi , I understood you perfectly, thanks!
